namespace IntegraRP.Contracts.Flow;

public sealed record ProcessDefinitionResponse(Guid Id, Guid TenantId, string Codigo, string Nome, string Status, Guid? VersaoPublicadaId);
public sealed record CreateProcessDefinitionRequest(string Codigo, string Nome, string? Descricao, string? ModuloOrigem, Guid? SetorDonoId);
public sealed record UpdateProcessDefinitionRequest(string Nome, string? Descricao, string? ModuloOrigem, Guid? SetorDonoId);
public sealed record ProcessVersionResponse(Guid Id, Guid DefinitionId, int NumeroVersao, string Status, DateTimeOffset? PublicadoEm);
public sealed record CreateProcessVersionRequest(string? Observacao);
public sealed record AddProcessElementRequest(string Codigo, string Nome, string Tipo, Guid? SetorResponsavelId, Guid? UsuarioResponsavelId, Guid? PerfilResponsavelId, int? SlaMinutos, string? FormularioJson, string? ChecklistJson, string? RegraJson);
public sealed record UpdateProcessElementRequest(string Nome, string? Descricao, Guid? SetorResponsavelId, Guid? UsuarioResponsavelId, Guid? PerfilResponsavelId, int? SlaMinutos, string? FormularioJson, string? ChecklistJson, string? RegraJson);
public sealed record AddProcessTransitionRequest(Guid ElementoOrigemId, Guid ElementoDestinoId, string Codigo, string? Nome, string CondicaoTipo, string? CondicaoJson, decimal Ordem);
public sealed record UpdateProcessTransitionRequest(string? Nome, string CondicaoTipo, string? CondicaoJson, decimal Ordem);
public sealed record PublishProcessVersionRequest(Guid? UsuarioId);
public sealed record ProcessDiagramResponse(ProcessVersionResponse Version, IReadOnlyList<ProcessElementResponse> Elements, IReadOnlyList<ProcessTransitionResponse> Transitions);
public sealed record ProcessElementResponse(Guid Id, string Codigo, string Nome, string Tipo, int? SlaMinutos);
public sealed record ProcessTransitionResponse(Guid Id, Guid ElementoOrigemId, Guid ElementoDestinoId, string Codigo, string CondicaoTipo, string CondicaoJson);
public sealed record StartProcessInstanceRequest(string Titulo, string? OrigemTipo, Guid? OrigemId, Guid? UsuarioId, Dictionary<string, object?> Variaveis);
public sealed record StartProcessInstanceResponse(Guid Id, string Codigo, string Status, Guid? TarefaInicialId);
public sealed record ProcessInstanceResponse(Guid Id, Guid DefinitionId, string Codigo, string Titulo, string Status, DateTimeOffset IniciadoEm, DateTimeOffset? PrazoEm);
public sealed record ProcessInstanceDetailResponse(ProcessInstanceResponse Instance, IReadOnlyList<WorkflowTaskResponse> Tasks, IReadOnlyList<WorkflowAuditEventResponse> Audit);
public sealed record CancelProcessInstanceRequest(string Motivo, Guid? UsuarioId);
public sealed record WorkflowTaskResponse(Guid Id, Guid? ProcessInstanceId, string Codigo, string Titulo, string Status, string Prioridade, Guid? UsuarioResponsavelId, Guid? SetorResponsavelId, DateTimeOffset? PrazoEm);
public sealed record WorkflowTaskDetailResponse(WorkflowTaskResponse Task, IReadOnlyList<WorkflowTaskCommentResponse> Comments, IReadOnlyList<WorkflowTaskAttachmentResponse> Attachments);
public sealed record AssignWorkflowTaskRequest(Guid UsuarioResponsavelId, Guid? UsuarioExecutorId);
public sealed record CompleteWorkflowTaskRequest(Guid UsuarioId, string? FormularioRespostaJson, string? ChecklistRespostaJson, Dictionary<string, object?> Variaveis);
public sealed record AddWorkflowTaskCommentRequest(Guid UsuarioId, string Comentario);
public sealed record AddWorkflowTaskAttachmentRequest(Guid UsuarioId, string NomeArquivo, string Url, string? ContentType);
public sealed record WorkflowTaskCommentResponse(Guid Id, Guid UsuarioId, string Comentario, DateTimeOffset CriadoEm);
public sealed record WorkflowTaskAttachmentResponse(Guid Id, string NomeArquivo, string Url, DateTimeOffset CriadoEm);
public sealed record FlowDashboardSummaryResponse(int ProcessosPublicados, int ProcessosEmAndamento, int TarefasAbertas, int TarefasAtrasadas, int ProcessosConcluidos);
public sealed record OverdueTaskResponse(Guid Id, string Codigo, string Titulo, DateTimeOffset PrazoEm);
public sealed record OverdueProcessResponse(Guid Id, string Codigo, string Titulo, DateTimeOffset PrazoEm);
public sealed record WorkflowAuditEventResponse(Guid Id, string TipoEvento, string Descricao, DateTimeOffset CriadoEm);
public sealed record WorkflowBusinessEventContract(Guid Id, string TipoEvento, string PayloadJson, string Status);
public sealed record WorkflowOutboxEventContract(Guid Id, string TipoEvento, string Canal, string PayloadJson, string Status);
