using IntegraRP.Application.Abstractions.OperationalTemplates;
using IntegraRP.Application.Common;
using IntegraRP.Contracts.OperationalTemplates;
using Microsoft.Extensions.Logging;

namespace IntegraRP.Application.OperationalTemplates;

public sealed class ListOperationalTemplatePackagesUseCase(IOperationalTemplatePackageRepository repo, ILogger<ListOperationalTemplatePackagesUseCase> logger) { public async Task<Result<IReadOnlyList<OperationalTemplatePackageResponse>>> ExecuteAsync(Guid tenantId, CancellationToken ct) { try { return Result<IReadOnlyList<OperationalTemplatePackageResponse>>.Success(await repo.ListAsync(tenantId, ct)); } catch (Exception ex) { logger.LogError(ex, "List packages failed"); return Result<IReadOnlyList<OperationalTemplatePackageResponse>>.Failure(ex.Message); } } }
public sealed class ListOperationalTemplatesUseCase(IOperationalTemplateRepository repo, ILogger<ListOperationalTemplatesUseCase> logger) { public async Task<Result<IReadOnlyList<OperationalTemplateResponse>>> ExecuteAsync(Guid tenantId, CancellationToken ct) { try { return Result<IReadOnlyList<OperationalTemplateResponse>>.Success(await repo.ListAsync(tenantId, ct)); } catch (Exception ex) { logger.LogError(ex, "List templates failed"); return Result<IReadOnlyList<OperationalTemplateResponse>>.Failure(ex.Message); } } }
public sealed class GetOperationalTemplateByIdUseCase(IOperationalTemplateRepository repo, ILogger<GetOperationalTemplateByIdUseCase> logger) { public async Task<Result<OperationalTemplateResponse?>> ExecuteAsync(Guid tenantId, Guid id, CancellationToken ct) { try { return Result<OperationalTemplateResponse?>.Success(await repo.GetAsync(tenantId, id, ct)); } catch (Exception ex) { logger.LogError(ex, "Get template failed"); return Result<OperationalTemplateResponse?>.Failure(ex.Message); } } }
public sealed class PreviewOperationalTemplateUseCase(IOperationalTemplatePreviewService svc, ILogger<PreviewOperationalTemplateUseCase> logger) { public async Task<Result<OperationalTemplatePreviewResponse>> ExecuteAsync(Guid tenantId, Guid id, CancellationToken ct) { try { return Result<OperationalTemplatePreviewResponse>.Success(await svc.PreviewAsync(tenantId, id, ct)); } catch (Exception ex) { logger.LogError(ex, "Preview template failed"); return Result<OperationalTemplatePreviewResponse>.Failure(ex.Message); } } }
public sealed class InstallOperationalTemplateUseCase(IOperationalTemplateInstaller installer, ILogger<InstallOperationalTemplateUseCase> logger) { public async Task<Result<InstallOperationalTemplateResponse>> ExecuteAsync(Guid tenantId, Guid id, Guid? userId, IReadOnlyDictionary<string, string>? cfg, CancellationToken ct) { try { return Result<InstallOperationalTemplateResponse>.Success(await installer.InstallTemplateAsync(tenantId, id, userId, cfg, ct)); } catch (Exception ex) { logger.LogError(ex, "Install template failed"); return Result<InstallOperationalTemplateResponse>.Failure(ex.Message); } } }
public sealed class InstallOperationalTemplatePackageUseCase(IOperationalTemplateInstaller installer, ILogger<InstallOperationalTemplatePackageUseCase> logger) { public async Task<Result<InstallOperationalTemplateResponse>> ExecuteAsync(Guid tenantId, Guid id, Guid? userId, IReadOnlyDictionary<string, string>? cfg, CancellationToken ct) { try { return Result<InstallOperationalTemplateResponse>.Success(await installer.InstallPackageAsync(tenantId, id, userId, cfg, ct)); } catch (Exception ex) { logger.LogError(ex, "Install package failed"); return Result<InstallOperationalTemplateResponse>.Failure(ex.Message); } } }
public sealed class ListOperationalTemplateInstallationsUseCase(IOperationalTemplateInstallationRepository repo, ILogger<ListOperationalTemplateInstallationsUseCase> logger) { public async Task<Result<IReadOnlyList<OperationalTemplateInstallationResponse>>> ExecuteAsync(Guid tenantId, CancellationToken ct) { try { return Result<IReadOnlyList<OperationalTemplateInstallationResponse>>.Success(await repo.ListAsync(tenantId, ct)); } catch (Exception ex) { logger.LogError(ex, "List installations failed"); return Result<IReadOnlyList<OperationalTemplateInstallationResponse>>.Failure(ex.Message); } } }
public sealed class GetOperationalTemplateInstallationLogUseCase(IOperationalTemplateInstallationRepository repo, ILogger<GetOperationalTemplateInstallationLogUseCase> logger) { public async Task<Result<IReadOnlyList<OperationalTemplateInstallationLogResponse>>> ExecuteAsync(Guid tenantId, Guid id, CancellationToken ct) { try { return Result<IReadOnlyList<OperationalTemplateInstallationLogResponse>>.Success(await repo.GetLogsAsync(tenantId, id, ct)); } catch (Exception ex) { logger.LogError(ex, "Installation logs failed"); return Result<IReadOnlyList<OperationalTemplateInstallationLogResponse>>.Failure(ex.Message); } } }
public sealed class ValidateOperationalTemplateUseCase(IOperationalTemplateValidationService svc, ILogger<ValidateOperationalTemplateUseCase> logger) { public async Task<Result<IReadOnlyList<string>>> ExecuteAsync(Guid tenantId, Guid id, CancellationToken ct) { try { return Result<IReadOnlyList<string>>.Success(await svc.ValidateAsync(tenantId, id, ct)); } catch (Exception ex) { logger.LogError(ex, "Validate template failed"); return Result<IReadOnlyList<string>>.Failure(ex.Message); } } }
