using IntegraRP.Application.Abstractions.Operations;
using IntegraRP.Application.Common;
using IntegraRP.Contracts.Operations;
using Microsoft.Extensions.Logging;

namespace IntegraRP.Application.Operations;

public sealed class CreateDeliveryRouteUseCase(IDeliveryRouteRepository repo, ILogger<CreateDeliveryRouteUseCase> logger) { public async Task<Result<DeliveryRouteResponse>> ExecuteAsync(CreateDeliveryRouteRequest request, CancellationToken ct) { try { return Result<DeliveryRouteResponse>.Success(await repo.CreateAsync(request, ct)); } catch (Exception ex) { logger.LogError(ex, "Create route failed"); return Result<DeliveryRouteResponse>.Failure(ex.Message); } } }
public sealed class UpdateDeliveryRouteUseCase(IDeliveryRouteRepository repo, ILogger<UpdateDeliveryRouteUseCase> logger) { public async Task<Result<DeliveryRouteResponse?>> ExecuteAsync(Guid tenantId, Guid id, UpdateDeliveryRouteRequest request, CancellationToken ct) { try { return Result<DeliveryRouteResponse?>.Success(await repo.ChangeStatusAsync(tenantId, id, request.Status, ct)); } catch (Exception ex) { logger.LogError(ex, "Update route failed"); return Result<DeliveryRouteResponse?>.Failure(ex.Message); } } }
public sealed class ListDeliveryRoutesUseCase(IDeliveryRouteRepository repo, ILogger<ListDeliveryRoutesUseCase> logger) { public async Task<Result<IReadOnlyList<DeliveryRouteResponse>>> ExecuteAsync(Guid tenantId, CancellationToken ct) { try { return Result<IReadOnlyList<DeliveryRouteResponse>>.Success(await repo.ListAsync(tenantId, ct)); } catch (Exception ex) { logger.LogError(ex, "List routes failed"); return Result<IReadOnlyList<DeliveryRouteResponse>>.Failure(ex.Message); } } }
public sealed class GetDeliveryRouteByIdUseCase(IDeliveryRouteRepository repo, ILogger<GetDeliveryRouteByIdUseCase> logger) { public async Task<Result<DeliveryRouteDetailResponse?>> ExecuteAsync(Guid tenantId, Guid id, CancellationToken ct) { try { return Result<DeliveryRouteDetailResponse?>.Success(await repo.GetAsync(tenantId, id, ct)); } catch (Exception ex) { logger.LogError(ex, "Get route failed"); return Result<DeliveryRouteDetailResponse?>.Failure(ex.Message); } } }
public sealed class AddDeliveryRouteStopUseCase(IDeliveryRouteRepository repo, ILogger<AddDeliveryRouteStopUseCase> logger) { public async Task<Result<DeliveryRouteStopResponse>> ExecuteAsync(Guid id, AddDeliveryRouteStopRequest request, CancellationToken ct) { try { return Result<DeliveryRouteStopResponse>.Success(await repo.AddStopAsync(id, request, ct)); } catch (Exception ex) { logger.LogError(ex, "Add stop failed"); return Result<DeliveryRouteStopResponse>.Failure(ex.Message); } } }
public sealed class ReorderDeliveryRouteStopsUseCase(IDeliveryRouteRepository repo, ILogger<ReorderDeliveryRouteStopsUseCase> logger) { public async Task<Result<string>> ExecuteAsync(Guid id, ReorderDeliveryRouteStopsRequest request, CancellationToken ct) { try { await repo.ReorderStopsAsync(id, request, ct); return Result<string>.Success("ok"); } catch (Exception ex) { logger.LogError(ex, "Reorder stops failed"); return Result<string>.Failure(ex.Message); } } }
public sealed class StartDeliveryRouteUseCase(IDeliveryRouteRepository r, ILogger<StartDeliveryRouteUseCase> l) { public Task<Result<DeliveryRouteResponse?>> ExecuteAsync(Guid t, Guid id, CancellationToken c) => Change(r, l, t, id, "em_rota", c); static async Task<Result<DeliveryRouteResponse?>> Change(IDeliveryRouteRepository r, ILogger l, Guid t, Guid id, string s, CancellationToken c) { try { return Result<DeliveryRouteResponse?>.Success(await r.ChangeStatusAsync(t, id, s, c)); } catch (Exception ex) { l.LogError(ex, "Route status failed"); return Result<DeliveryRouteResponse?>.Failure(ex.Message); } } }
public sealed class CompleteDeliveryRouteUseCase(IDeliveryRouteRepository r, ILogger<CompleteDeliveryRouteUseCase> l) { public async Task<Result<DeliveryRouteResponse?>> ExecuteAsync(Guid t, Guid id, CancellationToken c) { try { return Result<DeliveryRouteResponse?>.Success(await r.ChangeStatusAsync(t, id, "concluida", c)); } catch (Exception ex) { l.LogError(ex, "Complete route failed"); return Result<DeliveryRouteResponse?>.Failure(ex.Message); } } }
public sealed class CancelDeliveryRouteUseCase(IDeliveryRouteRepository r, ILogger<CancelDeliveryRouteUseCase> l) { public async Task<Result<DeliveryRouteResponse?>> ExecuteAsync(Guid t, Guid id, CancellationToken c) { try { return Result<DeliveryRouteResponse?>.Success(await r.ChangeStatusAsync(t, id, "cancelada", c)); } catch (Exception ex) { l.LogError(ex, "Cancel route failed"); return Result<DeliveryRouteResponse?>.Failure(ex.Message); } } }
public sealed class CreateDeliveryManifestUseCase(IDeliveryManifestRepository r, ILogger<CreateDeliveryManifestUseCase> l) { public async Task<Result<DeliveryManifestResponse>> ExecuteAsync(CreateDeliveryManifestRequest q, CancellationToken c) { try { return Result<DeliveryManifestResponse>.Success(await r.CreateAsync(q, c)); } catch (Exception ex) { l.LogError(ex, "Create manifest failed"); return Result<DeliveryManifestResponse>.Failure(ex.Message); } } }
public sealed class AddDeliveryManifestItemUseCase(IDeliveryManifestRepository r, ILogger<AddDeliveryManifestItemUseCase> l) { public async Task<Result<DeliveryManifestItemResponse>> ExecuteAsync(Guid id, AddDeliveryManifestItemRequest q, CancellationToken c) { try { return Result<DeliveryManifestItemResponse>.Success(await r.AddItemAsync(id, q, c)); } catch (Exception ex) { l.LogError(ex, "Add manifest item failed"); return Result<DeliveryManifestItemResponse>.Failure(ex.Message); } } }
public sealed class ConfirmDeliveryManifestUseCase(IDeliveryManifestRepository r, ILogger<ConfirmDeliveryManifestUseCase> l) { public async Task<Result<DeliveryManifestResponse?>> ExecuteAsync(Guid t, Guid id, CancellationToken c) { try { return Result<DeliveryManifestResponse?>.Success(await r.ChangeStatusAsync(t, id, "conferido", c)); } catch (Exception ex) { l.LogError(ex, "Confirm manifest failed"); return Result<DeliveryManifestResponse?>.Failure(ex.Message); } } }
public sealed class StartManifestRouteUseCase(IDeliveryManifestRepository r, ILogger<StartManifestRouteUseCase> l) { public async Task<Result<DeliveryManifestResponse?>> ExecuteAsync(Guid t, Guid id, CancellationToken c) { try { return Result<DeliveryManifestResponse?>.Success(await r.ChangeStatusAsync(t, id, "em_rota", c)); } catch (Exception ex) { l.LogError(ex, "Start manifest failed"); return Result<DeliveryManifestResponse?>.Failure(ex.Message); } } }
public sealed class CompleteDeliveryManifestUseCase(IDeliveryManifestRepository r, ILogger<CompleteDeliveryManifestUseCase> l) { public async Task<Result<DeliveryManifestResponse?>> ExecuteAsync(Guid t, Guid id, CancellationToken c) { try { return Result<DeliveryManifestResponse?>.Success(await r.ChangeStatusAsync(t, id, "finalizado", c)); } catch (Exception ex) { l.LogError(ex, "Complete manifest failed"); return Result<DeliveryManifestResponse?>.Failure(ex.Message); } } }
public sealed class ListDeliveryManifestsUseCase(IDeliveryManifestRepository r, ILogger<ListDeliveryManifestsUseCase> l) { public async Task<Result<IReadOnlyList<DeliveryManifestResponse>>> ExecuteAsync(Guid t, CancellationToken c) { try { return Result<IReadOnlyList<DeliveryManifestResponse>>.Success(await r.ListAsync(t, c)); } catch (Exception ex) { l.LogError(ex, "List manifests failed"); return Result<IReadOnlyList<DeliveryManifestResponse>>.Failure(ex.Message); } } }
public sealed class GetDeliveryManifestByIdUseCase(IDeliveryManifestRepository r, ILogger<GetDeliveryManifestByIdUseCase> l) { public async Task<Result<DeliveryManifestDetailResponse?>> ExecuteAsync(Guid t, Guid id, CancellationToken c) { try { return Result<DeliveryManifestDetailResponse?>.Success(await r.GetAsync(t, id, c)); } catch (Exception ex) { l.LogError(ex, "Get manifest failed"); return Result<DeliveryManifestDetailResponse?>.Failure(ex.Message); } } }
public sealed class RegisterProofOfDeliveryUseCase(IProofOfDeliveryRepository r, ILogger<RegisterProofOfDeliveryUseCase> l) { public async Task<Result<ProofOfDeliveryResponse>> ExecuteAsync(RegisterProofOfDeliveryRequest q, CancellationToken c) { try { return Result<ProofOfDeliveryResponse>.Success(await r.RegisterAsync(q, c)); } catch (Exception ex) { l.LogError(ex, "POD failed"); return Result<ProofOfDeliveryResponse>.Failure(ex.Message); } } }
public sealed class RegisterDeliveryOccurrenceUseCase(IDeliveryOccurrenceRepository r, ILogger<RegisterDeliveryOccurrenceUseCase> l) { public async Task<Result<DeliveryOccurrenceResponse>> ExecuteAsync(RegisterDeliveryOccurrenceRequest q, CancellationToken c) { try { return Result<DeliveryOccurrenceResponse>.Success(await r.RegisterAsync(q, c)); } catch (Exception ex) { l.LogError(ex, "Occurrence failed"); return Result<DeliveryOccurrenceResponse>.Failure(ex.Message); } } }
public sealed class ResolveDeliveryOccurrenceUseCase(IDeliveryOccurrenceRepository r, ILogger<ResolveDeliveryOccurrenceUseCase> l) { public async Task<Result<DeliveryOccurrenceResponse?>> ExecuteAsync(Guid t, Guid id, ResolveDeliveryOccurrenceRequest q, CancellationToken c) { try { return Result<DeliveryOccurrenceResponse?>.Success(await r.ResolveAsync(t, id, q, c)); } catch (Exception ex) { l.LogError(ex, "Resolve occurrence failed"); return Result<DeliveryOccurrenceResponse?>.Failure(ex.Message); } } }
public sealed class GetDeliveryMonitoringDashboardUseCase(IDeliveryMonitoringService s, ILogger<GetDeliveryMonitoringDashboardUseCase> l) { public async Task<Result<DeliveryMonitoringDashboardResponse>> ExecuteAsync(Guid t, CancellationToken c) { try { return Result<DeliveryMonitoringDashboardResponse>.Success(await s.GetDashboardAsync(t, c)); } catch (Exception ex) { l.LogError(ex, "Dashboard failed"); return Result<DeliveryMonitoringDashboardResponse>.Failure(ex.Message); } } }
public sealed class ListPendingDeliveriesUseCase(IDeliveryMonitoringService s, ILogger<ListPendingDeliveriesUseCase> l) { public async Task<Result<IReadOnlyList<DeliveryRouteStopResponse>>> ExecuteAsync(Guid t, CancellationToken c) { try { return Result<IReadOnlyList<DeliveryRouteStopResponse>>.Success(await s.ListPendingDeliveriesAsync(t, c)); } catch (Exception ex) { l.LogError(ex, "Pending failed"); return Result<IReadOnlyList<DeliveryRouteStopResponse>>.Failure(ex.Message); } } }
public sealed class ListDeliveriesWithOccurrenceUseCase(IDeliveryOccurrenceRepository r, ILogger<ListDeliveriesWithOccurrenceUseCase> l) { public async Task<Result<IReadOnlyList<DeliveryOccurrenceResponse>>> ExecuteAsync(Guid t, CancellationToken c) { try { return Result<IReadOnlyList<DeliveryOccurrenceResponse>>.Success(await r.ListAsync(t, c)); } catch (Exception ex) { l.LogError(ex, "Occurrences failed"); return Result<IReadOnlyList<DeliveryOccurrenceResponse>>.Failure(ex.Message); } } }
