using IntegraRP.Application.Abstractions.Ai;
using IntegraRP.Application.Abstractions.Mobile;
using IntegraRP.Application.Common;
using IntegraRP.Contracts.Ai;
using IntegraRP.Contracts.Mobile;
using Microsoft.Extensions.Logging;

namespace IntegraRP.Infrastructure.Services;

public sealed class InMemoryMobileFieldService : IMobileDeviceRepository, IMobileTaskRepository, IMobileEvidenceRepository, IMobileNotificationRepository, IMobileSyncRepository, IMobileDashboardService, IMobileTaskExecutionService, IMobileApprovalService, IMobileStorageService
{
    private readonly List<MobileNotificationResponse> notifications = [];
    private readonly Dictionary<Guid, string> statuses = [];
    public Task<Guid> RegisterAsync(Guid tenantId, Guid usuarioId, RegisterMobileDeviceRequest request, CancellationToken cancellationToken) => Task.FromResult(Guid.NewGuid());
    public Task<MobileDashboardResponse> GetAsync(Guid tenantId, Guid usuarioId, CancellationToken cancellationToken) => Task.FromResult(new MobileDashboardResponse(3, 1, 2, 1, 1, [new("SLA campo", "92%", "ok"), new("Pendências", "1", "alerta")]));
    public Task<IReadOnlyList<MobileTaskResponse>> ListMyTasksAsync(Guid tenantId, Guid usuarioId, string? filtro, int page, int pageSize, CancellationToken cancellationToken) => Task.FromResult<IReadOnlyList<MobileTaskResponse>>([new(Guid.Parse("10000000-0000-0000-0000-000000000001"), "Entregar pedido demo", "Entrega Field", DateTimeOffset.UtcNow.AddHours(4), "alta", "aberta", "Assumir"), new(Guid.Parse("10000000-0000-0000-0000-000000000002"), "Checklist de gôndola", "Trade", DateTimeOffset.UtcNow.AddDays(1), "media", "em_execucao", "Continuar")]);
    public Task<MobileTaskDetailResponse?> GetAsync(Guid tenantId, Guid usuarioId, Guid taskId, CancellationToken cancellationToken) => Task.FromResult<MobileTaskDetailResponse?>(new(taskId, "Entregar pedido demo", "Registrar POD com foto, GPS e assinatura.", "Entrega Field", "Cliente Demo", "PED-123", "alta", statuses.GetValueOrDefault(taskId, "aberta"), [new("observacao", "Observação", "texto", false, null)], [new("volumes", "Conferir volumes", false), new("assinatura", "Coletar assinatura", false)], ["Levar comprovante."]));
    public Task SaveStatusAsync(Guid tenantId, Guid usuarioId, Guid taskId, string status, CancellationToken cancellationToken) { statuses[taskId] = status; return Task.CompletedTask; }
    public Task<UploadMobileEvidenceResponse> AddEvidenceAsync(Guid tenantId, Guid usuarioId, Guid taskId, UploadMobileEvidenceRequest request, CancellationToken cancellationToken) => Task.FromResult(new UploadMobileEvidenceResponse(Guid.NewGuid(), $"mobile/{tenantId}/{Guid.NewGuid():N}"));
    public Task<Guid> AddSignatureAsync(Guid tenantId, Guid usuarioId, Guid taskId, CaptureMobileSignatureRequest request, CancellationToken cancellationToken) => Task.FromResult(Guid.NewGuid());
    public Task<IReadOnlyList<MobileNotificationResponse>> ListAsync(Guid tenantId, Guid usuarioId, CancellationToken cancellationToken) => Task.FromResult<IReadOnlyList<MobileNotificationResponse>>(notifications.Count == 0 ? [new(Guid.NewGuid(), "Nova tarefa", "Você possui tarefas de campo pendentes.", "pendente", DateTimeOffset.UtcNow)] : notifications);
    public Task MarkReadAsync(Guid tenantId, Guid usuarioId, Guid notificationId, CancellationToken cancellationToken) => Task.CompletedTask;
    public Task QueueAsync(Guid tenantId, Guid usuarioId, MobileSyncQueueRequest request, CancellationToken cancellationToken) => Task.CompletedTask;
    public Task<MobileSyncStatusResponse> GetStatusAsync(Guid tenantId, Guid usuarioId, CancellationToken cancellationToken) => Task.FromResult(new MobileSyncStatusResponse(0, 0, DateTimeOffset.UtcNow));
    public Task<string> SaveAsync(Guid tenantId, string? base64Content, string? contentType, CancellationToken cancellationToken) => Task.FromResult($"mobile/{tenantId}/{Guid.NewGuid():N}");
    public Task<Result<Guid>> StartAsync(Guid tenantId, Guid usuarioId, Guid taskId, StartMobileTaskExecutionRequest request, CancellationToken cancellationToken) { statuses[taskId] = "em_execucao"; return Task.FromResult(Result<Guid>.Success(Guid.NewGuid())); }
    public Task<Result<bool>> CompleteAsync(Guid tenantId, Guid usuarioId, Guid taskId, CompleteMobileTaskRequest request, CancellationToken cancellationToken) { if (statuses.GetValueOrDefault(taskId) == "concluida") return Task.FromResult(Result<bool>.Failure("Tarefa já concluída.")); statuses[taskId] = "concluida"; return Task.FromResult(Result<bool>.Success(true)); }
    public Task<Result<bool>> DecideAsync(Guid tenantId, Guid usuarioId, Guid taskId, bool approved, string comentario, CancellationToken cancellationToken) => Task.FromResult(Result<bool>.Success(true));
}

public sealed class RuleBasedIntentClassifierV2 : IAiIntentClassifierV2 { public AiIntentClassification Classify(string message) { var m = message.ToLowerInvariant(); if (m.Contains("pedido")) return new("pedido_status", "get_order_status", .9m); if (m.Contains("comprovante") || m.Contains("entrega")) return new("entrega_comprovante", "get_delivery_proof", .88m); if (m.Contains("boleto") || m.Contains("título") || m.Contains("titulo")) return new("financeiro_titulo", "get_financial_title", .86m); if (m.Contains("kpi") || m.Contains("estoque crítico")) return new("kpi_consulta", "get_authorized_kpi", .82m); if (m.Contains("módulo") || m.Contains("modulo") || m.Contains("tarefas")) return new("modulo_dinamico_consulta", "search_dynamic_module", .72m); if (m.Contains("falar") || m.Contains("chamado")) return new("abrir_tarefa_humana", "open_human_task", .8m); return new("desconhecida", null, .25m); } }
public sealed class AiPermissionValidatorV2 : IAiPermissionValidatorV2 { public bool HasPermission(IReadOnlyCollection<string> permissions, string? permission) => permission is null || permissions.Contains(permission) || permissions.Contains("ai.tool.*"); }
public sealed class AiToolRegistryV2(IEnumerable<IAiToolV2> tools) : IAiToolRegistryV2 { public IReadOnlyList<IAiToolV2> Tools { get; } = tools.ToArray(); public IAiToolV2? Find(string toolCode) => Tools.FirstOrDefault(t => t.Code == toolCode); }
public sealed class GovernedTool(string code, string desc, string perm, string response) : IAiToolV2 { public string Code => code; public string Description => desc; public string RequiredPermission => perm; public Task<AiToolExecutionResult> ExecuteAsync(AiToolExecutionContext context, CancellationToken cancellationToken) => Task.FromResult(new AiToolExecutionResult(response, "{}", .84m, response.Contains("***"))); }
public sealed class AiOrchestratorV2(IAiIntentClassifierV2 classifier, IAiPermissionValidatorV2 permissions, IAiToolRegistryV2 tools, IAiHumanEscalationServiceV2 escalation, IAiAuditServiceV2 audit, ILogger<AiOrchestratorV2> logger) : IAiOrchestratorV2 { public async Task<SendAiMessageResponse> SendAsync(Guid tenantId, Guid? userId, Guid conversationId, SendAiMessageRequest request, CancellationToken ct) { try { var intent = classifier.Classify(request.Mensagem); var tool = intent.ToolCode is null ? null : tools.Find(intent.ToolCode); if (intent.Confidence < .5m || tool is null || !permissions.HasPermission(request.Permissoes ?? [], tool.RequiredPermission)) { var esc = await escalation.OpenAsync(tenantId, userId, conversationId, "fallback_humano", request.Mensagem, ct); await audit.RegisterAsync(tenantId, userId, request.Mensagem, intent, "Fallback humano criado.", "fallback_humano", ct); return new(conversationId, Guid.NewGuid(), "Não posso responder com segurança. Abri atendimento humano.", intent.IntentCode, intent.ToolCode, intent.Confidence, true, esc); } var result = await tool.ExecuteAsync(new(tenantId, userId, request.Permissoes ?? [], request.Mensagem), ct); var answer = $"IA governada: {result.Response}"; await audit.RegisterAsync(tenantId, userId, request.Mensagem, intent, answer, "permitido", ct); return new(conversationId, Guid.NewGuid(), answer, intent.IntentCode, tool.Code, result.Confidence, false, null); } catch (Exception ex) { logger.LogError(ex, "Erro no orquestrador de IA"); throw; } } }
public sealed class AiMemoryStore : IAiConversationRepositoryV2, IAiHumanEscalationServiceV2, IAiAuditServiceV2, IAiFeedbackService { public Task<Guid> StartAsync(Guid tenantId, Guid? userId, StartAiConversationRequest request, CancellationToken cancellationToken) => Task.FromResult(Guid.NewGuid()); public Task<IReadOnlyList<AiConversationResponse>> ListAsync(Guid tenantId, Guid? userId, int page, int pageSize, CancellationToken cancellationToken) => Task.FromResult<IReadOnlyList<AiConversationResponse>>([]); public Task<Guid> OpenAsync(Guid tenantId, Guid? userId, Guid? conversationId, string reason, string? description, CancellationToken cancellationToken) => Task.FromResult(Guid.NewGuid()); public Task<Guid> RegisterAsync(Guid tenantId, Guid? userId, string question, AiIntentClassification intent, string response, string status, CancellationToken cancellationToken) => Task.FromResult(Guid.NewGuid()); public Task<AiFeedbackResponse> AddAsync(Guid tenantId, Guid? userId, AddAiUserFeedbackRequest request, CancellationToken cancellationToken) => Task.FromResult(new AiFeedbackResponse(Guid.NewGuid(), request.Nota, "registrado")); }
public sealed class AiDataMaskingServiceV2 : IAiDataMaskingServiceV2 { public string MaskFinancial(string value, bool canSeeSensitive) => canSeeSensitive ? value : "R$ ***"; public string MaskGeo(decimal? lat, decimal? lng, bool canSeePrecise) => canSeePrecise ? $"{lat},{lng}" : "coordenada mascarada"; }
public sealed class FakeAiProviderV2 : global::IntegraRP.Application.Abstractions.Ai.IAiProvider { public Task<string> CompleteAsync(string prompt, CancellationToken cancellationToken) => Task.FromResult("Provider fake governado sem IA externa."); }
