<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\IntegraRP.Domain\IntegraRP.Domain.csproj" />
    <ProjectReference Include="..\..\src\IntegraRP.Application\IntegraRP.Application.csproj" />
    <ProjectReference Include="..\..\src\IntegraRP.Contracts\IntegraRP.Contracts.csproj" />
    <ProjectReference Include="..\..\src\IntegraRP.Infrastructure\IntegraRP.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\IntegraRP.Api\IntegraRP.Api.csproj" />
    <ProjectReference Include="..\..\src\IntegraRP.Web\IntegraRP.Web.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Microsoft.Extensions.Identity.Core" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="Microsoft.Playwright" />
    <PackageReference Include="coverlet.collector" />
  </ItemGroup>
</Project>
