using IntegraRP.Application.Abstractions.FlowDesigner;
using IntegraRP.Application.Common;
using IntegraRP.Contracts.FlowDesigner;
using Microsoft.Extensions.Logging;

namespace IntegraRP.Application.FlowDesigner.UseCases;

public sealed class ListFlowTemplatesUseCase(IFlowTemplateRepository repository, ILogger<ListFlowTemplatesUseCase> logger) { public async Task<Result<IReadOnlyList<FlowTemplateResponse>>> ExecuteAsync(Guid tenantId, string? category, string? sector, int page, int pageSize, CancellationToken ct) { try { logger.LogInformation("Listing flow templates"); return await repository.ListAsync(tenantId, category, sector, page, pageSize, ct); } catch (Exception ex) { logger.LogError(ex, "Error listing flow templates"); return Result<IReadOnlyList<FlowTemplateResponse>>.Failure(ex.Message); } } }
public sealed class GetFlowTemplateByIdUseCase(IFlowTemplateRepository repository, ILogger<GetFlowTemplateByIdUseCase> logger) { public async Task<Result<FlowTemplateResponse>> ExecuteAsync(Guid tenantId, Guid templateId, CancellationToken ct) { try { return await repository.GetAsync(tenantId, templateId, ct); } catch (Exception ex) { logger.LogError(ex, "Error getting flow template"); return Result<FlowTemplateResponse>.Failure(ex.Message); } } }
public sealed class CloneFlowTemplateToProcessUseCase(IFlowTemplateCloner cloner, ILogger<CloneFlowTemplateToProcessUseCase> logger) { public async Task<Result<CloneFlowTemplateResponse>> ExecuteAsync(Guid tenantId, Guid templateId, CloneFlowTemplateRequest request, CancellationToken ct) { try { return await cloner.CloneAsync(tenantId, templateId, request, ct); } catch (Exception ex) { logger.LogError(ex, "Error cloning flow template"); return Result<CloneFlowTemplateResponse>.Failure(ex.Message); } } }
public sealed class GetFlowDesignerVersionUseCase(IFlowDesignerService service, ILogger<GetFlowDesignerVersionUseCase> logger) { public async Task<Result<FlowDesignerVersionResponse>> ExecuteAsync(Guid tenantId, Guid versionId, CancellationToken ct) { try { return await service.GetVersionAsync(tenantId, versionId, ct); } catch (Exception ex) { logger.LogError(ex, "Error getting designer version"); return Result<FlowDesignerVersionResponse>.Failure(ex.Message); } } }
public sealed class SaveFlowDesignerLayoutUseCase(IFlowDesignerService service, ILogger<SaveFlowDesignerLayoutUseCase> logger) { public async Task<Result<FlowDesignerVersionResponse>> ExecuteAsync(Guid tenantId, Guid versionId, FlowDesignerLayoutRequest request, CancellationToken ct) { try { return await service.SaveLayoutAsync(tenantId, versionId, request, ct); } catch (Exception ex) { logger.LogError(ex, "Error saving layout"); return Result<FlowDesignerVersionResponse>.Failure(ex.Message); } } }
public sealed class AddDesignerElementUseCase(IFlowDesignerService service, ILogger<AddDesignerElementUseCase> logger) { public async Task<Result<FlowDesignerElementResponse>> ExecuteAsync(Guid tenantId, Guid versionId, AddDesignerElementRequest request, CancellationToken ct) { try { return await service.AddElementAsync(tenantId, versionId, request, ct); } catch (Exception ex) { logger.LogError(ex, "Error adding element"); return Result<FlowDesignerElementResponse>.Failure(ex.Message); } } }
public sealed class UpdateDesignerElementUseCase(IFlowDesignerService service, ILogger<UpdateDesignerElementUseCase> logger) { public async Task<Result<FlowDesignerElementResponse>> ExecuteAsync(Guid tenantId, Guid versionId, Guid elementId, UpdateDesignerElementRequest request, CancellationToken ct) { try { return await service.UpdateElementAsync(tenantId, versionId, elementId, request, ct); } catch (Exception ex) { logger.LogError(ex, "Error updating element"); return Result<FlowDesignerElementResponse>.Failure(ex.Message); } } }
public sealed class RemoveDesignerElementUseCase(IFlowDesignerService service, ILogger<RemoveDesignerElementUseCase> logger) { public async Task<Result<bool>> ExecuteAsync(Guid tenantId, Guid versionId, Guid elementId, CancellationToken ct) { try { return await service.RemoveElementAsync(tenantId, versionId, elementId, ct); } catch (Exception ex) { logger.LogError(ex, "Error removing element"); return Result<bool>.Failure(ex.Message); } } }
public sealed class AddDesignerTransitionUseCase(IFlowDesignerService service, ILogger<AddDesignerTransitionUseCase> logger) { public async Task<Result<FlowDesignerTransitionResponse>> ExecuteAsync(Guid tenantId, Guid versionId, AddDesignerTransitionRequest request, CancellationToken ct) { try { return await service.AddTransitionAsync(tenantId, versionId, request, ct); } catch (Exception ex) { logger.LogError(ex, "Error adding transition"); return Result<FlowDesignerTransitionResponse>.Failure(ex.Message); } } }
public sealed class UpdateDesignerTransitionUseCase(IFlowDesignerService service, ILogger<UpdateDesignerTransitionUseCase> logger) { public async Task<Result<FlowDesignerTransitionResponse>> ExecuteAsync(Guid tenantId, Guid versionId, Guid transitionId, UpdateDesignerTransitionRequest request, CancellationToken ct) { try { return await service.UpdateTransitionAsync(tenantId, versionId, transitionId, request, ct); } catch (Exception ex) { logger.LogError(ex, "Error updating transition"); return Result<FlowDesignerTransitionResponse>.Failure(ex.Message); } } }
public sealed class RemoveDesignerTransitionUseCase(IFlowDesignerService service, ILogger<RemoveDesignerTransitionUseCase> logger) { public async Task<Result<bool>> ExecuteAsync(Guid tenantId, Guid versionId, Guid transitionId, CancellationToken ct) { try { return await service.RemoveTransitionAsync(tenantId, versionId, transitionId, ct); } catch (Exception ex) { logger.LogError(ex, "Error removing transition"); return Result<bool>.Failure(ex.Message); } } }
public sealed class SaveElementFormSchemaUseCase(IFlowDesignerService service, ILogger<SaveElementFormSchemaUseCase> logger) { public async Task<Result<FlowDesignerElementResponse>> ExecuteAsync(Guid tenantId, Guid versionId, Guid elementId, SaveElementFormSchemaRequest request, CancellationToken ct) { try { return await service.SaveFormAsync(tenantId, versionId, elementId, request, ct); } catch (Exception ex) { logger.LogError(ex, "Error saving form"); return Result<FlowDesignerElementResponse>.Failure(ex.Message); } } }
public sealed class SaveElementChecklistUseCase(IFlowDesignerService service, ILogger<SaveElementChecklistUseCase> logger) { public async Task<Result<FlowDesignerElementResponse>> ExecuteAsync(Guid tenantId, Guid versionId, Guid elementId, SaveElementChecklistRequest request, CancellationToken ct) { try { return await service.SaveChecklistAsync(tenantId, versionId, elementId, request, ct); } catch (Exception ex) { logger.LogError(ex, "Error saving checklist"); return Result<FlowDesignerElementResponse>.Failure(ex.Message); } } }
public sealed class ValidateFlowDesignerVersionUseCase(IFlowDesignerService service, ILogger<ValidateFlowDesignerVersionUseCase> logger) { public async Task<Result<ValidateFlowDesignerVersionResponse>> ExecuteAsync(Guid tenantId, Guid versionId, CancellationToken ct) { try { return await service.ValidateAsync(tenantId, versionId, ct); } catch (Exception ex) { logger.LogError(ex, "Error validating version"); return Result<ValidateFlowDesignerVersionResponse>.Failure(ex.Message); } } }
public sealed class PublishFlowFromDesignerUseCase(IFlowDesignerService service, ILogger<PublishFlowFromDesignerUseCase> logger) { public async Task<Result<PublishFlowFromDesignerResponse>> ExecuteAsync(Guid tenantId, Guid versionId, PublishFlowFromDesignerRequest request, CancellationToken ct) { try { return await service.PublishAsync(tenantId, versionId, request, ct); } catch (Exception ex) { logger.LogError(ex, "Error publishing version"); return Result<PublishFlowFromDesignerResponse>.Failure(ex.Message); } } }
public sealed class CreateDraftFromPublishedVersionUseCase(IFlowDesignerService service, ILogger<CreateDraftFromPublishedVersionUseCase> logger) { public async Task<Result<FlowDesignerVersionResponse>> ExecuteAsync(Guid tenantId, Guid definitionId, CancellationToken ct) { try { return await service.CreateDraftFromPublishedAsync(tenantId, definitionId, ct); } catch (Exception ex) { logger.LogError(ex, "Error creating draft"); return Result<FlowDesignerVersionResponse>.Failure(ex.Message); } } }
public sealed class GetDesignerHistoryUseCase(IFlowDesignerHistoryRepository repository, ILogger<GetDesignerHistoryUseCase> logger) { public async Task<Result<IReadOnlyList<FlowDesignerHistoryResponse>>> ExecuteAsync(Guid tenantId, Guid versionId, CancellationToken ct) { try { return await repository.ListAsync(tenantId, versionId, ct); } catch (Exception ex) { logger.LogError(ex, "Error getting history"); return Result<IReadOnlyList<FlowDesignerHistoryResponse>>.Failure(ex.Message); } } }
public sealed class AddFormFieldUseCase { } public sealed class UpdateFormFieldUseCase { } public sealed class RemoveFormFieldUseCase { } public sealed class ReorderFormFieldsUseCase { } public sealed class AddChecklistItemUseCase { } public sealed class UpdateChecklistItemUseCase { } public sealed class RemoveChecklistItemUseCase { } public sealed class ReorderChecklistItemsUseCase { }
