using System.Text.Json;
using IntegraRP.Application.Abstractions.FlowDesigner;
using IntegraRP.Application.Common;
using IntegraRP.Contracts.FlowDesigner;
using Microsoft.Extensions.Logging;

namespace IntegraRP.Infrastructure.Services.FlowDesigner;

public sealed class InMemoryFlowDesignerServices(ILogger<InMemoryFlowDesignerServices> logger) : IFlowDesignerService, IFlowTemplateRepository, IFlowDesignerHistoryRepository, IFlowDesignerValidator, IFlowTemplateCloner, IFlowDiagramSerializer, IFlowDesignerLayoutService, IFlowFormSchemaValidator, IFlowChecklistSchemaValidator
{
    private readonly List<FlowTemplateResponse> templates = BuildTemplates();
    private readonly List<FlowDesignerVersionResponse> versions = [];
    private readonly List<FlowDesignerHistoryResponse> history = [];

    public Task<Result<IReadOnlyList<FlowTemplateResponse>>> ListAsync(Guid tenantId, string? category, string? sector, int page, int pageSize, CancellationToken ct)
    {
        var items = templates.Where(x => (x.Publico || x.TenantId == tenantId) && (category is null || x.Categoria.Contains(category, StringComparison.OrdinalIgnoreCase)) && (sector is null || (x.SetorSugerido?.Contains(sector, StringComparison.OrdinalIgnoreCase) ?? false))).Skip((Math.Max(page, 1) - 1) * Math.Clamp(pageSize, 1, 100)).Take(Math.Clamp(pageSize, 1, 100)).ToArray();
        return Task.FromResult(Result<IReadOnlyList<FlowTemplateResponse>>.Success(items));
    }

    public Task<Result<FlowTemplateResponse>> GetAsync(Guid tenantId, Guid templateId, CancellationToken ct)
    {
        var item = templates.FirstOrDefault(x => x.Id == templateId && (x.Publico || x.TenantId == tenantId));
        return Task.FromResult(item is null ? Result<FlowTemplateResponse>.Failure("Template não encontrado.") : Result<FlowTemplateResponse>.Success(item));
    }

    public async Task<Result<CloneFlowTemplateResponse>> CloneAsync(Guid tenantId, Guid templateId, CloneFlowTemplateRequest request, CancellationToken ct)
    {
        var templateResult = await GetAsync(tenantId, templateId, ct);
        if (!templateResult.IsSuccess || templateResult.Value is null) return Result<CloneFlowTemplateResponse>.Failure(templateResult.Error ?? "Template inválido.");
        var definitionId = Guid.NewGuid();
        var versionId = Guid.NewGuid();
        var elements = templateResult.Value.Elements.Select(e => new FlowDesignerElementResponse(Guid.NewGuid(), e.Codigo, e.Nome, e.Tipo, e.Descricao, null, null, null, e.SlaMinutos, e.RegraJson, e.FormularioSchemaJson, e.ChecklistSchemaJson, e.PosicaoX ?? 80, e.PosicaoY ?? 80)).ToArray();
        var elementByCode = elements.ToDictionary(x => x.Codigo, StringComparer.OrdinalIgnoreCase);
        var transitions = templateResult.Value.Transitions.Where(t => elementByCode.ContainsKey(t.OrigemCodigo) && elementByCode.ContainsKey(t.DestinoCodigo)).Select(t => new FlowDesignerTransitionResponse(Guid.NewGuid(), elementByCode[t.OrigemCodigo].Id, elementByCode[t.DestinoCodigo].Id, t.Codigo, t.Nome, t.CondicaoTipo, t.CondicaoJson, "{}", t.Ordem)).ToArray();
        var version = new FlowDesignerVersionResponse(versionId, definitionId, request.NomeProcesso, "rascunho", BuildLayoutJson(elements), elements, transitions, null);
        versions.Add(version);
        await AddAsync(tenantId, definitionId, versionId, request.UsuarioId, "TemplateCloned", $"Template {templateResult.Value.Nome} clonado.", null, Serialize(version), ct);
        return Result<CloneFlowTemplateResponse>.Success(new CloneFlowTemplateResponse(definitionId, versionId, request.CodigoProcesso, request.NomeProcesso));
    }

    public Task<Result<FlowDesignerVersionResponse>> GetVersionAsync(Guid tenantId, Guid versionId, CancellationToken ct) => Task.FromResult(Result<FlowDesignerVersionResponse>.Success(versions.FirstOrDefault(x => x.VersionId == versionId) ?? EmptyVersion(versionId)));
    public Task<Result<FlowDesignerVersionResponse>> SaveLayoutAsync(Guid tenantId, Guid versionId, FlowDesignerLayoutRequest request, CancellationToken ct) { var version = UpsertVersion(versionId); var positions = request.Positions.ToDictionary(x => x.ElementId); var elements = version.Elements.Select(x => positions.TryGetValue(x.Id, out var p) ? x with { PosicaoX = p.PosicaoX, PosicaoY = p.PosicaoY } : x).ToArray(); return ReplaceAsync(tenantId, version with { DesignerLayoutJson = request.DesignerLayoutJson, Elements = elements }, "LayoutSaved", ct); }
    public Task<Result<FlowDesignerElementResponse>> AddElementAsync(Guid tenantId, Guid versionId, AddDesignerElementRequest request, CancellationToken ct) { var version = UpsertVersion(versionId); var item = new FlowDesignerElementResponse(Guid.NewGuid(), request.Codigo, request.Nome, request.Tipo, request.Descricao, request.SetorResponsavelId, request.UsuarioResponsavelId, request.PerfilResponsavelId, request.SlaMinutos, request.DesignerConfigJson ?? "{}", "{\"fields\":[]}", "[]", request.PosicaoX, request.PosicaoY); versions.Remove(version); versions.Add(version with { Elements = version.Elements.Concat([item]).ToArray() }); _ = AddAsync(tenantId, version.DefinitionId, versionId, null, "ElementCreated", item.Nome, null, JsonSerializer.Serialize(item), ct); return Task.FromResult(Result<FlowDesignerElementResponse>.Success(item)); }
    public Task<Result<FlowDesignerElementResponse>> UpdateElementAsync(Guid tenantId, Guid versionId, Guid elementId, UpdateDesignerElementRequest request, CancellationToken ct) { var version = UpsertVersion(versionId); var old = version.Elements.FirstOrDefault(x => x.Id == elementId); if (old is null) return Task.FromResult(Result<FlowDesignerElementResponse>.Failure("Elemento não encontrado.")); var item = old with { Codigo = request.Codigo, Nome = request.Nome, Tipo = request.Tipo, Descricao = request.Descricao, SetorResponsavelId = request.SetorResponsavelId, UsuarioResponsavelId = request.UsuarioResponsavelId, PerfilResponsavelId = request.PerfilResponsavelId, SlaMinutos = request.SlaMinutos, DesignerConfigJson = request.DesignerConfigJson ?? "{}", PosicaoX = request.PosicaoX, PosicaoY = request.PosicaoY }; ReplaceElements(version, version.Elements.Select(x => x.Id == elementId ? item : x).ToArray()); _ = AddAsync(tenantId, version.DefinitionId, versionId, null, "ElementUpdated", item.Nome, JsonSerializer.Serialize(old), JsonSerializer.Serialize(item), ct); return Task.FromResult(Result<FlowDesignerElementResponse>.Success(item)); }
    public Task<Result<bool>> RemoveElementAsync(Guid tenantId, Guid versionId, Guid elementId, CancellationToken ct) { var version = UpsertVersion(versionId); Replace(version with { Elements = version.Elements.Where(x => x.Id != elementId).ToArray(), Transitions = version.Transitions.Where(x => x.ElementoOrigemId != elementId && x.ElementoDestinoId != elementId).ToArray() }); _ = AddAsync(tenantId, version.DefinitionId, versionId, null, "ElementDeleted", elementId.ToString(), null, null, ct); return Task.FromResult(Result<bool>.Success(true)); }
    public Task<Result<FlowDesignerTransitionResponse>> AddTransitionAsync(Guid tenantId, Guid versionId, AddDesignerTransitionRequest request, CancellationToken ct) { var version = UpsertVersion(versionId); var item = new FlowDesignerTransitionResponse(Guid.NewGuid(), request.ElementoOrigemId, request.ElementoDestinoId, request.Codigo, request.Nome, request.CondicaoTipo, request.CondicaoJson ?? "{}", request.DesignerConfigJson ?? "{}", request.Ordem); Replace(version with { Transitions = version.Transitions.Concat([item]).ToArray() }); _ = AddAsync(tenantId, version.DefinitionId, versionId, null, "TransitionCreated", item.Codigo, null, JsonSerializer.Serialize(item), ct); return Task.FromResult(Result<FlowDesignerTransitionResponse>.Success(item)); }
    public Task<Result<FlowDesignerTransitionResponse>> UpdateTransitionAsync(Guid tenantId, Guid versionId, Guid transitionId, UpdateDesignerTransitionRequest request, CancellationToken ct) { var version = UpsertVersion(versionId); var old = version.Transitions.FirstOrDefault(x => x.Id == transitionId); if (old is null) return Task.FromResult(Result<FlowDesignerTransitionResponse>.Failure("Transição não encontrada.")); var item = old with { ElementoOrigemId = request.ElementoOrigemId, ElementoDestinoId = request.ElementoDestinoId, Codigo = request.Codigo, Nome = request.Nome, CondicaoTipo = request.CondicaoTipo, CondicaoJson = request.CondicaoJson ?? "{}", DesignerConfigJson = request.DesignerConfigJson ?? "{}", Ordem = request.Ordem }; Replace(version with { Transitions = version.Transitions.Select(x => x.Id == transitionId ? item : x).ToArray() }); _ = AddAsync(tenantId, version.DefinitionId, versionId, null, "TransitionUpdated", item.Codigo, JsonSerializer.Serialize(old), JsonSerializer.Serialize(item), ct); return Task.FromResult(Result<FlowDesignerTransitionResponse>.Success(item)); }
    public Task<Result<bool>> RemoveTransitionAsync(Guid tenantId, Guid versionId, Guid transitionId, CancellationToken ct) { var version = UpsertVersion(versionId); Replace(version with { Transitions = version.Transitions.Where(x => x.Id != transitionId).ToArray() }); _ = AddAsync(tenantId, version.DefinitionId, versionId, null, "TransitionDeleted", transitionId.ToString(), null, null, ct); return Task.FromResult(Result<bool>.Success(true)); }
    public Task<Result<FlowDesignerElementResponse>> SaveFormAsync(Guid tenantId, Guid versionId, Guid elementId, SaveElementFormSchemaRequest request, CancellationToken ct) => UpdateSchemaAsync(tenantId, versionId, elementId, JsonSerializer.Serialize(request.Schema), null, "FormSaved", ct);
    public Task<Result<FlowDesignerElementResponse>> SaveChecklistAsync(Guid tenantId, Guid versionId, Guid elementId, SaveElementChecklistRequest request, CancellationToken ct) => UpdateSchemaAsync(tenantId, versionId, elementId, null, JsonSerializer.Serialize(request.Schema.Items), "ChecklistSaved", ct);
    public Task<Result<ValidateFlowDesignerVersionResponse>> ValidateAsync(Guid tenantId, Guid versionId, CancellationToken ct) { var version = UpsertVersion(versionId); var result = Validate(version); Replace(version with { LastValidation = result }); _ = AddAsync(tenantId, version.DefinitionId, versionId, null, "VersionValidated", $"{result.Summary.Errors} erros", null, JsonSerializer.Serialize(result), ct); return Task.FromResult(Result<ValidateFlowDesignerVersionResponse>.Success(result)); }
    public async Task<Result<PublishFlowFromDesignerResponse>> PublishAsync(Guid tenantId, Guid versionId, PublishFlowFromDesignerRequest request, CancellationToken ct) { var validation = (await ValidateAsync(tenantId, versionId, ct)).Value!; if (!validation.CanPublish) return Result<PublishFlowFromDesignerResponse>.Failure("Existem erros críticos de validação."); if (validation.Summary.Warnings > 0 && !request.ConfirmWarnings) return Result<PublishFlowFromDesignerResponse>.Failure("Confirme a publicação com warnings."); var version = UpsertVersion(versionId) with { Status = "publicada", LastValidation = validation }; Replace(version); await AddAsync(tenantId, version.DefinitionId, versionId, request.UsuarioId, "VersionPublished", "flow.designer.version.published", null, Serialize(version), ct); return Result<PublishFlowFromDesignerResponse>.Success(new PublishFlowFromDesignerResponse(versionId, "publicada", DateTimeOffset.UtcNow, validation)); }
    public Task<Result<FlowDesignerVersionResponse>> CreateDraftFromPublishedAsync(Guid tenantId, Guid definitionId, CancellationToken ct) { var published = versions.LastOrDefault(x => x.DefinitionId == definitionId); var draft = (published ?? EmptyVersion(Guid.NewGuid())) with { VersionId = Guid.NewGuid(), DefinitionId = definitionId, Status = "rascunho" }; versions.Add(draft); return Task.FromResult(Result<FlowDesignerVersionResponse>.Success(draft)); }
    public Task<Result<IReadOnlyList<FlowDesignerHistoryResponse>>> ListAsync(Guid tenantId, Guid versionId, CancellationToken ct) => Task.FromResult(Result<IReadOnlyList<FlowDesignerHistoryResponse>>.Success(history.TakeLast(30).Reverse().ToArray()));
    public Task AddAsync(Guid tenantId, Guid definitionId, Guid versionId, Guid? userId, string action, string description, string? beforeJson, string? afterJson, CancellationToken ct) { history.Add(new FlowDesignerHistoryResponse(Guid.NewGuid(), action, description, beforeJson, afterJson, DateTimeOffset.UtcNow, Guid.NewGuid().ToString("N"))); logger.LogInformation("Designer history {Action}: {Description}", action, description); return Task.CompletedTask; }

    public ValidateFlowDesignerVersionResponse Validate(FlowDesignerVersionResponse version)
    {
        var issues = new List<FlowDesignerValidationIssueDto>();
        void Add(string severity, string code, string message, Guid? elementId = null, Guid? transitionId = null, string? path = null) => issues.Add(new FlowDesignerValidationIssueDto(severity, code, message, elementId, transitionId, path));
        if (version.Elements.Count(x => x.Tipo == "start_event") != 1) Add("error", "missing_start_event", "O fluxo precisa ter exatamente um evento de início.");
        if (!version.Elements.Any(x => x.Tipo == "end_event")) Add("error", "missing_end_event", "O fluxo precisa ter ao menos um evento de fim.");
        if (!version.Elements.Any(x => x.Tipo is "human_task" or "automatic_activity")) Add("error", "missing_task", "Inclua ao menos uma tarefa humana ou atividade automática.");
        foreach (var group in version.Elements.GroupBy(x => x.Codigo, StringComparer.OrdinalIgnoreCase).Where(x => string.IsNullOrWhiteSpace(x.Key) || x.Count() > 1)) Add("error", "duplicate_element_code", "Cada elemento precisa ter código único.");
        foreach (var transition in version.Transitions) if (!version.Elements.Any(x => x.Id == transition.ElementoOrigemId) || !version.Elements.Any(x => x.Id == transition.ElementoDestinoId)) Add("error", "invalid_transition", "Transição aponta para elemento inexistente.", null, transition.Id);
        foreach (var element in version.Elements.Where(x => x.Tipo != "start_event" && !version.Transitions.Any(t => t.ElementoDestinoId == x.Id))) Add("error", "orphan_element", $"{element.Nome} não possui entrada.", element.Id);
        foreach (var element in version.Elements.Where(x => x.Tipo != "end_event" && !version.Transitions.Any(t => t.ElementoOrigemId == x.Id))) Add("error", "orphan_element", $"{element.Nome} não possui saída.", element.Id);
        foreach (var element in version.Elements.Where(x => x.Tipo == "human_task" && x.UsuarioResponsavelId is null && x.SetorResponsavelId is null && x.PerfilResponsavelId is null)) Add("error", "human_task_without_owner", $"{element.Nome} precisa de responsável.", element.Id);
        foreach (var element in version.Elements.Where(x => x.SlaMinutos < 0)) Add("error", "invalid_sla", "SLA precisa ser maior ou igual a zero.", element.Id);
        foreach (var gateway in version.Elements.Where(x => x.Tipo == "gateway")) { var outgoing = version.Transitions.Where(x => x.ElementoOrigemId == gateway.Id).ToArray(); if (outgoing.Length < 2) Add("error", "gateway_without_outputs", "Gateway precisa ter no mínimo duas saídas.", gateway.Id); if (!outgoing.Any(x => x.CondicaoTipo is "always" or "fallback")) Add("error", "gateway_without_fallback", "Gateway precisa ter saída fallback ou always.", gateway.Id); }
        foreach (var element in version.Elements) { issues.AddRange(ValidateFormJson(element.FormularioSchemaJson, element.Id)); issues.AddRange(ValidateChecklistJson(element.ChecklistSchemaJson, element.Id)); }
        if (!issues.Any(x => x.Severity == "error")) Add("info", "ready_to_publish", "Fluxo validado e pronto para publicação.");
        return new ValidateFlowDesignerVersionResponse(new FlowDesignerValidationSummaryDto(issues.Count(x => x.Severity == "error"), issues.Count(x => x.Severity == "warning"), issues.Count(x => x.Severity == "info")), issues, !issues.Any(x => x.Severity == "error"));
    }

    public string Serialize(FlowDesignerVersionResponse version) => JsonSerializer.Serialize(version, new JsonSerializerOptions { WriteIndented = true });
    public string BuildLayout(FlowDesignerVersionResponse version) => BuildLayoutJson(version.Elements);
    public IReadOnlyList<FlowDesignerValidationIssueDto> Validate(FlowFormSchemaDto schema, Guid elementId) => ValidateForm(schema, elementId);
    public IReadOnlyList<FlowDesignerValidationIssueDto> Validate(FlowChecklistSchemaDto schema, Guid elementId) => ValidateChecklist(schema.Items, elementId);

    private Task<Result<FlowDesignerElementResponse>> UpdateSchemaAsync(Guid tenantId, Guid versionId, Guid elementId, string? formJson, string? checklistJson, string action, CancellationToken ct) { var version = UpsertVersion(versionId); var old = version.Elements.FirstOrDefault(x => x.Id == elementId); if (old is null) return Task.FromResult(Result<FlowDesignerElementResponse>.Failure("Elemento não encontrado.")); var item = old with { FormularioSchemaJson = formJson ?? old.FormularioSchemaJson, ChecklistSchemaJson = checklistJson ?? old.ChecklistSchemaJson }; ReplaceElements(version, version.Elements.Select(x => x.Id == elementId ? item : x).ToArray()); _ = AddAsync(tenantId, version.DefinitionId, versionId, null, action, item.Nome, JsonSerializer.Serialize(old), JsonSerializer.Serialize(item), ct); return Task.FromResult(Result<FlowDesignerElementResponse>.Success(item)); }
    private FlowDesignerVersionResponse UpsertVersion(Guid versionId) { var version = versions.FirstOrDefault(x => x.VersionId == versionId); if (version is not null) return version; version = EmptyVersion(versionId); versions.Add(version); return version; }
    private static FlowDesignerVersionResponse EmptyVersion(Guid versionId) => new(versionId, Guid.NewGuid(), "Novo processo", "rascunho", "{}", [], [], null);
    private void ReplaceElements(FlowDesignerVersionResponse version, IReadOnlyList<FlowDesignerElementResponse> elements) => Replace(version with { Elements = elements });
    private Task<Result<FlowDesignerVersionResponse>> ReplaceAsync(Guid tenantId, FlowDesignerVersionResponse version, string action, CancellationToken ct) { Replace(version); _ = AddAsync(tenantId, version.DefinitionId, version.VersionId, null, action, action, null, Serialize(version), ct); return Task.FromResult(Result<FlowDesignerVersionResponse>.Success(version)); }
    private void Replace(FlowDesignerVersionResponse version) { versions.RemoveAll(x => x.VersionId == version.VersionId); versions.Add(version); }
    private static string BuildLayoutJson(IEnumerable<FlowDesignerElementResponse> elements) => JsonSerializer.Serialize(new { elements = elements.Select(x => new { id = x.Id, x = x.PosicaoX, y = x.PosicaoY }) });
    private IReadOnlyList<FlowDesignerValidationIssueDto> ValidateFormJson(string json, Guid elementId) { try { var schema = JsonSerializer.Deserialize<FlowFormSchemaDto>(json, new JsonSerializerOptions { PropertyNameCaseInsensitive = true }); return schema is null ? [] : ValidateForm(schema, elementId); } catch { return [new("error", "invalid_form_json", "Formulário possui JSON inválido.", elementId, null, "form")]; } }
    private static IReadOnlyList<FlowDesignerValidationIssueDto> ValidateForm(FlowFormSchemaDto schema, Guid elementId) { var issues = new List<FlowDesignerValidationIssueDto>(); foreach (var group in schema.Fields.GroupBy(x => x.Code, StringComparer.OrdinalIgnoreCase).Where(x => string.IsNullOrWhiteSpace(x.Key) || x.Count() > 1)) issues.Add(new("error", "invalid_form_field", "Campos precisam ter código único.", elementId, null, "form.fields")); foreach (var field in schema.Fields) { if (field.Required && string.IsNullOrWhiteSpace(field.Label)) issues.Add(new("error", "required_field_without_label", "Campo obrigatório precisa ter label.", elementId, null, field.Code)); if (field.Type is "select" or "multiselect" && field.Options.Count == 0) issues.Add(new("error", "select_without_options", "Select/MultiSelect precisa ter opções.", elementId, null, field.Code)); if (field.Type == "relation" && string.IsNullOrWhiteSpace(field.Validation?.RelationTarget)) issues.Add(new("error", "relation_without_target", "Campo relation precisa ter alvo.", elementId, null, field.Code)); if (field.Type == "money" && field.Validation?.Precision is < 0 or > 6) issues.Add(new("error", "invalid_money_precision", "Campo money precisa ter precisão válida.", elementId, null, field.Code)); } return issues; }
    private IReadOnlyList<FlowDesignerValidationIssueDto> ValidateChecklistJson(string json, Guid elementId) { try { var items = JsonSerializer.Deserialize<List<FlowChecklistItemDto>>(json, new JsonSerializerOptions { PropertyNameCaseInsensitive = true }) ?? []; return ValidateChecklist(items, elementId); } catch { return [new("error", "invalid_checklist_json", "Checklist possui JSON inválido.", elementId, null, "checklist")]; } }
    private static IReadOnlyList<FlowDesignerValidationIssueDto> ValidateChecklist(IEnumerable<FlowChecklistItemDto> items, Guid elementId) => items.Where(x => string.IsNullOrWhiteSpace(x.Title)).Select(x => new FlowDesignerValidationIssueDto("error", "checklist_item_without_title", "Item de checklist precisa ter título.", elementId, null, x.Code)).ToArray();
    private static List<FlowTemplateResponse> BuildTemplates() { string[] names = ["Pedido ao Pós-venda", "Emissão de Boletos", "Lançamento de Pedidos no Sistema", "Emissão e Faturamento de Notas Fiscais", "Atualização de Produtos no Catálogo", "Planejamento Semanal de Vendas", "Visita a Clientes", "Pós-vendas", "Arrumação do Ponto de Venda", "Checagem de Estoque", "Precificação", "Recebimento de Notas Fiscais", "Separação de Pedidos", "Saída de Notas Fiscais / Expedição"]; string[] categories = ["Operação Comercial", "Financeiro", "Administrativo / Financeiro", "Financeiro / Faturamento", "Marketing", "Vendas", "Vendas", "Vendas", "Trade Marketing", "Trade Marketing / Estoque", "Trade Marketing", "Logística", "Logística", "Logística"]; return names.Select((name, i) => MakeTemplate(name, categories[i], i)).ToList(); }
    private static FlowTemplateResponse MakeTemplate(string name, string category, int index) { var id = Guid.Parse($"00000000-0000-0000-0000-{index + 1:000000000000}"); var slug = string.Concat(name.Normalize().Where(c => char.IsLetterOrDigit(c) || char.IsWhiteSpace(c))).ToLowerInvariant().Replace(' ', '_'); var elements = new List<FlowTemplateElementResponse> { new(Guid.NewGuid(), "inicio", "Início", "start_event", "Evento inicial", category, null, "{\"fields\":[]}", "[]", "{}", 80, 120, 0), new(Guid.NewGuid(), "atividade_1", name.Contains("Boletos") ? "Coletar informações do cliente e do pedido" : "Executar etapa operacional", "human_task", "Etapa humana", category, 240, "{\"fields\":[{\"code\":\"observacao\",\"label\":\"Observação\",\"type\":\"textarea\",\"required\":false,\"options\":[],\"order\":1}]}", "[{\"code\":\"confirmar\",\"title\":\"Confirmar execução\",\"required\":true,\"order\":1}]", "{}", 320, 120, 1), new(Guid.NewGuid(), "decisao", "Conferência necessária?", "gateway", "Decisão simples", category, null, "{\"fields\":[]}", "[]", "{}", 560, 120, 2), new(Guid.NewGuid(), "fim", "Fim", "end_event", "Evento final", category, null, "{\"fields\":[]}", "[]", "{}", 820, 120, 3) }; var transitions = new List<FlowTemplateTransitionResponse> { new(Guid.NewGuid(), "t_inicio_atividade", "inicio", "atividade_1", "Iniciar", "always", "{}", 1), new(Guid.NewGuid(), "t_atividade_decisao", "atividade_1", "decisao", "Conferir", "always", "{}", 2), new(Guid.NewGuid(), "t_decisao_fim", "decisao", "fim", "Finalizar", "always", "{}", 3) }; return new FlowTemplateResponse(id, null, slug, name, $"Template operacional para {name}.", category, category, "diagram", "#2563EB", true, elements, transitions); }
}
