namespace IntegraRP.Contracts.FlowDesigner;

public sealed record FlowTemplateResponse(Guid Id, Guid? TenantId, string Codigo, string Nome, string? Descricao, string Categoria, string? SetorSugerido, string? Icone, string Cor, bool Publico, IReadOnlyList<FlowTemplateElementResponse> Elements, IReadOnlyList<FlowTemplateTransitionResponse> Transitions);
public sealed record FlowTemplateElementResponse(Guid Id, string Codigo, string Nome, string Tipo, string? Descricao, string? SetorSugerido, int? SlaMinutos, string FormularioSchemaJson, string ChecklistSchemaJson, string RegraJson, decimal? PosicaoX, decimal? PosicaoY, decimal Ordem);
public sealed record FlowTemplateTransitionResponse(Guid Id, string Codigo, string OrigemCodigo, string DestinoCodigo, string? Nome, string CondicaoTipo, string CondicaoJson, decimal Ordem);
public sealed record CloneFlowTemplateRequest(string CodigoProcesso, string NomeProcesso, Guid? UsuarioId);
public sealed record CloneFlowTemplateResponse(Guid ProcessoDefinicaoId, Guid ProcessoVersaoId, string Codigo, string Nome);
public sealed record FlowDesignerVersionResponse(Guid VersionId, Guid DefinitionId, string NomeProcesso, string Status, string DesignerLayoutJson, IReadOnlyList<FlowDesignerElementResponse> Elements, IReadOnlyList<FlowDesignerTransitionResponse> Transitions, ValidateFlowDesignerVersionResponse? LastValidation);
public sealed record FlowDesignerElementResponse(Guid Id, string Codigo, string Nome, string Tipo, string? Descricao, Guid? SetorResponsavelId, Guid? UsuarioResponsavelId, Guid? PerfilResponsavelId, int? SlaMinutos, string DesignerConfigJson, string FormularioSchemaJson, string ChecklistSchemaJson, decimal PosicaoX, decimal PosicaoY);
public sealed record FlowDesignerTransitionResponse(Guid Id, Guid ElementoOrigemId, Guid ElementoDestinoId, string Codigo, string? Nome, string CondicaoTipo, string CondicaoJson, string DesignerConfigJson, decimal Ordem);
public sealed record FlowDesignerLayoutRequest(string DesignerLayoutJson, IReadOnlyList<DesignerElementPositionDto> Positions);
public sealed record DesignerElementPositionDto(Guid ElementId, decimal PosicaoX, decimal PosicaoY);
public sealed record AddDesignerElementRequest(string Codigo, string Nome, string Tipo, string? Descricao, Guid? SetorResponsavelId, Guid? UsuarioResponsavelId, Guid? PerfilResponsavelId, int? SlaMinutos, string? DesignerConfigJson, decimal PosicaoX, decimal PosicaoY);
public sealed record UpdateDesignerElementRequest(string Codigo, string Nome, string Tipo, string? Descricao, Guid? SetorResponsavelId, Guid? UsuarioResponsavelId, Guid? PerfilResponsavelId, int? SlaMinutos, string? DesignerConfigJson, decimal PosicaoX, decimal PosicaoY);
public sealed record AddDesignerTransitionRequest(Guid ElementoOrigemId, Guid ElementoDestinoId, string Codigo, string? Nome, string CondicaoTipo, string? CondicaoJson, string? DesignerConfigJson, decimal Ordem);
public sealed record UpdateDesignerTransitionRequest(Guid ElementoOrigemId, Guid ElementoDestinoId, string Codigo, string? Nome, string CondicaoTipo, string? CondicaoJson, string? DesignerConfigJson, decimal Ordem);
public sealed record SaveElementFormSchemaRequest(FlowFormSchemaDto Schema);
public sealed record SaveElementChecklistRequest(FlowChecklistSchemaDto Schema);
public sealed record PublishFlowFromDesignerRequest(Guid? UsuarioId, bool ConfirmWarnings);
public sealed record PublishFlowFromDesignerResponse(Guid VersionId, string Status, DateTimeOffset PublishedAt, ValidateFlowDesignerVersionResponse Validation);
public sealed record FlowDesignerHistoryResponse(Guid Id, string Acao, string? Descricao, string? AntesJson, string? DepoisJson, DateTimeOffset CriadoEm, string? CorrelationId);
public sealed record FlowFormSchemaDto(IReadOnlyList<FlowFormFieldDto> Fields);
public sealed record FlowFormFieldDto(string Code, string Label, string Type, bool Required, string? Placeholder, string? HelpText, IReadOnlyList<FlowFormFieldOptionDto> Options, object? DefaultValue, FlowFieldValidationDto? Validation, decimal Order, string? VisibilityRule);
public sealed record FlowFormFieldOptionDto(string Value, string Label);
public sealed record FlowFieldValidationDto(int? MinLength, int? MaxLength, decimal? Min, decimal? Max, int? Precision, string? RelationTarget);
public sealed record FlowChecklistSchemaDto(IReadOnlyList<FlowChecklistItemDto> Items);
public sealed record FlowChecklistItemDto(string Code, string Title, bool Required, decimal Order, string? HelpText);
public sealed record ValidateFlowDesignerVersionResponse(FlowDesignerValidationSummaryDto Summary, IReadOnlyList<FlowDesignerValidationIssueDto> Issues, bool CanPublish);
public sealed record FlowDesignerValidationIssueDto(string Severity, string Code, string Message, Guid? ElementId, Guid? TransitionId, string? Path);
public sealed record FlowDesignerValidationSummaryDto(int Errors, int Warnings, int Infos);
