using IntegraRP.Contracts.Flow;

namespace IntegraRP.Application.Abstractions.Flow;

public interface IProcessDefinitionRepository { Task<IReadOnlyList<ProcessDefinitionResponse>> ListAsync(Guid tenantId, int page, int pageSize, CancellationToken ct); Task<ProcessDefinitionResponse?> GetAsync(Guid tenantId, Guid id, CancellationToken ct); Task<ProcessDefinitionResponse> CreateAsync(Guid tenantId, CreateProcessDefinitionRequest request, CancellationToken ct); Task<ProcessDefinitionResponse> UpdateAsync(Guid tenantId, Guid id, UpdateProcessDefinitionRequest request, CancellationToken ct); Task ArchiveAsync(Guid tenantId, Guid id, CancellationToken ct); }
public interface IProcessVersionRepository { Task<ProcessVersionResponse> CreateDraftAsync(Guid tenantId, Guid definitionId, CancellationToken ct); Task<ProcessDiagramResponse?> GetDiagramAsync(Guid tenantId, Guid versionId, CancellationToken ct); Task<ProcessVersionResponse> PublishAsync(Guid tenantId, Guid versionId, Guid? userId, CancellationToken ct); }
public interface IProcessElementRepository { Task<ProcessElementResponse> AddAsync(Guid tenantId, Guid versionId, AddProcessElementRequest request, CancellationToken ct); Task<ProcessElementResponse> UpdateAsync(Guid tenantId, Guid versionId, Guid elementId, UpdateProcessElementRequest request, CancellationToken ct); Task RemoveAsync(Guid tenantId, Guid versionId, Guid elementId, CancellationToken ct); }
public interface IProcessTransitionRepository { Task<ProcessTransitionResponse> AddAsync(Guid tenantId, Guid versionId, AddProcessTransitionRequest request, CancellationToken ct); Task<ProcessTransitionResponse> UpdateAsync(Guid tenantId, Guid versionId, Guid transitionId, UpdateProcessTransitionRequest request, CancellationToken ct); Task RemoveAsync(Guid tenantId, Guid versionId, Guid transitionId, CancellationToken ct); }
public interface IProcessInstanceRepository { Task<IReadOnlyList<ProcessInstanceResponse>> ListAsync(Guid tenantId, string? status, int page, int pageSize, CancellationToken ct); Task<ProcessInstanceDetailResponse?> GetAsync(Guid tenantId, Guid id, CancellationToken ct); Task CancelAsync(Guid tenantId, Guid id, string reason, CancellationToken ct); }
public interface IWorkflowTaskRepository { Task<IReadOnlyList<WorkflowTaskResponse>> ListAsync(Guid tenantId, Guid? userId, Guid? departmentId, Guid? processId, int page, int pageSize, CancellationToken ct); Task<WorkflowTaskDetailResponse?> GetAsync(Guid tenantId, Guid id, CancellationToken ct); Task<WorkflowTaskResponse> AssumeAsync(Guid tenantId, Guid id, Guid userId, CancellationToken ct); Task<WorkflowTaskResponse> AssignAsync(Guid tenantId, Guid id, AssignWorkflowTaskRequest request, CancellationToken ct); Task<WorkflowTaskResponse> CancelAsync(Guid tenantId, Guid id, Guid? userId, CancellationToken ct); Task AddCommentAsync(Guid tenantId, Guid id, AddWorkflowTaskCommentRequest request, CancellationToken ct); Task AddAttachmentAsync(Guid tenantId, Guid id, AddWorkflowTaskAttachmentRequest request, CancellationToken ct); }
public interface IWorkflowAuditRepository { Task<IReadOnlyList<WorkflowAuditEventResponse>> ListByInstanceAsync(Guid tenantId, Guid instanceId, CancellationToken ct); Task AddAsync(Guid tenantId, string eventType, string description, CancellationToken ct); }
public interface IBusinessEventRepository { Task AddAsync(Guid tenantId, string eventType, string payloadJson, CancellationToken ct); }
public interface IOutboxEventRepository { Task AddAsync(Guid tenantId, string eventType, string channel, string payloadJson, CancellationToken ct); }
public interface IWorkflowEngine { Task<StartProcessInstanceResponse> StartProcessInstanceAsync(Guid tenantId, Guid definitionId, StartProcessInstanceRequest request, CancellationToken ct); Task<WorkflowTaskResponse> CompleteWorkflowTaskAsync(Guid tenantId, Guid taskId, CompleteWorkflowTaskRequest request, CancellationToken ct); Task<ProcessInstanceResponse> AdvanceProcessInstanceAsync(Guid tenantId, Guid instanceId, CancellationToken ct); }
public interface IWorkflowGatewayEvaluator { bool Evaluate(string conditionType, string conditionJson, IReadOnlyDictionary<string, object?> variables); }
public interface IWorkflowTaskFactory { WorkflowTaskResponse Create(Guid tenantId, Guid instanceId, ProcessElementResponse element); }
public interface IWorkflowEventPublisher { Task PublishAsync(Guid tenantId, string eventType, object payload, CancellationToken ct); }
public interface IWorkflowSlaCalculator { DateTimeOffset? Calculate(DateTimeOffset start, int? slaMinutes); }
public interface IWorkflowCodeGenerator { string NewProcessInstanceCode(); string NewTaskCode(); }
public interface IUnitOfWork { Task ExecuteAsync(Func<CancellationToken, Task> action, CancellationToken ct); }
