CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE SCHEMA IF NOT EXISTS integrarp;
CREATE TABLE IF NOT EXISTS integrarp.schema_migrations(version text PRIMARY KEY, checksum text NOT NULL, executado_em timestamptz NOT NULL DEFAULT now());
CREATE OR REPLACE FUNCTION integrarp.set_atualizado_em() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN NEW.atualizado_em = now(); RETURN NEW; END $$;
CREATE TABLE IF NOT EXISTS integrarp.tenant (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), nome text, codigo text, status text NOT NULL DEFAULT 'ativo', prioridade text, responsavel_usuario_id uuid, setor_id uuid, dados jsonb NOT NULL DEFAULT '{}'::jsonb, metadados jsonb NOT NULL DEFAULT '{}'::jsonb, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid, atualizado_em timestamptz, atualizado_por_usuario_id uuid, excluido_em timestamptz);
CREATE INDEX IF NOT EXISTS ix_tenant_status ON integrarp.tenant(status);
CREATE INDEX IF NOT EXISTS ix_tenant_criado_em ON integrarp.tenant(criado_em);
DROP TRIGGER IF EXISTS trg_tenant_atualizado_em ON integrarp.tenant; CREATE TRIGGER trg_tenant_atualizado_em BEFORE UPDATE ON integrarp.tenant FOR EACH ROW EXECUTE FUNCTION integrarp.set_atualizado_em();
CREATE TABLE IF NOT EXISTS integrarp.filial (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid, nome text, codigo text, status text NOT NULL DEFAULT 'ativo', prioridade text, responsavel_usuario_id uuid, setor_id uuid, dados jsonb NOT NULL DEFAULT '{}'::jsonb, metadados jsonb NOT NULL DEFAULT '{}'::jsonb, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid, atualizado_em timestamptz, atualizado_por_usuario_id uuid, excluido_em timestamptz);
CREATE INDEX IF NOT EXISTS ix_filial_tenant ON integrarp.filial(tenant_id);
CREATE INDEX IF NOT EXISTS ix_filial_status ON integrarp.filial(status);
CREATE INDEX IF NOT EXISTS ix_filial_criado_em ON integrarp.filial(criado_em);
DROP TRIGGER IF EXISTS trg_filial_atualizado_em ON integrarp.filial; CREATE TRIGGER trg_filial_atualizado_em BEFORE UPDATE ON integrarp.filial FOR EACH ROW EXECUTE FUNCTION integrarp.set_atualizado_em();
CREATE TABLE IF NOT EXISTS integrarp.usuario (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid, nome text, codigo text, status text NOT NULL DEFAULT 'ativo', prioridade text, responsavel_usuario_id uuid, setor_id uuid, dados jsonb NOT NULL DEFAULT '{}'::jsonb, metadados jsonb NOT NULL DEFAULT '{}'::jsonb, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid, atualizado_em timestamptz, atualizado_por_usuario_id uuid, excluido_em timestamptz);
CREATE INDEX IF NOT EXISTS ix_usuario_tenant ON integrarp.usuario(tenant_id);
CREATE INDEX IF NOT EXISTS ix_usuario_status ON integrarp.usuario(status);
CREATE INDEX IF NOT EXISTS ix_usuario_criado_em ON integrarp.usuario(criado_em);
DROP TRIGGER IF EXISTS trg_usuario_atualizado_em ON integrarp.usuario; CREATE TRIGGER trg_usuario_atualizado_em BEFORE UPDATE ON integrarp.usuario FOR EACH ROW EXECUTE FUNCTION integrarp.set_atualizado_em();
CREATE TABLE IF NOT EXISTS integrarp.perfil (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid, nome text, codigo text, status text NOT NULL DEFAULT 'ativo', prioridade text, responsavel_usuario_id uuid, setor_id uuid, dados jsonb NOT NULL DEFAULT '{}'::jsonb, metadados jsonb NOT NULL DEFAULT '{}'::jsonb, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid, atualizado_em timestamptz, atualizado_por_usuario_id uuid, excluido_em timestamptz);
CREATE INDEX IF NOT EXISTS ix_perfil_tenant ON integrarp.perfil(tenant_id);
CREATE INDEX IF NOT EXISTS ix_perfil_status ON integrarp.perfil(status);
CREATE INDEX IF NOT EXISTS ix_perfil_criado_em ON integrarp.perfil(criado_em);
DROP TRIGGER IF EXISTS trg_perfil_atualizado_em ON integrarp.perfil; CREATE TRIGGER trg_perfil_atualizado_em BEFORE UPDATE ON integrarp.perfil FOR EACH ROW EXECUTE FUNCTION integrarp.set_atualizado_em();
CREATE TABLE IF NOT EXISTS integrarp.permissao (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid, nome text, codigo text, status text NOT NULL DEFAULT 'ativo', prioridade text, responsavel_usuario_id uuid, setor_id uuid, dados jsonb NOT NULL DEFAULT '{}'::jsonb, metadados jsonb NOT NULL DEFAULT '{}'::jsonb, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid, atualizado_em timestamptz, atualizado_por_usuario_id uuid, excluido_em timestamptz);
CREATE INDEX IF NOT EXISTS ix_permissao_tenant ON integrarp.permissao(tenant_id);
CREATE INDEX IF NOT EXISTS ix_permissao_status ON integrarp.permissao(status);
CREATE INDEX IF NOT EXISTS ix_permissao_criado_em ON integrarp.permissao(criado_em);
DROP TRIGGER IF EXISTS trg_permissao_atualizado_em ON integrarp.permissao; CREATE TRIGGER trg_permissao_atualizado_em BEFORE UPDATE ON integrarp.permissao FOR EACH ROW EXECUTE FUNCTION integrarp.set_atualizado_em();
CREATE TABLE IF NOT EXISTS integrarp.usuario_perfil (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid, nome text, codigo text, status text NOT NULL DEFAULT 'ativo', prioridade text, responsavel_usuario_id uuid, setor_id uuid, dados jsonb NOT NULL DEFAULT '{}'::jsonb, metadados jsonb NOT NULL DEFAULT '{}'::jsonb, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid, atualizado_em timestamptz, atualizado_por_usuario_id uuid, excluido_em timestamptz);
CREATE INDEX IF NOT EXISTS ix_usuario_perfil_tenant ON integrarp.usuario_perfil(tenant_id);
CREATE INDEX IF NOT EXISTS ix_usuario_perfil_status ON integrarp.usuario_perfil(status);
CREATE INDEX IF NOT EXISTS ix_usuario_perfil_criado_em ON integrarp.usuario_perfil(criado_em);
DROP TRIGGER IF EXISTS trg_usuario_perfil_atualizado_em ON integrarp.usuario_perfil; CREATE TRIGGER trg_usuario_perfil_atualizado_em BEFORE UPDATE ON integrarp.usuario_perfil FOR EACH ROW EXECUTE FUNCTION integrarp.set_atualizado_em();
CREATE TABLE IF NOT EXISTS integrarp.auditoria_evento (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid, nome text, codigo text, status text NOT NULL DEFAULT 'ativo', prioridade text, responsavel_usuario_id uuid, setor_id uuid, dados jsonb NOT NULL DEFAULT '{}'::jsonb, metadados jsonb NOT NULL DEFAULT '{}'::jsonb, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid, atualizado_em timestamptz, atualizado_por_usuario_id uuid, excluido_em timestamptz);
CREATE INDEX IF NOT EXISTS ix_auditoria_evento_tenant ON integrarp.auditoria_evento(tenant_id);
CREATE INDEX IF NOT EXISTS ix_auditoria_evento_status ON integrarp.auditoria_evento(status);
CREATE INDEX IF NOT EXISTS ix_auditoria_evento_criado_em ON integrarp.auditoria_evento(criado_em);
DROP TRIGGER IF EXISTS trg_auditoria_evento_atualizado_em ON integrarp.auditoria_evento; CREATE TRIGGER trg_auditoria_evento_atualizado_em BEFORE UPDATE ON integrarp.auditoria_evento FOR EACH ROW EXECUTE FUNCTION integrarp.set_atualizado_em();
CREATE TABLE IF NOT EXISTS integrarp.setor (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid, nome text, codigo text, status text NOT NULL DEFAULT 'ativo', prioridade text, responsavel_usuario_id uuid, setor_id uuid, dados jsonb NOT NULL DEFAULT '{}'::jsonb, metadados jsonb NOT NULL DEFAULT '{}'::jsonb, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid, atualizado_em timestamptz, atualizado_por_usuario_id uuid, excluido_em timestamptz);
CREATE INDEX IF NOT EXISTS ix_setor_tenant ON integrarp.setor(tenant_id);
CREATE INDEX IF NOT EXISTS ix_setor_status ON integrarp.setor(status);
CREATE INDEX IF NOT EXISTS ix_setor_criado_em ON integrarp.setor(criado_em);
DROP TRIGGER IF EXISTS trg_setor_atualizado_em ON integrarp.setor; CREATE TRIGGER trg_setor_atualizado_em BEFORE UPDATE ON integrarp.setor FOR EACH ROW EXECUTE FUNCTION integrarp.set_atualizado_em();
CREATE TABLE IF NOT EXISTS integrarp.cargo (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid, nome text, codigo text, status text NOT NULL DEFAULT 'ativo', prioridade text, responsavel_usuario_id uuid, setor_id uuid, dados jsonb NOT NULL DEFAULT '{}'::jsonb, metadados jsonb NOT NULL DEFAULT '{}'::jsonb, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid, atualizado_em timestamptz, atualizado_por_usuario_id uuid, excluido_em timestamptz);
CREATE INDEX IF NOT EXISTS ix_cargo_tenant ON integrarp.cargo(tenant_id);
CREATE INDEX IF NOT EXISTS ix_cargo_status ON integrarp.cargo(status);
CREATE INDEX IF NOT EXISTS ix_cargo_criado_em ON integrarp.cargo(criado_em);
DROP TRIGGER IF EXISTS trg_cargo_atualizado_em ON integrarp.cargo; CREATE TRIGGER trg_cargo_atualizado_em BEFORE UPDATE ON integrarp.cargo FOR EACH ROW EXECUTE FUNCTION integrarp.set_atualizado_em();
CREATE TABLE IF NOT EXISTS integrarp.equipe (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid, nome text, codigo text, status text NOT NULL DEFAULT 'ativo', prioridade text, responsavel_usuario_id uuid, setor_id uuid, dados jsonb NOT NULL DEFAULT '{}'::jsonb, metadados jsonb NOT NULL DEFAULT '{}'::jsonb, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid, atualizado_em timestamptz, atualizado_por_usuario_id uuid, excluido_em timestamptz);
CREATE INDEX IF NOT EXISTS ix_equipe_tenant ON integrarp.equipe(tenant_id);
CREATE INDEX IF NOT EXISTS ix_equipe_status ON integrarp.equipe(status);
CREATE INDEX IF NOT EXISTS ix_equipe_criado_em ON integrarp.equipe(criado_em);
DROP TRIGGER IF EXISTS trg_equipe_atualizado_em ON integrarp.equipe; CREATE TRIGGER trg_equipe_atualizado_em BEFORE UPDATE ON integrarp.equipe FOR EACH ROW EXECUTE FUNCTION integrarp.set_atualizado_em();
CREATE TABLE IF NOT EXISTS integrarp.usuario_setor (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid, nome text, codigo text, status text NOT NULL DEFAULT 'ativo', prioridade text, responsavel_usuario_id uuid, setor_id uuid, dados jsonb NOT NULL DEFAULT '{}'::jsonb, metadados jsonb NOT NULL DEFAULT '{}'::jsonb, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid, atualizado_em timestamptz, atualizado_por_usuario_id uuid, excluido_em timestamptz);
CREATE INDEX IF NOT EXISTS ix_usuario_setor_tenant ON integrarp.usuario_setor(tenant_id);
CREATE INDEX IF NOT EXISTS ix_usuario_setor_status ON integrarp.usuario_setor(status);
CREATE INDEX IF NOT EXISTS ix_usuario_setor_criado_em ON integrarp.usuario_setor(criado_em);
DROP TRIGGER IF EXISTS trg_usuario_setor_atualizado_em ON integrarp.usuario_setor; CREATE TRIGGER trg_usuario_setor_atualizado_em BEFORE UPDATE ON integrarp.usuario_setor FOR EACH ROW EXECUTE FUNCTION integrarp.set_atualizado_em();
CREATE TABLE IF NOT EXISTS integrarp.processo_definicao (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid, nome text, codigo text, status text NOT NULL DEFAULT 'ativo', prioridade text, responsavel_usuario_id uuid, setor_id uuid, dados jsonb NOT NULL DEFAULT '{}'::jsonb, metadados jsonb NOT NULL DEFAULT '{}'::jsonb, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid, atualizado_em timestamptz, atualizado_por_usuario_id uuid, excluido_em timestamptz);
CREATE INDEX IF NOT EXISTS ix_processo_definicao_tenant ON integrarp.processo_definicao(tenant_id);
CREATE INDEX IF NOT EXISTS ix_processo_definicao_status ON integrarp.processo_definicao(status);
CREATE INDEX IF NOT EXISTS ix_processo_definicao_criado_em ON integrarp.processo_definicao(criado_em);
DROP TRIGGER IF EXISTS trg_processo_definicao_atualizado_em ON integrarp.processo_definicao; CREATE TRIGGER trg_processo_definicao_atualizado_em BEFORE UPDATE ON integrarp.processo_definicao FOR EACH ROW EXECUTE FUNCTION integrarp.set_atualizado_em();
CREATE TABLE IF NOT EXISTS integrarp.processo_versao (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid, nome text, codigo text, status text NOT NULL DEFAULT 'ativo', prioridade text, responsavel_usuario_id uuid, setor_id uuid, dados jsonb NOT NULL DEFAULT '{}'::jsonb, metadados jsonb NOT NULL DEFAULT '{}'::jsonb, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid, atualizado_em timestamptz, atualizado_por_usuario_id uuid, excluido_em timestamptz);
CREATE INDEX IF NOT EXISTS ix_processo_versao_tenant ON integrarp.processo_versao(tenant_id);
CREATE INDEX IF NOT EXISTS ix_processo_versao_status ON integrarp.processo_versao(status);
CREATE INDEX IF NOT EXISTS ix_processo_versao_criado_em ON integrarp.processo_versao(criado_em);
DROP TRIGGER IF EXISTS trg_processo_versao_atualizado_em ON integrarp.processo_versao; CREATE TRIGGER trg_processo_versao_atualizado_em BEFORE UPDATE ON integrarp.processo_versao FOR EACH ROW EXECUTE FUNCTION integrarp.set_atualizado_em();
CREATE TABLE IF NOT EXISTS integrarp.processo_etapa (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid, nome text, codigo text, status text NOT NULL DEFAULT 'ativo', prioridade text, responsavel_usuario_id uuid, setor_id uuid, dados jsonb NOT NULL DEFAULT '{}'::jsonb, metadados jsonb NOT NULL DEFAULT '{}'::jsonb, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid, atualizado_em timestamptz, atualizado_por_usuario_id uuid, excluido_em timestamptz);
CREATE INDEX IF NOT EXISTS ix_processo_etapa_tenant ON integrarp.processo_etapa(tenant_id);
CREATE INDEX IF NOT EXISTS ix_processo_etapa_status ON integrarp.processo_etapa(status);
CREATE INDEX IF NOT EXISTS ix_processo_etapa_criado_em ON integrarp.processo_etapa(criado_em);
DROP TRIGGER IF EXISTS trg_processo_etapa_atualizado_em ON integrarp.processo_etapa; CREATE TRIGGER trg_processo_etapa_atualizado_em BEFORE UPDATE ON integrarp.processo_etapa FOR EACH ROW EXECUTE FUNCTION integrarp.set_atualizado_em();
CREATE TABLE IF NOT EXISTS integrarp.processo_transicao (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid, nome text, codigo text, status text NOT NULL DEFAULT 'ativo', prioridade text, responsavel_usuario_id uuid, setor_id uuid, dados jsonb NOT NULL DEFAULT '{}'::jsonb, metadados jsonb NOT NULL DEFAULT '{}'::jsonb, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid, atualizado_em timestamptz, atualizado_por_usuario_id uuid, excluido_em timestamptz);
CREATE INDEX IF NOT EXISTS ix_processo_transicao_tenant ON integrarp.processo_transicao(tenant_id);
CREATE INDEX IF NOT EXISTS ix_processo_transicao_status ON integrarp.processo_transicao(status);
CREATE INDEX IF NOT EXISTS ix_processo_transicao_criado_em ON integrarp.processo_transicao(criado_em);
DROP TRIGGER IF EXISTS trg_processo_transicao_atualizado_em ON integrarp.processo_transicao; CREATE TRIGGER trg_processo_transicao_atualizado_em BEFORE UPDATE ON integrarp.processo_transicao FOR EACH ROW EXECUTE FUNCTION integrarp.set_atualizado_em();
CREATE TABLE IF NOT EXISTS integrarp.processo_instancia (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid, nome text, codigo text, status text NOT NULL DEFAULT 'ativo', prioridade text, responsavel_usuario_id uuid, setor_id uuid, dados jsonb NOT NULL DEFAULT '{}'::jsonb, metadados jsonb NOT NULL DEFAULT '{}'::jsonb, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid, atualizado_em timestamptz, atualizado_por_usuario_id uuid, excluido_em timestamptz);
CREATE INDEX IF NOT EXISTS ix_processo_instancia_tenant ON integrarp.processo_instancia(tenant_id);
CREATE INDEX IF NOT EXISTS ix_processo_instancia_status ON integrarp.processo_instancia(status);
CREATE INDEX IF NOT EXISTS ix_processo_instancia_criado_em ON integrarp.processo_instancia(criado_em);
DROP TRIGGER IF EXISTS trg_processo_instancia_atualizado_em ON integrarp.processo_instancia; CREATE TRIGGER trg_processo_instancia_atualizado_em BEFORE UPDATE ON integrarp.processo_instancia FOR EACH ROW EXECUTE FUNCTION integrarp.set_atualizado_em();
CREATE TABLE IF NOT EXISTS integrarp.tarefa (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid, nome text, codigo text, status text NOT NULL DEFAULT 'ativo', prioridade text, responsavel_usuario_id uuid, setor_id uuid, dados jsonb NOT NULL DEFAULT '{}'::jsonb, metadados jsonb NOT NULL DEFAULT '{}'::jsonb, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid, atualizado_em timestamptz, atualizado_por_usuario_id uuid, excluido_em timestamptz);
CREATE INDEX IF NOT EXISTS ix_tarefa_tenant ON integrarp.tarefa(tenant_id);
CREATE INDEX IF NOT EXISTS ix_tarefa_status ON integrarp.tarefa(status);
CREATE INDEX IF NOT EXISTS ix_tarefa_criado_em ON integrarp.tarefa(criado_em);
DROP TRIGGER IF EXISTS trg_tarefa_atualizado_em ON integrarp.tarefa; CREATE TRIGGER trg_tarefa_atualizado_em BEFORE UPDATE ON integrarp.tarefa FOR EACH ROW EXECUTE FUNCTION integrarp.set_atualizado_em();
CREATE TABLE IF NOT EXISTS integrarp.tarefa_comentario (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid, nome text, codigo text, status text NOT NULL DEFAULT 'ativo', prioridade text, responsavel_usuario_id uuid, setor_id uuid, dados jsonb NOT NULL DEFAULT '{}'::jsonb, metadados jsonb NOT NULL DEFAULT '{}'::jsonb, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid, atualizado_em timestamptz, atualizado_por_usuario_id uuid, excluido_em timestamptz);
CREATE INDEX IF NOT EXISTS ix_tarefa_comentario_tenant ON integrarp.tarefa_comentario(tenant_id);
CREATE INDEX IF NOT EXISTS ix_tarefa_comentario_status ON integrarp.tarefa_comentario(status);
CREATE INDEX IF NOT EXISTS ix_tarefa_comentario_criado_em ON integrarp.tarefa_comentario(criado_em);
DROP TRIGGER IF EXISTS trg_tarefa_comentario_atualizado_em ON integrarp.tarefa_comentario; CREATE TRIGGER trg_tarefa_comentario_atualizado_em BEFORE UPDATE ON integrarp.tarefa_comentario FOR EACH ROW EXECUTE FUNCTION integrarp.set_atualizado_em();
CREATE TABLE IF NOT EXISTS integrarp.tarefa_anexo (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid, nome text, codigo text, status text NOT NULL DEFAULT 'ativo', prioridade text, responsavel_usuario_id uuid, setor_id uuid, dados jsonb NOT NULL DEFAULT '{}'::jsonb, metadados jsonb NOT NULL DEFAULT '{}'::jsonb, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid, atualizado_em timestamptz, atualizado_por_usuario_id uuid, excluido_em timestamptz);
CREATE INDEX IF NOT EXISTS ix_tarefa_anexo_tenant ON integrarp.tarefa_anexo(tenant_id);
CREATE INDEX IF NOT EXISTS ix_tarefa_anexo_status ON integrarp.tarefa_anexo(status);
CREATE INDEX IF NOT EXISTS ix_tarefa_anexo_criado_em ON integrarp.tarefa_anexo(criado_em);
DROP TRIGGER IF EXISTS trg_tarefa_anexo_atualizado_em ON integrarp.tarefa_anexo; CREATE TRIGGER trg_tarefa_anexo_atualizado_em BEFORE UPDATE ON integrarp.tarefa_anexo FOR EACH ROW EXECUTE FUNCTION integrarp.set_atualizado_em();
CREATE TABLE IF NOT EXISTS integrarp.modulo_dinamico (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid, nome text, codigo text, status text NOT NULL DEFAULT 'ativo', prioridade text, responsavel_usuario_id uuid, setor_id uuid, dados jsonb NOT NULL DEFAULT '{}'::jsonb, metadados jsonb NOT NULL DEFAULT '{}'::jsonb, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid, atualizado_em timestamptz, atualizado_por_usuario_id uuid, excluido_em timestamptz);
CREATE INDEX IF NOT EXISTS ix_modulo_dinamico_tenant ON integrarp.modulo_dinamico(tenant_id);
CREATE INDEX IF NOT EXISTS ix_modulo_dinamico_status ON integrarp.modulo_dinamico(status);
CREATE INDEX IF NOT EXISTS ix_modulo_dinamico_criado_em ON integrarp.modulo_dinamico(criado_em);
DROP TRIGGER IF EXISTS trg_modulo_dinamico_atualizado_em ON integrarp.modulo_dinamico; CREATE TRIGGER trg_modulo_dinamico_atualizado_em BEFORE UPDATE ON integrarp.modulo_dinamico FOR EACH ROW EXECUTE FUNCTION integrarp.set_atualizado_em();
CREATE TABLE IF NOT EXISTS integrarp.modulo_entidade (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid, nome text, codigo text, status text NOT NULL DEFAULT 'ativo', prioridade text, responsavel_usuario_id uuid, setor_id uuid, dados jsonb NOT NULL DEFAULT '{}'::jsonb, metadados jsonb NOT NULL DEFAULT '{}'::jsonb, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid, atualizado_em timestamptz, atualizado_por_usuario_id uuid, excluido_em timestamptz);
CREATE INDEX IF NOT EXISTS ix_modulo_entidade_tenant ON integrarp.modulo_entidade(tenant_id);
CREATE INDEX IF NOT EXISTS ix_modulo_entidade_status ON integrarp.modulo_entidade(status);
CREATE INDEX IF NOT EXISTS ix_modulo_entidade_criado_em ON integrarp.modulo_entidade(criado_em);
DROP TRIGGER IF EXISTS trg_modulo_entidade_atualizado_em ON integrarp.modulo_entidade; CREATE TRIGGER trg_modulo_entidade_atualizado_em BEFORE UPDATE ON integrarp.modulo_entidade FOR EACH ROW EXECUTE FUNCTION integrarp.set_atualizado_em();
CREATE TABLE IF NOT EXISTS integrarp.modulo_campo (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid, nome text, codigo text, status text NOT NULL DEFAULT 'ativo', prioridade text, responsavel_usuario_id uuid, setor_id uuid, dados jsonb NOT NULL DEFAULT '{}'::jsonb, metadados jsonb NOT NULL DEFAULT '{}'::jsonb, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid, atualizado_em timestamptz, atualizado_por_usuario_id uuid, excluido_em timestamptz);
CREATE INDEX IF NOT EXISTS ix_modulo_campo_tenant ON integrarp.modulo_campo(tenant_id);
CREATE INDEX IF NOT EXISTS ix_modulo_campo_status ON integrarp.modulo_campo(status);
CREATE INDEX IF NOT EXISTS ix_modulo_campo_criado_em ON integrarp.modulo_campo(criado_em);
DROP TRIGGER IF EXISTS trg_modulo_campo_atualizado_em ON integrarp.modulo_campo; CREATE TRIGGER trg_modulo_campo_atualizado_em BEFORE UPDATE ON integrarp.modulo_campo FOR EACH ROW EXECUTE FUNCTION integrarp.set_atualizado_em();
CREATE TABLE IF NOT EXISTS integrarp.modulo_acao (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid, nome text, codigo text, status text NOT NULL DEFAULT 'ativo', prioridade text, responsavel_usuario_id uuid, setor_id uuid, dados jsonb NOT NULL DEFAULT '{}'::jsonb, metadados jsonb NOT NULL DEFAULT '{}'::jsonb, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid, atualizado_em timestamptz, atualizado_por_usuario_id uuid, excluido_em timestamptz);
CREATE INDEX IF NOT EXISTS ix_modulo_acao_tenant ON integrarp.modulo_acao(tenant_id);
CREATE INDEX IF NOT EXISTS ix_modulo_acao_status ON integrarp.modulo_acao(status);
CREATE INDEX IF NOT EXISTS ix_modulo_acao_criado_em ON integrarp.modulo_acao(criado_em);
DROP TRIGGER IF EXISTS trg_modulo_acao_atualizado_em ON integrarp.modulo_acao; CREATE TRIGGER trg_modulo_acao_atualizado_em BEFORE UPDATE ON integrarp.modulo_acao FOR EACH ROW EXECUTE FUNCTION integrarp.set_atualizado_em();
CREATE TABLE IF NOT EXISTS integrarp.modulo_registro (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid, nome text, codigo text, status text NOT NULL DEFAULT 'ativo', prioridade text, responsavel_usuario_id uuid, setor_id uuid, dados jsonb NOT NULL DEFAULT '{}'::jsonb, metadados jsonb NOT NULL DEFAULT '{}'::jsonb, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid, atualizado_em timestamptz, atualizado_por_usuario_id uuid, excluido_em timestamptz);
CREATE INDEX IF NOT EXISTS ix_modulo_registro_tenant ON integrarp.modulo_registro(tenant_id);
CREATE INDEX IF NOT EXISTS ix_modulo_registro_status ON integrarp.modulo_registro(status);
CREATE INDEX IF NOT EXISTS ix_modulo_registro_criado_em ON integrarp.modulo_registro(criado_em);
DROP TRIGGER IF EXISTS trg_modulo_registro_atualizado_em ON integrarp.modulo_registro; CREATE TRIGGER trg_modulo_registro_atualizado_em BEFORE UPDATE ON integrarp.modulo_registro FOR EACH ROW EXECUTE FUNCTION integrarp.set_atualizado_em();
CREATE TABLE IF NOT EXISTS integrarp.cliente (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid, nome text, codigo text, status text NOT NULL DEFAULT 'ativo', prioridade text, responsavel_usuario_id uuid, setor_id uuid, dados jsonb NOT NULL DEFAULT '{}'::jsonb, metadados jsonb NOT NULL DEFAULT '{}'::jsonb, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid, atualizado_em timestamptz, atualizado_por_usuario_id uuid, excluido_em timestamptz);
CREATE INDEX IF NOT EXISTS ix_cliente_tenant ON integrarp.cliente(tenant_id);
CREATE INDEX IF NOT EXISTS ix_cliente_status ON integrarp.cliente(status);
CREATE INDEX IF NOT EXISTS ix_cliente_criado_em ON integrarp.cliente(criado_em);
DROP TRIGGER IF EXISTS trg_cliente_atualizado_em ON integrarp.cliente; CREATE TRIGGER trg_cliente_atualizado_em BEFORE UPDATE ON integrarp.cliente FOR EACH ROW EXECUTE FUNCTION integrarp.set_atualizado_em();
CREATE TABLE IF NOT EXISTS integrarp.lead (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid, nome text, codigo text, status text NOT NULL DEFAULT 'ativo', prioridade text, responsavel_usuario_id uuid, setor_id uuid, dados jsonb NOT NULL DEFAULT '{}'::jsonb, metadados jsonb NOT NULL DEFAULT '{}'::jsonb, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid, atualizado_em timestamptz, atualizado_por_usuario_id uuid, excluido_em timestamptz);
CREATE INDEX IF NOT EXISTS ix_lead_tenant ON integrarp.lead(tenant_id);
CREATE INDEX IF NOT EXISTS ix_lead_status ON integrarp.lead(status);
CREATE INDEX IF NOT EXISTS ix_lead_criado_em ON integrarp.lead(criado_em);
DROP TRIGGER IF EXISTS trg_lead_atualizado_em ON integrarp.lead; CREATE TRIGGER trg_lead_atualizado_em BEFORE UPDATE ON integrarp.lead FOR EACH ROW EXECUTE FUNCTION integrarp.set_atualizado_em();
CREATE TABLE IF NOT EXISTS integrarp.pedido (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid, nome text, codigo text, status text NOT NULL DEFAULT 'ativo', prioridade text, responsavel_usuario_id uuid, setor_id uuid, dados jsonb NOT NULL DEFAULT '{}'::jsonb, metadados jsonb NOT NULL DEFAULT '{}'::jsonb, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid, atualizado_em timestamptz, atualizado_por_usuario_id uuid, excluido_em timestamptz);
CREATE INDEX IF NOT EXISTS ix_pedido_tenant ON integrarp.pedido(tenant_id);
CREATE INDEX IF NOT EXISTS ix_pedido_status ON integrarp.pedido(status);
CREATE INDEX IF NOT EXISTS ix_pedido_criado_em ON integrarp.pedido(criado_em);
DROP TRIGGER IF EXISTS trg_pedido_atualizado_em ON integrarp.pedido; CREATE TRIGGER trg_pedido_atualizado_em BEFORE UPDATE ON integrarp.pedido FOR EACH ROW EXECUTE FUNCTION integrarp.set_atualizado_em();
CREATE TABLE IF NOT EXISTS integrarp.pedido_item (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid, nome text, codigo text, status text NOT NULL DEFAULT 'ativo', prioridade text, responsavel_usuario_id uuid, setor_id uuid, dados jsonb NOT NULL DEFAULT '{}'::jsonb, metadados jsonb NOT NULL DEFAULT '{}'::jsonb, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid, atualizado_em timestamptz, atualizado_por_usuario_id uuid, excluido_em timestamptz);
CREATE INDEX IF NOT EXISTS ix_pedido_item_tenant ON integrarp.pedido_item(tenant_id);
CREATE INDEX IF NOT EXISTS ix_pedido_item_status ON integrarp.pedido_item(status);
CREATE INDEX IF NOT EXISTS ix_pedido_item_criado_em ON integrarp.pedido_item(criado_em);
DROP TRIGGER IF EXISTS trg_pedido_item_atualizado_em ON integrarp.pedido_item; CREATE TRIGGER trg_pedido_item_atualizado_em BEFORE UPDATE ON integrarp.pedido_item FOR EACH ROW EXECUTE FUNCTION integrarp.set_atualizado_em();
CREATE TABLE IF NOT EXISTS integrarp.produto (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid, nome text, codigo text, status text NOT NULL DEFAULT 'ativo', prioridade text, responsavel_usuario_id uuid, setor_id uuid, dados jsonb NOT NULL DEFAULT '{}'::jsonb, metadados jsonb NOT NULL DEFAULT '{}'::jsonb, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid, atualizado_em timestamptz, atualizado_por_usuario_id uuid, excluido_em timestamptz);
CREATE INDEX IF NOT EXISTS ix_produto_tenant ON integrarp.produto(tenant_id);
CREATE INDEX IF NOT EXISTS ix_produto_status ON integrarp.produto(status);
CREATE INDEX IF NOT EXISTS ix_produto_criado_em ON integrarp.produto(criado_em);
DROP TRIGGER IF EXISTS trg_produto_atualizado_em ON integrarp.produto; CREATE TRIGGER trg_produto_atualizado_em BEFORE UPDATE ON integrarp.produto FOR EACH ROW EXECUTE FUNCTION integrarp.set_atualizado_em();
CREATE TABLE IF NOT EXISTS integrarp.estoque_lote (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid, nome text, codigo text, status text NOT NULL DEFAULT 'ativo', prioridade text, responsavel_usuario_id uuid, setor_id uuid, dados jsonb NOT NULL DEFAULT '{}'::jsonb, metadados jsonb NOT NULL DEFAULT '{}'::jsonb, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid, atualizado_em timestamptz, atualizado_por_usuario_id uuid, excluido_em timestamptz);
CREATE INDEX IF NOT EXISTS ix_estoque_lote_tenant ON integrarp.estoque_lote(tenant_id);
CREATE INDEX IF NOT EXISTS ix_estoque_lote_status ON integrarp.estoque_lote(status);
CREATE INDEX IF NOT EXISTS ix_estoque_lote_criado_em ON integrarp.estoque_lote(criado_em);
DROP TRIGGER IF EXISTS trg_estoque_lote_atualizado_em ON integrarp.estoque_lote; CREATE TRIGGER trg_estoque_lote_atualizado_em BEFORE UPDATE ON integrarp.estoque_lote FOR EACH ROW EXECUTE FUNCTION integrarp.set_atualizado_em();
CREATE TABLE IF NOT EXISTS integrarp.estoque_movimento (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid, nome text, codigo text, status text NOT NULL DEFAULT 'ativo', prioridade text, responsavel_usuario_id uuid, setor_id uuid, dados jsonb NOT NULL DEFAULT '{}'::jsonb, metadados jsonb NOT NULL DEFAULT '{}'::jsonb, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid, atualizado_em timestamptz, atualizado_por_usuario_id uuid, excluido_em timestamptz);
CREATE INDEX IF NOT EXISTS ix_estoque_movimento_tenant ON integrarp.estoque_movimento(tenant_id);
CREATE INDEX IF NOT EXISTS ix_estoque_movimento_status ON integrarp.estoque_movimento(status);
CREATE INDEX IF NOT EXISTS ix_estoque_movimento_criado_em ON integrarp.estoque_movimento(criado_em);
DROP TRIGGER IF EXISTS trg_estoque_movimento_atualizado_em ON integrarp.estoque_movimento; CREATE TRIGGER trg_estoque_movimento_atualizado_em BEFORE UPDATE ON integrarp.estoque_movimento FOR EACH ROW EXECUTE FUNCTION integrarp.set_atualizado_em();
CREATE TABLE IF NOT EXISTS integrarp.titulo_financeiro (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid, nome text, codigo text, status text NOT NULL DEFAULT 'ativo', prioridade text, responsavel_usuario_id uuid, setor_id uuid, dados jsonb NOT NULL DEFAULT '{}'::jsonb, metadados jsonb NOT NULL DEFAULT '{}'::jsonb, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid, atualizado_em timestamptz, atualizado_por_usuario_id uuid, excluido_em timestamptz);
CREATE INDEX IF NOT EXISTS ix_titulo_financeiro_tenant ON integrarp.titulo_financeiro(tenant_id);
CREATE INDEX IF NOT EXISTS ix_titulo_financeiro_status ON integrarp.titulo_financeiro(status);
CREATE INDEX IF NOT EXISTS ix_titulo_financeiro_criado_em ON integrarp.titulo_financeiro(criado_em);
DROP TRIGGER IF EXISTS trg_titulo_financeiro_atualizado_em ON integrarp.titulo_financeiro; CREATE TRIGGER trg_titulo_financeiro_atualizado_em BEFORE UPDATE ON integrarp.titulo_financeiro FOR EACH ROW EXECUTE FUNCTION integrarp.set_atualizado_em();
CREATE TABLE IF NOT EXISTS integrarp.boleto_log (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid, nome text, codigo text, status text NOT NULL DEFAULT 'ativo', prioridade text, responsavel_usuario_id uuid, setor_id uuid, dados jsonb NOT NULL DEFAULT '{}'::jsonb, metadados jsonb NOT NULL DEFAULT '{}'::jsonb, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid, atualizado_em timestamptz, atualizado_por_usuario_id uuid, excluido_em timestamptz);
CREATE INDEX IF NOT EXISTS ix_boleto_log_tenant ON integrarp.boleto_log(tenant_id);
CREATE INDEX IF NOT EXISTS ix_boleto_log_status ON integrarp.boleto_log(status);
CREATE INDEX IF NOT EXISTS ix_boleto_log_criado_em ON integrarp.boleto_log(criado_em);
DROP TRIGGER IF EXISTS trg_boleto_log_atualizado_em ON integrarp.boleto_log; CREATE TRIGGER trg_boleto_log_atualizado_em BEFORE UPDATE ON integrarp.boleto_log FOR EACH ROW EXECUTE FUNCTION integrarp.set_atualizado_em();
CREATE TABLE IF NOT EXISTS integrarp.nota_fiscal_referencia (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid, nome text, codigo text, status text NOT NULL DEFAULT 'ativo', prioridade text, responsavel_usuario_id uuid, setor_id uuid, dados jsonb NOT NULL DEFAULT '{}'::jsonb, metadados jsonb NOT NULL DEFAULT '{}'::jsonb, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid, atualizado_em timestamptz, atualizado_por_usuario_id uuid, excluido_em timestamptz);
CREATE INDEX IF NOT EXISTS ix_nota_fiscal_referencia_tenant ON integrarp.nota_fiscal_referencia(tenant_id);
CREATE INDEX IF NOT EXISTS ix_nota_fiscal_referencia_status ON integrarp.nota_fiscal_referencia(status);
CREATE INDEX IF NOT EXISTS ix_nota_fiscal_referencia_criado_em ON integrarp.nota_fiscal_referencia(criado_em);
DROP TRIGGER IF EXISTS trg_nota_fiscal_referencia_atualizado_em ON integrarp.nota_fiscal_referencia; CREATE TRIGGER trg_nota_fiscal_referencia_atualizado_em BEFORE UPDATE ON integrarp.nota_fiscal_referencia FOR EACH ROW EXECUTE FUNCTION integrarp.set_atualizado_em();
CREATE TABLE IF NOT EXISTS integrarp.campanha_marketing (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid, nome text, codigo text, status text NOT NULL DEFAULT 'ativo', prioridade text, responsavel_usuario_id uuid, setor_id uuid, dados jsonb NOT NULL DEFAULT '{}'::jsonb, metadados jsonb NOT NULL DEFAULT '{}'::jsonb, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid, atualizado_em timestamptz, atualizado_por_usuario_id uuid, excluido_em timestamptz);
CREATE INDEX IF NOT EXISTS ix_campanha_marketing_tenant ON integrarp.campanha_marketing(tenant_id);
CREATE INDEX IF NOT EXISTS ix_campanha_marketing_status ON integrarp.campanha_marketing(status);
CREATE INDEX IF NOT EXISTS ix_campanha_marketing_criado_em ON integrarp.campanha_marketing(criado_em);
DROP TRIGGER IF EXISTS trg_campanha_marketing_atualizado_em ON integrarp.campanha_marketing; CREATE TRIGGER trg_campanha_marketing_atualizado_em BEFORE UPDATE ON integrarp.campanha_marketing FOR EACH ROW EXECUTE FUNCTION integrarp.set_atualizado_em();
CREATE TABLE IF NOT EXISTS integrarp.asset_marketing (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid, nome text, codigo text, status text NOT NULL DEFAULT 'ativo', prioridade text, responsavel_usuario_id uuid, setor_id uuid, dados jsonb NOT NULL DEFAULT '{}'::jsonb, metadados jsonb NOT NULL DEFAULT '{}'::jsonb, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid, atualizado_em timestamptz, atualizado_por_usuario_id uuid, excluido_em timestamptz);
CREATE INDEX IF NOT EXISTS ix_asset_marketing_tenant ON integrarp.asset_marketing(tenant_id);
CREATE INDEX IF NOT EXISTS ix_asset_marketing_status ON integrarp.asset_marketing(status);
CREATE INDEX IF NOT EXISTS ix_asset_marketing_criado_em ON integrarp.asset_marketing(criado_em);
DROP TRIGGER IF EXISTS trg_asset_marketing_atualizado_em ON integrarp.asset_marketing; CREATE TRIGGER trg_asset_marketing_atualizado_em BEFORE UPDATE ON integrarp.asset_marketing FOR EACH ROW EXECUTE FUNCTION integrarp.set_atualizado_em();
CREATE TABLE IF NOT EXISTS integrarp.romaneio (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid, nome text, codigo text, status text NOT NULL DEFAULT 'ativo', prioridade text, responsavel_usuario_id uuid, setor_id uuid, dados jsonb NOT NULL DEFAULT '{}'::jsonb, metadados jsonb NOT NULL DEFAULT '{}'::jsonb, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid, atualizado_em timestamptz, atualizado_por_usuario_id uuid, excluido_em timestamptz);
CREATE INDEX IF NOT EXISTS ix_romaneio_tenant ON integrarp.romaneio(tenant_id);
CREATE INDEX IF NOT EXISTS ix_romaneio_status ON integrarp.romaneio(status);
CREATE INDEX IF NOT EXISTS ix_romaneio_criado_em ON integrarp.romaneio(criado_em);
DROP TRIGGER IF EXISTS trg_romaneio_atualizado_em ON integrarp.romaneio; CREATE TRIGGER trg_romaneio_atualizado_em BEFORE UPDATE ON integrarp.romaneio FOR EACH ROW EXECUTE FUNCTION integrarp.set_atualizado_em();
CREATE TABLE IF NOT EXISTS integrarp.romaneio_item (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid, nome text, codigo text, status text NOT NULL DEFAULT 'ativo', prioridade text, responsavel_usuario_id uuid, setor_id uuid, dados jsonb NOT NULL DEFAULT '{}'::jsonb, metadados jsonb NOT NULL DEFAULT '{}'::jsonb, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid, atualizado_em timestamptz, atualizado_por_usuario_id uuid, excluido_em timestamptz);
CREATE INDEX IF NOT EXISTS ix_romaneio_item_tenant ON integrarp.romaneio_item(tenant_id);
CREATE INDEX IF NOT EXISTS ix_romaneio_item_status ON integrarp.romaneio_item(status);
CREATE INDEX IF NOT EXISTS ix_romaneio_item_criado_em ON integrarp.romaneio_item(criado_em);
DROP TRIGGER IF EXISTS trg_romaneio_item_atualizado_em ON integrarp.romaneio_item; CREATE TRIGGER trg_romaneio_item_atualizado_em BEFORE UPDATE ON integrarp.romaneio_item FOR EACH ROW EXECUTE FUNCTION integrarp.set_atualizado_em();
CREATE TABLE IF NOT EXISTS integrarp.rota_entrega (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid, nome text, codigo text, status text NOT NULL DEFAULT 'ativo', prioridade text, responsavel_usuario_id uuid, setor_id uuid, dados jsonb NOT NULL DEFAULT '{}'::jsonb, metadados jsonb NOT NULL DEFAULT '{}'::jsonb, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid, atualizado_em timestamptz, atualizado_por_usuario_id uuid, excluido_em timestamptz);
CREATE INDEX IF NOT EXISTS ix_rota_entrega_tenant ON integrarp.rota_entrega(tenant_id);
CREATE INDEX IF NOT EXISTS ix_rota_entrega_status ON integrarp.rota_entrega(status);
CREATE INDEX IF NOT EXISTS ix_rota_entrega_criado_em ON integrarp.rota_entrega(criado_em);
DROP TRIGGER IF EXISTS trg_rota_entrega_atualizado_em ON integrarp.rota_entrega; CREATE TRIGGER trg_rota_entrega_atualizado_em BEFORE UPDATE ON integrarp.rota_entrega FOR EACH ROW EXECUTE FUNCTION integrarp.set_atualizado_em();
CREATE TABLE IF NOT EXISTS integrarp.parada_entrega (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid, nome text, codigo text, status text NOT NULL DEFAULT 'ativo', prioridade text, responsavel_usuario_id uuid, setor_id uuid, dados jsonb NOT NULL DEFAULT '{}'::jsonb, metadados jsonb NOT NULL DEFAULT '{}'::jsonb, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid, atualizado_em timestamptz, atualizado_por_usuario_id uuid, excluido_em timestamptz);
CREATE INDEX IF NOT EXISTS ix_parada_entrega_tenant ON integrarp.parada_entrega(tenant_id);
CREATE INDEX IF NOT EXISTS ix_parada_entrega_status ON integrarp.parada_entrega(status);
CREATE INDEX IF NOT EXISTS ix_parada_entrega_criado_em ON integrarp.parada_entrega(criado_em);
DROP TRIGGER IF EXISTS trg_parada_entrega_atualizado_em ON integrarp.parada_entrega; CREATE TRIGGER trg_parada_entrega_atualizado_em BEFORE UPDATE ON integrarp.parada_entrega FOR EACH ROW EXECUTE FUNCTION integrarp.set_atualizado_em();
CREATE TABLE IF NOT EXISTS integrarp.prova_entrega (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid, nome text, codigo text, status text NOT NULL DEFAULT 'ativo', prioridade text, responsavel_usuario_id uuid, setor_id uuid, dados jsonb NOT NULL DEFAULT '{}'::jsonb, metadados jsonb NOT NULL DEFAULT '{}'::jsonb, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid, atualizado_em timestamptz, atualizado_por_usuario_id uuid, excluido_em timestamptz);
CREATE INDEX IF NOT EXISTS ix_prova_entrega_tenant ON integrarp.prova_entrega(tenant_id);
CREATE INDEX IF NOT EXISTS ix_prova_entrega_status ON integrarp.prova_entrega(status);
CREATE INDEX IF NOT EXISTS ix_prova_entrega_criado_em ON integrarp.prova_entrega(criado_em);
DROP TRIGGER IF EXISTS trg_prova_entrega_atualizado_em ON integrarp.prova_entrega; CREATE TRIGGER trg_prova_entrega_atualizado_em BEFORE UPDATE ON integrarp.prova_entrega FOR EACH ROW EXECUTE FUNCTION integrarp.set_atualizado_em();
CREATE TABLE IF NOT EXISTS integrarp.ocorrencia_entrega (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid, nome text, codigo text, status text NOT NULL DEFAULT 'ativo', prioridade text, responsavel_usuario_id uuid, setor_id uuid, dados jsonb NOT NULL DEFAULT '{}'::jsonb, metadados jsonb NOT NULL DEFAULT '{}'::jsonb, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid, atualizado_em timestamptz, atualizado_por_usuario_id uuid, excluido_em timestamptz);
CREATE INDEX IF NOT EXISTS ix_ocorrencia_entrega_tenant ON integrarp.ocorrencia_entrega(tenant_id);
CREATE INDEX IF NOT EXISTS ix_ocorrencia_entrega_status ON integrarp.ocorrencia_entrega(status);
CREATE INDEX IF NOT EXISTS ix_ocorrencia_entrega_criado_em ON integrarp.ocorrencia_entrega(criado_em);
DROP TRIGGER IF EXISTS trg_ocorrencia_entrega_atualizado_em ON integrarp.ocorrencia_entrega; CREATE TRIGGER trg_ocorrencia_entrega_atualizado_em BEFORE UPDATE ON integrarp.ocorrencia_entrega FOR EACH ROW EXECUTE FUNCTION integrarp.set_atualizado_em();
CREATE TABLE IF NOT EXISTS integrarp.mensagem_template (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid, nome text, codigo text, status text NOT NULL DEFAULT 'ativo', prioridade text, responsavel_usuario_id uuid, setor_id uuid, dados jsonb NOT NULL DEFAULT '{}'::jsonb, metadados jsonb NOT NULL DEFAULT '{}'::jsonb, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid, atualizado_em timestamptz, atualizado_por_usuario_id uuid, excluido_em timestamptz);
CREATE INDEX IF NOT EXISTS ix_mensagem_template_tenant ON integrarp.mensagem_template(tenant_id);
CREATE INDEX IF NOT EXISTS ix_mensagem_template_status ON integrarp.mensagem_template(status);
CREATE INDEX IF NOT EXISTS ix_mensagem_template_criado_em ON integrarp.mensagem_template(criado_em);
DROP TRIGGER IF EXISTS trg_mensagem_template_atualizado_em ON integrarp.mensagem_template; CREATE TRIGGER trg_mensagem_template_atualizado_em BEFORE UPDATE ON integrarp.mensagem_template FOR EACH ROW EXECUTE FUNCTION integrarp.set_atualizado_em();
CREATE TABLE IF NOT EXISTS integrarp.outbox_evento (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid, nome text, codigo text, status text NOT NULL DEFAULT 'ativo', prioridade text, responsavel_usuario_id uuid, setor_id uuid, dados jsonb NOT NULL DEFAULT '{}'::jsonb, metadados jsonb NOT NULL DEFAULT '{}'::jsonb, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid, atualizado_em timestamptz, atualizado_por_usuario_id uuid, excluido_em timestamptz);
CREATE INDEX IF NOT EXISTS ix_outbox_evento_tenant ON integrarp.outbox_evento(tenant_id);
CREATE INDEX IF NOT EXISTS ix_outbox_evento_status ON integrarp.outbox_evento(status);
CREATE INDEX IF NOT EXISTS ix_outbox_evento_criado_em ON integrarp.outbox_evento(criado_em);
DROP TRIGGER IF EXISTS trg_outbox_evento_atualizado_em ON integrarp.outbox_evento; CREATE TRIGGER trg_outbox_evento_atualizado_em BEFORE UPDATE ON integrarp.outbox_evento FOR EACH ROW EXECUTE FUNCTION integrarp.set_atualizado_em();
CREATE TABLE IF NOT EXISTS integrarp.canal_conversa (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid, nome text, codigo text, status text NOT NULL DEFAULT 'ativo', prioridade text, responsavel_usuario_id uuid, setor_id uuid, dados jsonb NOT NULL DEFAULT '{}'::jsonb, metadados jsonb NOT NULL DEFAULT '{}'::jsonb, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid, atualizado_em timestamptz, atualizado_por_usuario_id uuid, excluido_em timestamptz);
CREATE INDEX IF NOT EXISTS ix_canal_conversa_tenant ON integrarp.canal_conversa(tenant_id);
CREATE INDEX IF NOT EXISTS ix_canal_conversa_status ON integrarp.canal_conversa(status);
CREATE INDEX IF NOT EXISTS ix_canal_conversa_criado_em ON integrarp.canal_conversa(criado_em);
DROP TRIGGER IF EXISTS trg_canal_conversa_atualizado_em ON integrarp.canal_conversa; CREATE TRIGGER trg_canal_conversa_atualizado_em BEFORE UPDATE ON integrarp.canal_conversa FOR EACH ROW EXECUTE FUNCTION integrarp.set_atualizado_em();
CREATE TABLE IF NOT EXISTS integrarp.kpi_definicao (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid, nome text, codigo text, status text NOT NULL DEFAULT 'ativo', prioridade text, responsavel_usuario_id uuid, setor_id uuid, dados jsonb NOT NULL DEFAULT '{}'::jsonb, metadados jsonb NOT NULL DEFAULT '{}'::jsonb, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid, atualizado_em timestamptz, atualizado_por_usuario_id uuid, excluido_em timestamptz);
CREATE INDEX IF NOT EXISTS ix_kpi_definicao_tenant ON integrarp.kpi_definicao(tenant_id);
CREATE INDEX IF NOT EXISTS ix_kpi_definicao_status ON integrarp.kpi_definicao(status);
CREATE INDEX IF NOT EXISTS ix_kpi_definicao_criado_em ON integrarp.kpi_definicao(criado_em);
DROP TRIGGER IF EXISTS trg_kpi_definicao_atualizado_em ON integrarp.kpi_definicao; CREATE TRIGGER trg_kpi_definicao_atualizado_em BEFORE UPDATE ON integrarp.kpi_definicao FOR EACH ROW EXECUTE FUNCTION integrarp.set_atualizado_em();
CREATE TABLE IF NOT EXISTS integrarp.kpi_valor (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid, nome text, codigo text, status text NOT NULL DEFAULT 'ativo', prioridade text, responsavel_usuario_id uuid, setor_id uuid, dados jsonb NOT NULL DEFAULT '{}'::jsonb, metadados jsonb NOT NULL DEFAULT '{}'::jsonb, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid, atualizado_em timestamptz, atualizado_por_usuario_id uuid, excluido_em timestamptz);
CREATE INDEX IF NOT EXISTS ix_kpi_valor_tenant ON integrarp.kpi_valor(tenant_id);
CREATE INDEX IF NOT EXISTS ix_kpi_valor_status ON integrarp.kpi_valor(status);
CREATE INDEX IF NOT EXISTS ix_kpi_valor_criado_em ON integrarp.kpi_valor(criado_em);
DROP TRIGGER IF EXISTS trg_kpi_valor_atualizado_em ON integrarp.kpi_valor; CREATE TRIGGER trg_kpi_valor_atualizado_em BEFORE UPDATE ON integrarp.kpi_valor FOR EACH ROW EXECUTE FUNCTION integrarp.set_atualizado_em();
CREATE TABLE IF NOT EXISTS integrarp.ai_auditoria (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid, nome text, codigo text, status text NOT NULL DEFAULT 'ativo', prioridade text, responsavel_usuario_id uuid, setor_id uuid, dados jsonb NOT NULL DEFAULT '{}'::jsonb, metadados jsonb NOT NULL DEFAULT '{}'::jsonb, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid, atualizado_em timestamptz, atualizado_por_usuario_id uuid, excluido_em timestamptz);
CREATE INDEX IF NOT EXISTS ix_ai_auditoria_tenant ON integrarp.ai_auditoria(tenant_id);
CREATE INDEX IF NOT EXISTS ix_ai_auditoria_status ON integrarp.ai_auditoria(status);
CREATE INDEX IF NOT EXISTS ix_ai_auditoria_criado_em ON integrarp.ai_auditoria(criado_em);
DROP TRIGGER IF EXISTS trg_ai_auditoria_atualizado_em ON integrarp.ai_auditoria; CREATE TRIGGER trg_ai_auditoria_atualizado_em BEFORE UPDATE ON integrarp.ai_auditoria FOR EACH ROW EXECUTE FUNCTION integrarp.set_atualizado_em();
CREATE TABLE IF NOT EXISTS integrarp.projeto_central_board (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid, nome text, codigo text, status text NOT NULL DEFAULT 'ativo', prioridade text, responsavel_usuario_id uuid, setor_id uuid, dados jsonb NOT NULL DEFAULT '{}'::jsonb, metadados jsonb NOT NULL DEFAULT '{}'::jsonb, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid, atualizado_em timestamptz, atualizado_por_usuario_id uuid, excluido_em timestamptz);
CREATE INDEX IF NOT EXISTS ix_projeto_central_board_tenant ON integrarp.projeto_central_board(tenant_id);
CREATE INDEX IF NOT EXISTS ix_projeto_central_board_status ON integrarp.projeto_central_board(status);
CREATE INDEX IF NOT EXISTS ix_projeto_central_board_criado_em ON integrarp.projeto_central_board(criado_em);
DROP TRIGGER IF EXISTS trg_projeto_central_board_atualizado_em ON integrarp.projeto_central_board; CREATE TRIGGER trg_projeto_central_board_atualizado_em BEFORE UPDATE ON integrarp.projeto_central_board FOR EACH ROW EXECUTE FUNCTION integrarp.set_atualizado_em();
CREATE TABLE IF NOT EXISTS integrarp.projeto_central_sprint (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid, nome text, codigo text, status text NOT NULL DEFAULT 'ativo', prioridade text, responsavel_usuario_id uuid, setor_id uuid, dados jsonb NOT NULL DEFAULT '{}'::jsonb, metadados jsonb NOT NULL DEFAULT '{}'::jsonb, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid, atualizado_em timestamptz, atualizado_por_usuario_id uuid, excluido_em timestamptz);
CREATE INDEX IF NOT EXISTS ix_projeto_central_sprint_tenant ON integrarp.projeto_central_sprint(tenant_id);
CREATE INDEX IF NOT EXISTS ix_projeto_central_sprint_status ON integrarp.projeto_central_sprint(status);
CREATE INDEX IF NOT EXISTS ix_projeto_central_sprint_criado_em ON integrarp.projeto_central_sprint(criado_em);
DROP TRIGGER IF EXISTS trg_projeto_central_sprint_atualizado_em ON integrarp.projeto_central_sprint; CREATE TRIGGER trg_projeto_central_sprint_atualizado_em BEFORE UPDATE ON integrarp.projeto_central_sprint FOR EACH ROW EXECUTE FUNCTION integrarp.set_atualizado_em();
CREATE TABLE IF NOT EXISTS integrarp.projeto_central_coluna (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid, nome text, codigo text, status text NOT NULL DEFAULT 'ativo', prioridade text, responsavel_usuario_id uuid, setor_id uuid, dados jsonb NOT NULL DEFAULT '{}'::jsonb, metadados jsonb NOT NULL DEFAULT '{}'::jsonb, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid, atualizado_em timestamptz, atualizado_por_usuario_id uuid, excluido_em timestamptz);
CREATE INDEX IF NOT EXISTS ix_projeto_central_coluna_tenant ON integrarp.projeto_central_coluna(tenant_id);
CREATE INDEX IF NOT EXISTS ix_projeto_central_coluna_status ON integrarp.projeto_central_coluna(status);
CREATE INDEX IF NOT EXISTS ix_projeto_central_coluna_criado_em ON integrarp.projeto_central_coluna(criado_em);
DROP TRIGGER IF EXISTS trg_projeto_central_coluna_atualizado_em ON integrarp.projeto_central_coluna; CREATE TRIGGER trg_projeto_central_coluna_atualizado_em BEFORE UPDATE ON integrarp.projeto_central_coluna FOR EACH ROW EXECUTE FUNCTION integrarp.set_atualizado_em();
CREATE TABLE IF NOT EXISTS integrarp.projeto_central_item (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid, nome text, codigo text, status text NOT NULL DEFAULT 'ativo', prioridade text, responsavel_usuario_id uuid, setor_id uuid, dados jsonb NOT NULL DEFAULT '{}'::jsonb, metadados jsonb NOT NULL DEFAULT '{}'::jsonb, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid, atualizado_em timestamptz, atualizado_por_usuario_id uuid, excluido_em timestamptz);
CREATE INDEX IF NOT EXISTS ix_projeto_central_item_tenant ON integrarp.projeto_central_item(tenant_id);
CREATE INDEX IF NOT EXISTS ix_projeto_central_item_status ON integrarp.projeto_central_item(status);
CREATE INDEX IF NOT EXISTS ix_projeto_central_item_criado_em ON integrarp.projeto_central_item(criado_em);
DROP TRIGGER IF EXISTS trg_projeto_central_item_atualizado_em ON integrarp.projeto_central_item; CREATE TRIGGER trg_projeto_central_item_atualizado_em BEFORE UPDATE ON integrarp.projeto_central_item FOR EACH ROW EXECUTE FUNCTION integrarp.set_atualizado_em();
CREATE TABLE IF NOT EXISTS integrarp.projeto_central_item_comentario (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid, nome text, codigo text, status text NOT NULL DEFAULT 'ativo', prioridade text, responsavel_usuario_id uuid, setor_id uuid, dados jsonb NOT NULL DEFAULT '{}'::jsonb, metadados jsonb NOT NULL DEFAULT '{}'::jsonb, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid, atualizado_em timestamptz, atualizado_por_usuario_id uuid, excluido_em timestamptz);
CREATE INDEX IF NOT EXISTS ix_projeto_central_item_comentario_tenant ON integrarp.projeto_central_item_comentario(tenant_id);
CREATE INDEX IF NOT EXISTS ix_projeto_central_item_comentario_status ON integrarp.projeto_central_item_comentario(status);
CREATE INDEX IF NOT EXISTS ix_projeto_central_item_comentario_criado_em ON integrarp.projeto_central_item_comentario(criado_em);
DROP TRIGGER IF EXISTS trg_projeto_central_item_comentario_atualizado_em ON integrarp.projeto_central_item_comentario; CREATE TRIGGER trg_projeto_central_item_comentario_atualizado_em BEFORE UPDATE ON integrarp.projeto_central_item_comentario FOR EACH ROW EXECUTE FUNCTION integrarp.set_atualizado_em();
CREATE TABLE IF NOT EXISTS integrarp.projeto_central_item_anexo (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid, nome text, codigo text, status text NOT NULL DEFAULT 'ativo', prioridade text, responsavel_usuario_id uuid, setor_id uuid, dados jsonb NOT NULL DEFAULT '{}'::jsonb, metadados jsonb NOT NULL DEFAULT '{}'::jsonb, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid, atualizado_em timestamptz, atualizado_por_usuario_id uuid, excluido_em timestamptz);
CREATE INDEX IF NOT EXISTS ix_projeto_central_item_anexo_tenant ON integrarp.projeto_central_item_anexo(tenant_id);
CREATE INDEX IF NOT EXISTS ix_projeto_central_item_anexo_status ON integrarp.projeto_central_item_anexo(status);
CREATE INDEX IF NOT EXISTS ix_projeto_central_item_anexo_criado_em ON integrarp.projeto_central_item_anexo(criado_em);
DROP TRIGGER IF EXISTS trg_projeto_central_item_anexo_atualizado_em ON integrarp.projeto_central_item_anexo; CREATE TRIGGER trg_projeto_central_item_anexo_atualizado_em BEFORE UPDATE ON integrarp.projeto_central_item_anexo FOR EACH ROW EXECUTE FUNCTION integrarp.set_atualizado_em();
CREATE TABLE IF NOT EXISTS integrarp.projeto_central_evento_feed (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid, nome text, codigo text, status text NOT NULL DEFAULT 'ativo', prioridade text, responsavel_usuario_id uuid, setor_id uuid, dados jsonb NOT NULL DEFAULT '{}'::jsonb, metadados jsonb NOT NULL DEFAULT '{}'::jsonb, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid, atualizado_em timestamptz, atualizado_por_usuario_id uuid, excluido_em timestamptz);
CREATE INDEX IF NOT EXISTS ix_projeto_central_evento_feed_tenant ON integrarp.projeto_central_evento_feed(tenant_id);
CREATE INDEX IF NOT EXISTS ix_projeto_central_evento_feed_status ON integrarp.projeto_central_evento_feed(status);
CREATE INDEX IF NOT EXISTS ix_projeto_central_evento_feed_criado_em ON integrarp.projeto_central_evento_feed(criado_em);
DROP TRIGGER IF EXISTS trg_projeto_central_evento_feed_atualizado_em ON integrarp.projeto_central_evento_feed; CREATE TRIGGER trg_projeto_central_evento_feed_atualizado_em BEFORE UPDATE ON integrarp.projeto_central_evento_feed FOR EACH ROW EXECUTE FUNCTION integrarp.set_atualizado_em();

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='uq_tenant_slug') THEN ALTER TABLE integrarp.tenant ADD CONSTRAINT uq_tenant_slug UNIQUE (codigo); END IF; END $$;
CREATE INDEX IF NOT EXISTS ix_tarefa_prioridade ON integrarp.tarefa(prioridade);
CREATE INDEX IF NOT EXISTS ix_tarefa_responsavel ON integrarp.tarefa(responsavel_usuario_id);
CREATE INDEX IF NOT EXISTS ix_tarefa_busca ON integrarp.tarefa USING gin(to_tsvector('portuguese', coalesce(nome,'')));
CREATE OR REPLACE VIEW integrarp.vw_dashboard_operacional AS SELECT 0::int AS tarefas_abertas, 0::int AS processos_em_atraso, 0::int AS estoque_critico;
CREATE OR REPLACE VIEW integrarp.vw_tarefas_abertas AS SELECT * FROM integrarp.tarefa WHERE excluido_em IS NULL AND status <> 'concluida';
CREATE OR REPLACE VIEW integrarp.vw_processos_em_atraso AS SELECT * FROM integrarp.processo_instancia WHERE excluido_em IS NULL AND status = 'atrasado';
CREATE OR REPLACE VIEW integrarp.vw_estoque_critico AS SELECT * FROM integrarp.produto WHERE excluido_em IS NULL AND (dados->>'estoque_critico') = 'true';
CREATE OR REPLACE VIEW integrarp.vw_projeto_central_resumo AS SELECT b.id, b.nome, count(i.id) AS total_itens FROM integrarp.projeto_central_board b LEFT JOIN integrarp.projeto_central_item i ON i.tenant_id=b.tenant_id GROUP BY b.id,b.nome;
INSERT INTO integrarp.tenant(nome,codigo,status) VALUES ('Valora Group & MNSoft','valora-mnsoft','ativo') ON CONFLICT DO NOTHING;
