CREATE SCHEMA IF NOT EXISTS integrarp;
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TABLE IF NOT EXISTS integrarp.kpi_definicao (kpi_definicao_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NULL, codigo varchar(120) NOT NULL, nome varchar(180) NOT NULL, descricao text NULL, modulo varchar(80) NOT NULL, categoria varchar(80) NULL, unidade varchar(40) NULL, formula_texto text NULL, query_referencia text NULL, direcao_melhor varchar(20) NOT NULL DEFAULT 'maior', frequencia_calculo varchar(40) NOT NULL DEFAULT 'diaria', ativo boolean NOT NULL DEFAULT true, publico boolean NOT NULL DEFAULT false, criado_em timestamptz NOT NULL DEFAULT now(), atualizado_em timestamptz NULL, excluido_em timestamptz NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb);
CREATE TABLE IF NOT EXISTS integrarp.kpi_valor (kpi_valor_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, kpi_definicao_id uuid NOT NULL, referencia_tipo varchar(80) NULL, referencia_id uuid NULL, periodo_inicio timestamptz NOT NULL, periodo_fim timestamptz NOT NULL, valor_numero numeric(18,4) NULL, valor_texto text NULL, status varchar(40) NOT NULL DEFAULT 'neutro', calculado_em timestamptz NOT NULL DEFAULT now(), fonte varchar(120) NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb);
CREATE TABLE IF NOT EXISTS integrarp.kpi_meta (kpi_meta_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, kpi_definicao_id uuid NOT NULL, referencia_tipo varchar(80) NULL, referencia_id uuid NULL, valor_meta numeric(18,4) NULL, faixa_positiva_min numeric(18,4) NULL, faixa_positiva_max numeric(18,4) NULL, faixa_neutra_min numeric(18,4) NULL, faixa_neutra_max numeric(18,4) NULL, faixa_negativa_min numeric(18,4) NULL, faixa_negativa_max numeric(18,4) NULL, inicio_vigencia date NOT NULL DEFAULT current_date, fim_vigencia date NULL, ativo boolean NOT NULL DEFAULT true, criado_em timestamptz NOT NULL DEFAULT now(), atualizado_em timestamptz NULL, excluido_em timestamptz NULL);
CREATE TABLE IF NOT EXISTS integrarp.score_operacional (score_operacional_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, referencia_tipo varchar(80) NOT NULL, referencia_id uuid NULL, score numeric(10,2) NOT NULL DEFAULT 0, status varchar(40) NOT NULL DEFAULT 'neutro', componentes_json jsonb NOT NULL DEFAULT '{}'::jsonb, periodo_inicio timestamptz NOT NULL, periodo_fim timestamptz NOT NULL, calculado_em timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS integrarp.kpi_alerta (kpi_alerta_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NULL, nome varchar(180) NULL, status varchar(40) NOT NULL DEFAULT 'ativo', criado_em timestamptz NOT NULL DEFAULT now(), atualizado_em timestamptz NULL, excluido_em timestamptz NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb);
CREATE TABLE IF NOT EXISTS integrarp.kpi_snapshot (kpi_snapshot_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NULL, nome varchar(180) NULL, status varchar(40) NOT NULL DEFAULT 'ativo', criado_em timestamptz NOT NULL DEFAULT now(), atualizado_em timestamptz NULL, excluido_em timestamptz NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb);
CREATE TABLE IF NOT EXISTS integrarp.score_operacional (score_operacional_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NULL, nome varchar(180) NULL, status varchar(40) NOT NULL DEFAULT 'ativo', criado_em timestamptz NOT NULL DEFAULT now(), atualizado_em timestamptz NULL, excluido_em timestamptz NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb);
CREATE TABLE IF NOT EXISTS integrarp.dashboard_configuracao (dashboard_configuracao_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NULL, nome varchar(180) NULL, status varchar(40) NOT NULL DEFAULT 'ativo', criado_em timestamptz NOT NULL DEFAULT now(), atualizado_em timestamptz NULL, excluido_em timestamptz NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb);
CREATE TABLE IF NOT EXISTS integrarp.dashboard_widget (dashboard_widget_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NULL, nome varchar(180) NULL, status varchar(40) NOT NULL DEFAULT 'ativo', criado_em timestamptz NOT NULL DEFAULT now(), atualizado_em timestamptz NULL, excluido_em timestamptz NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb);
CREATE TABLE IF NOT EXISTS integrarp.relatorio_salvo (relatorio_salvo_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NULL, nome varchar(180) NULL, status varchar(40) NOT NULL DEFAULT 'ativo', criado_em timestamptz NOT NULL DEFAULT now(), atualizado_em timestamptz NULL, excluido_em timestamptz NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb);
CREATE TABLE IF NOT EXISTS integrarp.analytics_evento (analytics_evento_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NULL, nome varchar(180) NULL, status varchar(40) NOT NULL DEFAULT 'ativo', criado_em timestamptz NOT NULL DEFAULT now(), atualizado_em timestamptz NULL, excluido_em timestamptz NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb);
CREATE TABLE IF NOT EXISTS integrarp.analytics_agregacao_log (analytics_agregacao_log_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NULL, nome varchar(180) NULL, status varchar(40) NOT NULL DEFAULT 'ativo', criado_em timestamptz NOT NULL DEFAULT now(), atualizado_em timestamptz NULL, excluido_em timestamptz NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb);
CREATE TABLE IF NOT EXISTS integrarp.projeto_central_board (board_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, nome varchar(160) NOT NULL, descricao text NULL, cor_principal varchar(20) NOT NULL DEFAULT '#2563EB', status varchar(40) NOT NULL DEFAULT 'ativo', criado_por_usuario_id uuid NULL, criado_em timestamptz NOT NULL DEFAULT now(), atualizado_em timestamptz NULL, excluido_em timestamptz NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb);
CREATE TABLE IF NOT EXISTS integrarp.projeto_central_sprint (sprint_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, board_id uuid NOT NULL, codigo varchar(20) NOT NULL, nome varchar(160) NOT NULL, objetivo text NULL, data_inicio date NOT NULL, data_fim date NOT NULL, status varchar(30) NOT NULL DEFAULT 'planejada', meta_pontos integer NOT NULL DEFAULT 0, criado_em timestamptz NOT NULL DEFAULT now(), atualizado_em timestamptz NULL, excluido_em timestamptz NULL);
CREATE TABLE IF NOT EXISTS integrarp.projeto_central_coluna (coluna_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, board_id uuid NOT NULL, nome varchar(120) NOT NULL, descricao text NULL, cor varchar(20) NOT NULL DEFAULT '#2563EB', ordem numeric(12,4) NOT NULL DEFAULT 0, limite_wip integer NULL, eh_conclusiva boolean NOT NULL DEFAULT false, criado_em timestamptz NOT NULL DEFAULT now(), atualizado_em timestamptz NULL, excluido_em timestamptz NULL);
CREATE TABLE IF NOT EXISTS integrarp.projeto_central_item (item_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, board_id uuid NOT NULL, coluna_id uuid NOT NULL, sprint_id uuid NULL, codigo varchar(40) NOT NULL, titulo varchar(220) NOT NULL, descricao text NULL, tipo varchar(40) NOT NULL DEFAULT 'tarefa', modulo varchar(80) NULL, prioridade varchar(20) NOT NULL DEFAULT 'media', story_points integer NOT NULL DEFAULT 0, cor varchar(20) NOT NULL DEFAULT '#2563EB', responsavel_nome varchar(120) NULL, responsavel_usuario_id uuid NULL, data_limite date NULL, ordem numeric(12,4) NOT NULL DEFAULT 0, etiquetas_json jsonb NOT NULL DEFAULT '[]'::jsonb, campos_extras_json jsonb NOT NULL DEFAULT '{}'::jsonb, criado_por_usuario_id uuid NULL, criado_em timestamptz NOT NULL DEFAULT now(), atualizado_em timestamptz NULL, concluido_em timestamptz NULL, excluido_em timestamptz NULL);
CREATE TABLE IF NOT EXISTS integrarp.projeto_central_item_comentario (projeto_central_item_comentario_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, board_id uuid NULL, item_id uuid NULL, tipo varchar(80) NULL, conteudo text NULL, criado_em timestamptz NOT NULL DEFAULT now(), metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb);
CREATE TABLE IF NOT EXISTS integrarp.projeto_central_item_anexo (projeto_central_item_anexo_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, board_id uuid NULL, item_id uuid NULL, tipo varchar(80) NULL, conteudo text NULL, criado_em timestamptz NOT NULL DEFAULT now(), metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb);
CREATE TABLE IF NOT EXISTS integrarp.projeto_central_evento_feed (projeto_central_evento_feed_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, board_id uuid NULL, item_id uuid NULL, tipo varchar(80) NULL, conteudo text NULL, criado_em timestamptz NOT NULL DEFAULT now(), metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb);
CREATE TABLE IF NOT EXISTS integrarp.projeto_central_importacao (projeto_central_importacao_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, board_id uuid NULL, item_id uuid NULL, tipo varchar(80) NULL, conteudo text NULL, criado_em timestamptz NOT NULL DEFAULT now(), metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb);
CREATE TABLE IF NOT EXISTS integrarp.projeto_central_exportacao (projeto_central_exportacao_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, board_id uuid NULL, item_id uuid NULL, tipo varchar(80) NULL, conteudo text NULL, criado_em timestamptz NOT NULL DEFAULT now(), metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb);
CREATE INDEX IF NOT EXISTS ix_kpi_definicao_tenant ON integrarp.kpi_definicao (tenant_id);
CREATE INDEX IF NOT EXISTS ix_kpi_valor_tenant ON integrarp.kpi_valor (tenant_id);
CREATE INDEX IF NOT EXISTS ix_kpi_meta_tenant ON integrarp.kpi_meta (tenant_id);
CREATE INDEX IF NOT EXISTS ix_kpi_alerta_tenant ON integrarp.kpi_alerta (tenant_id);
CREATE INDEX IF NOT EXISTS ix_kpi_snapshot_tenant ON integrarp.kpi_snapshot (tenant_id);
CREATE INDEX IF NOT EXISTS ix_score_operacional_tenant ON integrarp.score_operacional (tenant_id);
CREATE INDEX IF NOT EXISTS ix_dashboard_configuracao_tenant ON integrarp.dashboard_configuracao (tenant_id);
CREATE INDEX IF NOT EXISTS ix_dashboard_widget_tenant ON integrarp.dashboard_widget (tenant_id);
CREATE INDEX IF NOT EXISTS ix_relatorio_salvo_tenant ON integrarp.relatorio_salvo (tenant_id);
CREATE INDEX IF NOT EXISTS ix_analytics_evento_tenant ON integrarp.analytics_evento (tenant_id);
CREATE INDEX IF NOT EXISTS ix_analytics_agregacao_log_tenant ON integrarp.analytics_agregacao_log (tenant_id);
CREATE INDEX IF NOT EXISTS ix_projeto_central_board_tenant ON integrarp.projeto_central_board (tenant_id);
CREATE INDEX IF NOT EXISTS ix_projeto_central_sprint_tenant ON integrarp.projeto_central_sprint (tenant_id);
CREATE INDEX IF NOT EXISTS ix_projeto_central_coluna_tenant ON integrarp.projeto_central_coluna (tenant_id);
CREATE INDEX IF NOT EXISTS ix_projeto_central_item_tenant ON integrarp.projeto_central_item (tenant_id);
CREATE INDEX IF NOT EXISTS ix_projeto_central_item_comentario_tenant ON integrarp.projeto_central_item_comentario (tenant_id);
CREATE INDEX IF NOT EXISTS ix_projeto_central_item_anexo_tenant ON integrarp.projeto_central_item_anexo (tenant_id);
CREATE INDEX IF NOT EXISTS ix_projeto_central_evento_feed_tenant ON integrarp.projeto_central_evento_feed (tenant_id);
CREATE INDEX IF NOT EXISTS ix_projeto_central_importacao_tenant ON integrarp.projeto_central_importacao (tenant_id);
CREATE INDEX IF NOT EXISTS ix_projeto_central_exportacao_tenant ON integrarp.projeto_central_exportacao (tenant_id);
CREATE OR REPLACE FUNCTION integrarp.fn_sprint7_touch_updated_at() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN NEW.atualizado_em = now(); RETURN NEW; END; $$;
DROP TRIGGER IF EXISTS trg_kpi_definicao_updated_at ON integrarp.kpi_definicao;
CREATE TRIGGER trg_kpi_definicao_updated_at BEFORE UPDATE ON integrarp.kpi_definicao FOR EACH ROW EXECUTE FUNCTION integrarp.fn_sprint7_touch_updated_at();
DROP TRIGGER IF EXISTS trg_projeto_central_board_updated_at ON integrarp.projeto_central_board;
CREATE TRIGGER trg_projeto_central_board_updated_at BEFORE UPDATE ON integrarp.projeto_central_board FOR EACH ROW EXECUTE FUNCTION integrarp.fn_sprint7_touch_updated_at();
DROP TRIGGER IF EXISTS trg_projeto_central_item_updated_at ON integrarp.projeto_central_item;
CREATE TRIGGER trg_projeto_central_item_updated_at BEFORE UPDATE ON integrarp.projeto_central_item FOR EACH ROW EXECUTE FUNCTION integrarp.fn_sprint7_touch_updated_at();
CREATE OR REPLACE VIEW integrarp.vw_bi_dashboard_executivo AS SELECT gen_random_uuid() AS id, NULL::uuid AS tenant_id, 'vw_bi_dashboard_executivo'::text AS indicador, 0::numeric AS valor, now() AS atualizado_em;
CREATE OR REPLACE VIEW integrarp.vw_bi_score_operacional AS SELECT gen_random_uuid() AS id, NULL::uuid AS tenant_id, 'vw_bi_score_operacional'::text AS indicador, 0::numeric AS valor, now() AS atualizado_em;
CREATE OR REPLACE VIEW integrarp.vw_bi_kpis_atuais AS SELECT gen_random_uuid() AS id, NULL::uuid AS tenant_id, 'vw_bi_kpis_atuais'::text AS indicador, 0::numeric AS valor, now() AS atualizado_em;
CREATE OR REPLACE VIEW integrarp.vw_bi_alertas_kpi AS SELECT gen_random_uuid() AS id, NULL::uuid AS tenant_id, 'vw_bi_alertas_kpi'::text AS indicador, 0::numeric AS valor, now() AS atualizado_em;
CREATE OR REPLACE VIEW integrarp.vw_bi_gargalos_operacionais AS SELECT gen_random_uuid() AS id, NULL::uuid AS tenant_id, 'vw_bi_gargalos_operacionais'::text AS indicador, 0::numeric AS valor, now() AS atualizado_em;
CREATE OR REPLACE VIEW integrarp.vw_bi_flow_resumo AS SELECT gen_random_uuid() AS id, NULL::uuid AS tenant_id, 'vw_bi_flow_resumo'::text AS indicador, 0::numeric AS valor, now() AS atualizado_em;
CREATE OR REPLACE VIEW integrarp.vw_bi_tarefas_atrasadas AS SELECT gen_random_uuid() AS id, NULL::uuid AS tenant_id, 'vw_bi_tarefas_atrasadas'::text AS indicador, 0::numeric AS valor, now() AS atualizado_em;
CREATE OR REPLACE VIEW integrarp.vw_bi_processos_atrasados AS SELECT gen_random_uuid() AS id, NULL::uuid AS tenant_id, 'vw_bi_processos_atrasados'::text AS indicador, 0::numeric AS valor, now() AS atualizado_em;
CREATE OR REPLACE VIEW integrarp.vw_bi_sla_por_setor AS SELECT gen_random_uuid() AS id, NULL::uuid AS tenant_id, 'vw_bi_sla_por_setor'::text AS indicador, 0::numeric AS valor, now() AS atualizado_em;
CREATE OR REPLACE VIEW integrarp.vw_bi_comercial_resumo AS SELECT gen_random_uuid() AS id, NULL::uuid AS tenant_id, 'vw_bi_comercial_resumo'::text AS indicador, 0::numeric AS valor, now() AS atualizado_em;
CREATE OR REPLACE VIEW integrarp.vw_bi_pedidos_por_status AS SELECT gen_random_uuid() AS id, NULL::uuid AS tenant_id, 'vw_bi_pedidos_por_status'::text AS indicador, 0::numeric AS valor, now() AS atualizado_em;
CREATE OR REPLACE VIEW integrarp.vw_bi_pedidos_em_fluxo AS SELECT gen_random_uuid() AS id, NULL::uuid AS tenant_id, 'vw_bi_pedidos_em_fluxo'::text AS indicador, 0::numeric AS valor, now() AS atualizado_em;
CREATE OR REPLACE VIEW integrarp.vw_bi_ticket_medio AS SELECT gen_random_uuid() AS id, NULL::uuid AS tenant_id, 'vw_bi_ticket_medio'::text AS indicador, 0::numeric AS valor, now() AS atualizado_em;
CREATE OR REPLACE VIEW integrarp.vw_bi_estoque_resumo AS SELECT gen_random_uuid() AS id, NULL::uuid AS tenant_id, 'vw_bi_estoque_resumo'::text AS indicador, 0::numeric AS valor, now() AS atualizado_em;
CREATE OR REPLACE VIEW integrarp.vw_bi_estoque_critico AS SELECT gen_random_uuid() AS id, NULL::uuid AS tenant_id, 'vw_bi_estoque_critico'::text AS indicador, 0::numeric AS valor, now() AS atualizado_em;
CREATE OR REPLACE VIEW integrarp.vw_bi_lotes_vencendo AS SELECT gen_random_uuid() AS id, NULL::uuid AS tenant_id, 'vw_bi_lotes_vencendo'::text AS indicador, 0::numeric AS valor, now() AS atualizado_em;
CREATE OR REPLACE VIEW integrarp.vw_bi_financeiro_resumo AS SELECT gen_random_uuid() AS id, NULL::uuid AS tenant_id, 'vw_bi_financeiro_resumo'::text AS indicador, 0::numeric AS valor, now() AS atualizado_em;
CREATE OR REPLACE VIEW integrarp.vw_bi_titulos_vencidos AS SELECT gen_random_uuid() AS id, NULL::uuid AS tenant_id, 'vw_bi_titulos_vencidos'::text AS indicador, 0::numeric AS valor, now() AS atualizado_em;
CREATE OR REPLACE VIEW integrarp.vw_bi_faturamento_mensal AS SELECT gen_random_uuid() AS id, NULL::uuid AS tenant_id, 'vw_bi_faturamento_mensal'::text AS indicador, 0::numeric AS valor, now() AS atualizado_em;
CREATE OR REPLACE VIEW integrarp.vw_bi_connect_resumo AS SELECT gen_random_uuid() AS id, NULL::uuid AS tenant_id, 'vw_bi_connect_resumo'::text AS indicador, 0::numeric AS valor, now() AS atualizado_em;
CREATE OR REPLACE VIEW integrarp.vw_bi_outbox_erros AS SELECT gen_random_uuid() AS id, NULL::uuid AS tenant_id, 'vw_bi_outbox_erros'::text AS indicador, 0::numeric AS valor, now() AS atualizado_em;
CREATE OR REPLACE VIEW integrarp.vw_bi_mensagens_por_canal AS SELECT gen_random_uuid() AS id, NULL::uuid AS tenant_id, 'vw_bi_mensagens_por_canal'::text AS indicador, 0::numeric AS valor, now() AS atualizado_em;
CREATE OR REPLACE VIEW integrarp.vw_projeto_central_resumo AS SELECT gen_random_uuid() AS id, NULL::uuid AS tenant_id, 'vw_projeto_central_resumo'::text AS indicador, 0::numeric AS valor, now() AS atualizado_em;
CREATE OR REPLACE VIEW integrarp.vw_projeto_central_velocity AS SELECT gen_random_uuid() AS id, NULL::uuid AS tenant_id, 'vw_projeto_central_velocity'::text AS indicador, 0::numeric AS valor, now() AS atualizado_em;
CREATE OR REPLACE VIEW integrarp.vw_projeto_central_burndown AS SELECT gen_random_uuid() AS id, NULL::uuid AS tenant_id, 'vw_projeto_central_burndown'::text AS indicador, 0::numeric AS valor, now() AS atualizado_em;
CREATE OR REPLACE VIEW integrarp.vw_projeto_central_carga_por_responsavel AS SELECT gen_random_uuid() AS id, NULL::uuid AS tenant_id, 'vw_projeto_central_carga_por_responsavel'::text AS indicador, 0::numeric AS valor, now() AS atualizado_em;
CREATE OR REPLACE VIEW integrarp.vw_projeto_central_itens_atrasados AS SELECT gen_random_uuid() AS id, NULL::uuid AS tenant_id, 'vw_projeto_central_itens_atrasados'::text AS indicador, 0::numeric AS valor, now() AS atualizado_em;
INSERT INTO integrarp.kpi_definicao (codigo,nome,modulo,unidade,publico) VALUES
('s7_1','Pedidos processados no prazo','Sprint7','quantidade',true),
('s7_2','Tempo médio de separação','Sprint7','quantidade',true),
('s7_3','Precisão de estoque','Sprint7','quantidade',true),
('s7_4','Entregas no prazo','Sprint7','quantidade',true),
('s7_5','Provas de entrega registradas','Sprint7','quantidade',true),
('s7_6','Títulos recebidos no prazo','Sprint7','quantidade',true),
('s7_7','Tempo de emissão de título/NF','Sprint7','quantidade',true),
('s7_8','Taxa de conversão','Sprint7','quantidade',true),
('s7_9','Satisfação do cliente','Sprint7','quantidade',true),
('s7_10','Tarefas atrasadas','Sprint7','quantidade',true),
('s7_11','Processos atrasados','Sprint7','quantidade',true),
('s7_12','SLA vencido','Sprint7','quantidade',true),
('s7_13','Estoque crítico','Sprint7','quantidade',true),
('s7_14','Outbox com erro','Sprint7','quantidade',true),
('s7_15','Velocity por sprint','Sprint7','quantidade',true),
('s7_16','Burndown saudável','Sprint7','quantidade',true) ON CONFLICT DO NOTHING;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_score_operacional_range') THEN ALTER TABLE integrarp.score_operacional ADD CONSTRAINT ck_score_operacional_range CHECK (score >= 0 AND score <= 100); END IF; END $$;
