-- IntegraRP database complete idempotent script v1.1
CREATE SCHEMA IF NOT EXISTS integrarp;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE OR REPLACE FUNCTION integrarp.fn_set_atualizado_em()
RETURNS trigger AS $$
BEGIN
    NEW.atualizado_em = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Core
-- v1.15: schema_migrations é gerenciada exclusivamente pelo Migration Runner; registro legado removido.
CREATE TABLE IF NOT EXISTS integrarp.tenant (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), nome text NOT NULL, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NULL, atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb);
-- Segurança
CREATE TABLE IF NOT EXISTS integrarp.usuario (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, email text NOT NULL, nome text NOT NULL, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NULL, atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb);
CREATE TABLE IF NOT EXISTS integrarp.perfil (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, nome text NOT NULL, permissoes_json jsonb NOT NULL DEFAULT '[]'::jsonb, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NULL, atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb);
-- Flow
CREATE TABLE IF NOT EXISTS integrarp.flow_tarefa (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, titulo text NOT NULL, status text NOT NULL DEFAULT 'pendente', criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NULL, atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb);
-- Studio
CREATE TABLE IF NOT EXISTS integrarp.studio_modulo (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, codigo text NOT NULL, nome text NOT NULL, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NULL, atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb);
-- Comercial
CREATE TABLE IF NOT EXISTS integrarp.pedido (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, numero text NOT NULL, status text NOT NULL, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NULL, atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb);
-- Estoque
CREATE TABLE IF NOT EXISTS integrarp.produto (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, sku text NOT NULL, nome text NOT NULL, estoque_atual numeric NOT NULL DEFAULT 0, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NULL, atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb);
-- Faturamento
CREATE TABLE IF NOT EXISTS integrarp.titulo_financeiro (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, numero text NOT NULL, valor numeric NOT NULL, vencimento date NOT NULL, status text NOT NULL, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NULL, atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb);
-- Connect
CREATE TABLE IF NOT EXISTS integrarp.connect_outbox (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, tipo text NOT NULL, payload_json jsonb NOT NULL, status text NOT NULL DEFAULT 'pendente', criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NULL, atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb);
-- BI
CREATE TABLE IF NOT EXISTS integrarp.kpi_valor (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, codigo text NOT NULL, valor numeric NOT NULL, referencia_em timestamptz NOT NULL DEFAULT now(), criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NULL, atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb);
-- Project
CREATE TABLE IF NOT EXISTS integrarp.project_board (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, nome text NOT NULL, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NULL, atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb);
-- Mobile
CREATE TABLE IF NOT EXISTS integrarp.mobile_device (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, usuario_id uuid NULL, push_token text NULL, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NULL, atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb);
-- IA
CREATE TABLE IF NOT EXISTS integrarp.ai_auditoria (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, pergunta text NOT NULL, resposta text NULL, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NULL, atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb);
-- Operações
CREATE TABLE IF NOT EXISTS integrarp.entrega (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, codigo text NOT NULL, status text NOT NULL, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NULL, atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb);

-- Forms
CREATE TABLE IF NOT EXISTS integrarp.formulario_definicao (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, nome text NOT NULL, descricao text NULL, status text NOT NULL DEFAULT 'draft', versao_publicada_id uuid NULL, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NULL, atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb);
CREATE TABLE IF NOT EXISTS integrarp.formulario_versao (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, formulario_definicao_id uuid NOT NULL, numero int NOT NULL, publicado boolean NOT NULL DEFAULT false, publicado_em timestamptz NULL, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NULL, atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb);
CREATE TABLE IF NOT EXISTS integrarp.formulario_secao (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, formulario_versao_id uuid NOT NULL, titulo text NOT NULL, ordem int NOT NULL, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NULL, atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb);
CREATE TABLE IF NOT EXISTS integrarp.formulario_campo (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, formulario_secao_id uuid NOT NULL, chave text NOT NULL, rotulo text NOT NULL, tipo text NOT NULL, ordem int NOT NULL, obrigatorio boolean NOT NULL DEFAULT false, mascara text NULL, regex_validacao text NULL, valor_padrao text NULL, opcoes_json jsonb NOT NULL DEFAULT '[]'::jsonb, visibilidade_json jsonb NOT NULL DEFAULT '{}'::jsonb, calculo_json jsonb NOT NULL DEFAULT '{}'::jsonb, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NULL, atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb);
CREATE TABLE IF NOT EXISTS integrarp.formulario_regra (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, formulario_versao_id uuid NOT NULL, nome text NOT NULL, condicao_json jsonb NOT NULL, acao_json jsonb NOT NULL, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NULL, atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb);
CREATE TABLE IF NOT EXISTS integrarp.formulario_resposta (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, formulario_versao_id uuid NOT NULL, entidade_tipo text NULL, entidade_id uuid NULL, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NULL, atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb);
CREATE TABLE IF NOT EXISTS integrarp.formulario_resposta_campo (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, formulario_resposta_id uuid NOT NULL, formulario_campo_id uuid NOT NULL, valor_json jsonb NULL, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NULL, atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb);
CREATE TABLE IF NOT EXISTS integrarp.formulario_template (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, nome text NOT NULL, template_json jsonb NOT NULL, demo boolean NOT NULL DEFAULT false, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NULL, atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb);
CREATE TABLE IF NOT EXISTS integrarp.formulario_validacao_log (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, formulario_resposta_id uuid NULL, mensagem text NOT NULL, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NULL, atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb);

-- Automação
CREATE TABLE IF NOT EXISTS integrarp.automacao_regra (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, nome text NOT NULL, habilitada boolean NOT NULL DEFAULT true, max_retries int NOT NULL DEFAULT 3, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NULL, atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb);
CREATE TABLE IF NOT EXISTS integrarp.automacao_gatilho (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, automacao_regra_id uuid NOT NULL, tipo text NOT NULL, config_json jsonb NOT NULL DEFAULT '{}'::jsonb, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NULL, atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb);
CREATE TABLE IF NOT EXISTS integrarp.automacao_condicao (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, automacao_regra_id uuid NOT NULL, campo text NOT NULL, operador text NOT NULL, valor_esperado text NULL, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NULL, atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb);
CREATE TABLE IF NOT EXISTS integrarp.automacao_acao (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, automacao_regra_id uuid NOT NULL, tipo text NOT NULL, ordem int NOT NULL, config_json jsonb NOT NULL DEFAULT '{}'::jsonb, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NULL, atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb);
CREATE TABLE IF NOT EXISTS integrarp.automacao_execucao (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, automacao_regra_id uuid NOT NULL, status text NOT NULL DEFAULT 'pendente', tentativa int NOT NULL DEFAULT 0, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NULL, atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb);
CREATE TABLE IF NOT EXISTS integrarp.automacao_execucao_log (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, automacao_execucao_id uuid NOT NULL, nivel text NOT NULL, mensagem text NOT NULL, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NULL, atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb);

-- Anexos
CREATE TABLE IF NOT EXISTS integrarp.anexo_arquivo (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, nome_arquivo text NOT NULL, content_type text NOT NULL, tamanho_bytes bigint NOT NULL, extensao text NOT NULL, sha256 text NOT NULL, storage_key text NOT NULL, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NULL, atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb);
CREATE TABLE IF NOT EXISTS integrarp.anexo_vinculo (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, anexo_arquivo_id uuid NOT NULL, entidade_tipo text NOT NULL, entidade_id uuid NOT NULL, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NULL, atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb);
CREATE TABLE IF NOT EXISTS integrarp.anexo_versao (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, anexo_arquivo_id uuid NOT NULL, numero int NOT NULL, storage_key text NOT NULL, sha256 text NOT NULL, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NULL, atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb);
CREATE TABLE IF NOT EXISTS integrarp.anexo_auditoria (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, anexo_arquivo_id uuid NOT NULL, acao text NOT NULL, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NULL, atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb);
CREATE TABLE IF NOT EXISTS integrarp.anexo_thumbnail (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, anexo_arquivo_id uuid NOT NULL, storage_key text NOT NULL, largura int NOT NULL, altura int NOT NULL, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NULL, atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb);
CREATE TABLE IF NOT EXISTS integrarp.anexo_assinatura (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, anexo_arquivo_id uuid NOT NULL, assinante text NOT NULL, assinado_em timestamptz NOT NULL, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NULL, atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb);
CREATE TABLE IF NOT EXISTS integrarp.anexo_configuracao (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, extensoes_permitidas text NOT NULL, tamanho_maximo_bytes bigint NOT NULL, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NULL, atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb);

-- Notificações
CREATE TABLE IF NOT EXISTS integrarp.notificacao (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, evento text NOT NULL, titulo text NOT NULL, corpo text NOT NULL, canal text NOT NULL DEFAULT 'sistema', status text NOT NULL DEFAULT 'pendente', criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NULL, atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb);
CREATE TABLE IF NOT EXISTS integrarp.notificacao_destinatario (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, notificacao_id uuid NOT NULL, usuario_id uuid NOT NULL, lida boolean NOT NULL DEFAULT false, lida_em timestamptz NULL, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NULL, atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb);
CREATE TABLE IF NOT EXISTS integrarp.notificacao_preferencia (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, usuario_id uuid NOT NULL, canal text NOT NULL, habilitado boolean NOT NULL DEFAULT true, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NULL, atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb);
CREATE TABLE IF NOT EXISTS integrarp.notificacao_template (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, evento text NOT NULL, canal text NOT NULL, assunto_template text NOT NULL, corpo_template text NOT NULL, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NULL, atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb);
CREATE TABLE IF NOT EXISTS integrarp.notificacao_push_log (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, notificacao_id uuid NOT NULL, canal text NOT NULL, status text NOT NULL, erro text NULL, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NULL, atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb);

-- Relatórios
CREATE TABLE IF NOT EXISTS integrarp.relatorio_definicao (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, nome text NOT NULL, chave_consulta text NOT NULL, formatos_json jsonb NOT NULL DEFAULT '["csv","pdf_html","json"]'::jsonb, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NULL, atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb);
CREATE TABLE IF NOT EXISTS integrarp.relatorio_filtro (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, relatorio_definicao_id uuid NOT NULL, nome text NOT NULL, tipo text NOT NULL, obrigatorio boolean NOT NULL DEFAULT false, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NULL, atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb);
CREATE TABLE IF NOT EXISTS integrarp.relatorio_execucao (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, relatorio_definicao_id uuid NOT NULL, status text NOT NULL DEFAULT 'pendente', parametros_json jsonb NOT NULL DEFAULT '{}'::jsonb, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NULL, atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb);
CREATE TABLE IF NOT EXISTS integrarp.relatorio_exportacao (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, relatorio_execucao_id uuid NOT NULL, formato text NOT NULL, storage_key text NOT NULL, expira_em timestamptz NULL, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NULL, atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb);
CREATE TABLE IF NOT EXISTS integrarp.relatorio_agendamento (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, relatorio_definicao_id uuid NOT NULL, cron text NOT NULL, formato text NOT NULL, habilitado boolean NOT NULL DEFAULT true, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NULL, atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb);

ALTER TABLE integrarp.formulario_definicao ADD COLUMN IF NOT EXISTS categoria text NULL;
ALTER TABLE integrarp.automacao_regra ADD COLUMN IF NOT EXISTS seguranca_json jsonb NOT NULL DEFAULT '{"no_eval":true,"no_dynamic_sql":true,"rbac":true}'::jsonb;
ALTER TABLE integrarp.anexo_arquivo ADD COLUMN IF NOT EXISTS validado boolean NOT NULL DEFAULT true;
ALTER TABLE integrarp.relatorio_definicao ADD COLUMN IF NOT EXISTS descricao text NULL;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_formulario_campo_tipo_v11') THEN ALTER TABLE integrarp.formulario_campo ADD CONSTRAINT ck_formulario_campo_tipo_v11 CHECK (tipo IN ('text','textarea','number','money','date','datetime','boolean','select','multiselect','user','sector','client','product','order','financial_title','dynamic_record','file','photo','signature','gps','barcode','qrcode','rating','checklist','json','relation')); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_notificacao_canal_v11') THEN ALTER TABLE integrarp.notificacao ADD CONSTRAINT ck_notificacao_canal_v11 CHECK (canal IN ('sistema','email_fake','whatsapp_fake','telegram_fake','mobile_push_fake','webhook_fake')); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_relatorio_formato_v11') THEN ALTER TABLE integrarp.relatorio_exportacao ADD CONSTRAINT ck_relatorio_formato_v11 CHECK (formato IN ('csv','xlsx','pdf_html','json')); END IF; END $$;

CREATE INDEX IF NOT EXISTS ix_formulario_definicao_tenant ON integrarp.formulario_definicao(tenant_id);
CREATE INDEX IF NOT EXISTS ix_automacao_execucao_status ON integrarp.automacao_execucao(tenant_id,status);
CREATE INDEX IF NOT EXISTS ix_anexo_vinculo_entidade ON integrarp.anexo_vinculo(tenant_id,entidade_tipo,entidade_id);
CREATE INDEX IF NOT EXISTS ix_notificacao_destinatario_usuario ON integrarp.notificacao_destinatario(tenant_id,usuario_id,lida);
CREATE INDEX IF NOT EXISTS ix_relatorio_execucao_relatorio ON integrarp.relatorio_execucao(tenant_id,relatorio_definicao_id,status);

CREATE OR REPLACE VIEW integrarp.vw_v11_relatorios_demo AS SELECT tenant_id, nome, chave_consulta FROM integrarp.relatorio_definicao WHERE excluido_em IS NULL;

DROP TRIGGER IF EXISTS trg_formulario_definicao_atualizado_em ON integrarp.formulario_definicao;
CREATE TRIGGER trg_formulario_definicao_atualizado_em BEFORE UPDATE ON integrarp.formulario_definicao FOR EACH ROW EXECUTE FUNCTION integrarp.fn_set_atualizado_em();
DROP TRIGGER IF EXISTS trg_automacao_regra_atualizado_em ON integrarp.automacao_regra;
CREATE TRIGGER trg_automacao_regra_atualizado_em BEFORE UPDATE ON integrarp.automacao_regra FOR EACH ROW EXECUTE FUNCTION integrarp.fn_set_atualizado_em();
DROP TRIGGER IF EXISTS trg_anexo_arquivo_atualizado_em ON integrarp.anexo_arquivo;
CREATE TRIGGER trg_anexo_arquivo_atualizado_em BEFORE UPDATE ON integrarp.anexo_arquivo FOR EACH ROW EXECUTE FUNCTION integrarp.fn_set_atualizado_em();
DROP TRIGGER IF EXISTS trg_notificacao_atualizado_em ON integrarp.notificacao;
CREATE TRIGGER trg_notificacao_atualizado_em BEFORE UPDATE ON integrarp.notificacao FOR EACH ROW EXECUTE FUNCTION integrarp.fn_set_atualizado_em();
DROP TRIGGER IF EXISTS trg_relatorio_definicao_atualizado_em ON integrarp.relatorio_definicao;
CREATE TRIGGER trg_relatorio_definicao_atualizado_em BEFORE UPDATE ON integrarp.relatorio_definicao FOR EACH ROW EXECUTE FUNCTION integrarp.fn_set_atualizado_em();

INSERT INTO integrarp.tenant (id,nome,metadata_json) VALUES ('11111111-1111-1111-1111-111111111111','Demo IntegraRP v1.1','{"demo":true}'::jsonb) ON CONFLICT (id) DO NOTHING;
INSERT INTO integrarp.formulario_template (tenant_id,nome,template_json,demo) VALUES
('11111111-1111-1111-1111-111111111111','Checklist de Visita Comercial','{"fields":["cliente","gps","assinatura"]}'::jsonb,true),
('11111111-1111-1111-1111-111111111111','Checklist de Entrega com POD','{"fields":["photo","signature","gps"]}'::jsonb,true),
('11111111-1111-1111-1111-111111111111','Registro de Avaria','{"fields":["product","photo","textarea"]}'::jsonb,true),
('11111111-1111-1111-1111-111111111111','Pesquisa de Satisfação','{"fields":["rating","textarea"]}'::jsonb,true)
ON CONFLICT DO NOTHING;
INSERT INTO integrarp.automacao_regra (tenant_id,nome,habilitada,metadata_json) VALUES
('11111111-1111-1111-1111-111111111111','Tarefa atrasada',true,'{"trigger":"task_overdue","action":"send_notification"}'::jsonb),
('11111111-1111-1111-1111-111111111111','Ocorrência cria tarefa',true,'{"trigger":"delivery_occurrence_created","action":"create_task"}'::jsonb)
ON CONFLICT DO NOTHING;
INSERT INTO integrarp.relatorio_definicao (tenant_id,nome,chave_consulta) VALUES
('11111111-1111-1111-1111-111111111111','Pedidos por período','orders_by_period'),
('11111111-1111-1111-1111-111111111111','Estoque crítico','critical_inventory'),
('11111111-1111-1111-1111-111111111111','Títulos vencidos','overdue_titles')
ON CONFLICT DO NOTHING;
INSERT INTO integrarp.notificacao (tenant_id,evento,titulo,corpo,canal,status) VALUES ('11111111-1111-1111-1111-111111111111','automacao falhou','Demo v1.1','Notificação demo','sistema','pendente') ON CONFLICT DO NOTHING;
INSERT INTO integrarp.anexo_configuracao (tenant_id,extensoes_permitidas,tamanho_maximo_bytes,metadata_json) VALUES ('11111111-1111-1111-1111-111111111111','.pdf,.png,.jpg,.jpeg,.csv',10485760,'{"demo":"Anexos demo"}'::jsonb) ON CONFLICT DO NOTHING;
-- v1.15: schema_migrations é gerenciada exclusivamente pelo Migration Runner; registro legado removido.
