
-- v1.2 Jornada do Cliente, Onboarding Guiado e UX Operacional
CREATE SCHEMA IF NOT EXISTS integrarp;
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE OR REPLACE FUNCTION integrarp.fn_set_atualizado_em()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    NEW.atualizado_em = now();
    RETURN NEW;
END;
$$;

-- v1.15: schema_migrations é gerenciada exclusivamente pelo Migration Runner; registro legado removido.

CREATE TABLE IF NOT EXISTS integrarp.jornada_cliente (jornada_cliente_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NULL, codigo varchar(120) NOT NULL, nome varchar(180) NOT NULL, descricao text NULL, perfil_alvo varchar(80) NULL, modulo varchar(80) NULL, ordem numeric(12,4) NOT NULL DEFAULT 0, ativo boolean NOT NULL DEFAULT true, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NULL, atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb);
CREATE TABLE IF NOT EXISTS integrarp.jornada_etapa (jornada_etapa_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NULL, jornada_cliente_id uuid NOT NULL, codigo varchar(120) NOT NULL, titulo varchar(180) NOT NULL, descricao text NULL, modulo varchar(80) NULL, rota_web varchar(240) NULL, rota_mobile varchar(240) NULL, acao_api varchar(240) NULL, tipo varchar(60) NOT NULL DEFAULT 'manual', obrigatoria boolean NOT NULL DEFAULT true, ordem numeric(12,4) NOT NULL DEFAULT 0, criterio_conclusao_json jsonb NOT NULL DEFAULT '{}'::jsonb, dica_json jsonb NOT NULL DEFAULT '{}'::jsonb, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NULL, atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb);
CREATE TABLE IF NOT EXISTS integrarp.jornada_usuario_progresso (jornada_usuario_progresso_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, usuario_id uuid NOT NULL, jornada_cliente_id uuid NOT NULL, jornada_etapa_id uuid NULL, status varchar(40) NOT NULL DEFAULT 'pendente', iniciado_em timestamptz NULL, concluido_em timestamptz NULL, ultima_interacao_em timestamptz NULL, progresso_percentual numeric(10,2) NOT NULL DEFAULT 0, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb);
CREATE TABLE IF NOT EXISTS integrarp.jornada_checklist (jornada_checklist_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, jornada_etapa_id uuid NOT NULL, titulo varchar(180) NOT NULL, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NULL, atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb);
CREATE TABLE IF NOT EXISTS integrarp.jornada_checklist_item (jornada_checklist_item_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, jornada_checklist_id uuid NOT NULL, titulo varchar(180) NOT NULL, obrigatorio boolean NOT NULL DEFAULT true, concluido boolean NOT NULL DEFAULT false, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NULL, atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb);
CREATE TABLE IF NOT EXISTS integrarp.jornada_evento (jornada_evento_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, usuario_id uuid NOT NULL, tipo varchar(80) NOT NULL, entidade_tipo varchar(80) NULL, entidade_id uuid NULL, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NULL, atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb);
CREATE TABLE IF NOT EXISTS integrarp.jornada_dica_contextual (jornada_dica_contextual_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NULL, chave_tela varchar(160) NOT NULL, titulo varchar(180) NOT NULL, conteudo text NOT NULL, proxima_acao varchar(180) NOT NULL, rota_web varchar(240) NULL, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NULL, atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb);
CREATE TABLE IF NOT EXISTS integrarp.jornada_tour (jornada_tour_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NULL, codigo varchar(120) NOT NULL, titulo varchar(180) NOT NULL, gatilho varchar(60) NOT NULL DEFAULT 'manual', criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NULL, atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb);
CREATE TABLE IF NOT EXISTS integrarp.jornada_tour_passo (jornada_tour_passo_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NULL, jornada_tour_id uuid NOT NULL, seletor_css varchar(180) NULL, titulo varchar(180) NOT NULL, conteudo text NOT NULL, ordem numeric(12,4) NOT NULL DEFAULT 0, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NULL, atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb);
CREATE TABLE IF NOT EXISTS integrarp.jornada_estado_vazio (jornada_estado_vazio_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NULL, chave_tela varchar(160) NOT NULL, tipo varchar(60) NOT NULL DEFAULT 'lista', titulo varchar(180) NOT NULL, explicacao text NOT NULL, acao_rotulo varchar(120) NOT NULL, acao_rota_web varchar(240) NULL, exemplo_json jsonb NOT NULL DEFAULT '{}'::jsonb, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NULL, atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb);
CREATE TABLE IF NOT EXISTS integrarp.jornada_acao_recomendada (jornada_acao_recomendada_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, usuario_id uuid NULL, perfil varchar(80) NULL, modulo varchar(80) NULL, titulo varchar(180) NOT NULL, descricao text NULL, prioridade varchar(20) NOT NULL DEFAULT 'media', rota_web varchar(240) NULL, rota_mobile varchar(240) NULL, entidade_tipo varchar(80) NULL, entidade_id uuid NULL, motivo varchar(180) NULL, status varchar(40) NOT NULL DEFAULT 'pendente', criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NULL, atualizado_por_usuario_id uuid NULL, concluido_em timestamptz NULL, excluido_em timestamptz NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb);
CREATE TABLE IF NOT EXISTS integrarp.jornada_feedback_usuario (jornada_feedback_usuario_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, usuario_id uuid NOT NULL, nota int NOT NULL, comentario text NULL, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NULL, atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb);
CREATE TABLE IF NOT EXISTS integrarp.adocao_score (adocao_score_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, score numeric(10,2) NOT NULL DEFAULT 0, periodo_inicio timestamptz NULL, periodo_fim timestamptz NULL, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NULL, atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb);
CREATE TABLE IF NOT EXISTS integrarp.adocao_evento (adocao_evento_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, usuario_id uuid NULL, tipo varchar(80) NOT NULL, peso numeric(10,2) NOT NULL DEFAULT 1, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NULL, atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb);
CREATE TABLE IF NOT EXISTS integrarp.adocao_modulo_status (adocao_modulo_status_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, modulo varchar(80) NOT NULL, status varchar(40) NOT NULL DEFAULT 'incompleto', score numeric(10,2) NOT NULL DEFAULT 0, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NULL, atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb);
CREATE TABLE IF NOT EXISTS integrarp.adocao_usuario_status (adocao_usuario_status_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, usuario_id uuid NOT NULL, status varchar(40) NOT NULL DEFAULT 'ativo', ultimo_login_em timestamptz NULL, score numeric(10,2) NOT NULL DEFAULT 0, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NULL, atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb);

ALTER TABLE integrarp.jornada_cliente ADD COLUMN IF NOT EXISTS metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_jornada_usuario_progresso_status') THEN ALTER TABLE integrarp.jornada_usuario_progresso ADD CONSTRAINT ck_jornada_usuario_progresso_status CHECK (status IN ('pendente','em_andamento','concluida','ignorada','bloqueada')); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_jornada_progresso_percentual') THEN ALTER TABLE integrarp.jornada_usuario_progresso ADD CONSTRAINT ck_jornada_progresso_percentual CHECK (progresso_percentual >= 0 AND progresso_percentual <= 100); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_jornada_etapa_cliente') THEN ALTER TABLE integrarp.jornada_etapa ADD CONSTRAINT fk_jornada_etapa_cliente FOREIGN KEY (jornada_cliente_id) REFERENCES integrarp.jornada_cliente(jornada_cliente_id); END IF; END $$;

CREATE INDEX IF NOT EXISTS ix_jornada_cliente_codigo ON integrarp.jornada_cliente(codigo);
CREATE INDEX IF NOT EXISTS ix_jornada_etapa_jornada ON integrarp.jornada_etapa(jornada_cliente_id, ordem);
CREATE INDEX IF NOT EXISTS ix_jornada_usuario_progresso_tenant_usuario ON integrarp.jornada_usuario_progresso(tenant_id, usuario_id, status);
CREATE INDEX IF NOT EXISTS ix_jornada_acao_recomendada_usuario ON integrarp.jornada_acao_recomendada(tenant_id, usuario_id, status, prioridade);
CREATE INDEX IF NOT EXISTS ix_adocao_score_tenant ON integrarp.adocao_score(tenant_id, periodo_fim);

DROP TRIGGER IF EXISTS trg_jornada_cliente_atualizado_em ON integrarp.jornada_cliente; CREATE TRIGGER trg_jornada_cliente_atualizado_em BEFORE UPDATE ON integrarp.jornada_cliente FOR EACH ROW EXECUTE FUNCTION integrarp.fn_set_atualizado_em();
DROP TRIGGER IF EXISTS trg_jornada_etapa_atualizado_em ON integrarp.jornada_etapa; CREATE TRIGGER trg_jornada_etapa_atualizado_em BEFORE UPDATE ON integrarp.jornada_etapa FOR EACH ROW EXECUTE FUNCTION integrarp.fn_set_atualizado_em();
DROP TRIGGER IF EXISTS trg_jornada_acao_recomendada_atualizado_em ON integrarp.jornada_acao_recomendada; CREATE TRIGGER trg_jornada_acao_recomendada_atualizado_em BEFORE UPDATE ON integrarp.jornada_acao_recomendada FOR EACH ROW EXECUTE FUNCTION integrarp.fn_set_atualizado_em();
DROP TRIGGER IF EXISTS trg_adocao_score_atualizado_em ON integrarp.adocao_score; CREATE TRIGGER trg_adocao_score_atualizado_em BEFORE UPDATE ON integrarp.adocao_score FOR EACH ROW EXECUTE FUNCTION integrarp.fn_set_atualizado_em();

CREATE OR REPLACE VIEW integrarp.vw_jornada_onboarding_status AS SELECT jc.tenant_id, jc.codigo, jc.nome, COALESCE(avg(jup.progresso_percentual),0) AS progresso_percentual FROM integrarp.jornada_cliente jc LEFT JOIN integrarp.jornada_usuario_progresso jup ON jup.jornada_cliente_id = jc.jornada_cliente_id GROUP BY jc.tenant_id, jc.codigo, jc.nome;
CREATE OR REPLACE VIEW integrarp.vw_jornada_usuario_progresso AS SELECT * FROM integrarp.jornada_usuario_progresso;
CREATE OR REPLACE VIEW integrarp.vw_acao_recomendada_usuario AS SELECT tenant_id, usuario_id, titulo, prioridade, rota_web, status, criado_em FROM integrarp.jornada_acao_recomendada WHERE status = 'pendente';
CREATE OR REPLACE VIEW integrarp.vw_o_que_fazer_agora AS SELECT tenant_id, usuario_id, 'acao_recomendada'::text AS origem, titulo, descricao, prioridade, rota_web, status, criado_em FROM integrarp.jornada_acao_recomendada WHERE status = 'pendente' UNION ALL SELECT tenant_id, usuario_id, 'jornadas_incompletas'::text AS origem, 'Continuar onboarding'::varchar(180) AS titulo, 'Concluir etapas pendentes da jornada guiada'::text AS descricao, 'alta'::varchar(20) AS prioridade, '/onboarding'::varchar(240) AS rota_web, status, ultima_interacao_em AS criado_em FROM integrarp.jornada_usuario_progresso WHERE status IN ('pendente','em_andamento','bloqueada');
CREATE OR REPLACE VIEW integrarp.vw_pendencias_por_perfil AS SELECT tenant_id, perfil, prioridade, count(*) AS total FROM integrarp.jornada_acao_recomendada WHERE status = 'pendente' GROUP BY tenant_id, perfil, prioridade;
CREATE OR REPLACE VIEW integrarp.vw_gargalos_para_gestor AS SELECT tenant_id, modulo, count(*) AS total_pendencias FROM integrarp.jornada_acao_recomendada WHERE status = 'pendente' GROUP BY tenant_id, modulo;
CREATE OR REPLACE VIEW integrarp.vw_proximos_passos_operacionais AS SELECT tenant_id, usuario_id, titulo, rota_web FROM integrarp.jornada_acao_recomendada WHERE status = 'pendente';
CREATE OR REPLACE VIEW integrarp.vw_modulos_incompletos_configuracao AS SELECT tenant_id, modulo, status FROM integrarp.adocao_modulo_status WHERE status <> 'completo';
CREATE OR REPLACE VIEW integrarp.vw_adocao_score_tenant AS SELECT tenant_id, max(score) AS score FROM integrarp.adocao_score GROUP BY tenant_id;
CREATE OR REPLACE VIEW integrarp.vw_adocao_modulos AS SELECT tenant_id, modulo, status, score FROM integrarp.adocao_modulo_status;
CREATE OR REPLACE VIEW integrarp.vw_adocao_usuarios AS SELECT tenant_id, usuario_id, status, score, ultimo_login_em FROM integrarp.adocao_usuario_status;

INSERT INTO integrarp.jornada_cliente (codigo, nome, descricao, perfil_alvo, modulo, ordem) VALUES
('primeiros-passos-administrador','Primeiros Passos do Administrador','Confirmar dados da empresa; Criar setores; Criar usuários; Definir perfis; Instalar pacote operacional; Criar primeiro processo; Criar primeiro cliente; Criar primeiro produto; Registrar entrada de estoque; Criar primeiro pedido; Ver dashboard.','Administrador do Tenant','core',1),
('operacao-diaria','Operação Diária','Ver painel O que fazer agora; Abrir minhas tarefas; Resolver atrasos; Ver pedidos pendentes; Ver estoque crítico; Ver títulos vencidos; Ver ocorrências; Consultar IA se necessário.','Operador','operacao',2),
('gestor','Gestor','Ver score operacional; Ver gargalos; Ver SLAs vencidos; Ver responsáveis; Exportar relatório; Criar ação corretiva; Acompanhar Project.','Diretor','gestao',3),
('usuario-campo','Usuário de Campo','Abrir app mobile; Ver minha fila; Abrir tarefa; Executar checklist; Registrar evidência; Capturar assinatura/GPS; Concluir; Sincronizar.','Motorista','mobile',4),
('studio','Studio','Criar módulo; Criar campos; Criar formulário; Criar ação; Conectar BPMN; Publicar; Criar primeiro registro; Ver KPI; Permitir consulta pela IA.','Administrador do Tenant','studio',5)
ON CONFLICT DO NOTHING;

INSERT INTO integrarp.jornada_acao_recomendada (tenant_id, titulo, descricao, prioridade, rota_web, motivo) VALUES ('00000000-0000-0000-0000-000000000001','Criar primeiro pedido','Complete cliente, produto e estoque para validar o fluxo comercial.','alta','/onboarding/first-order','seed demo v1.2') ON CONFLICT DO NOTHING;
-- RBAC v1.2: journey.visualizar journey.iniciar journey.concluir_etapa journey.ignorar_etapa journey.resetar journey.acoes.visualizar journey.acoes.concluir journey.ajuda.visualizar journey.tour.visualizar journey.feedback.enviar
-- Perfis: Administrador Geral; Administrador do Tenant; Diretor; Coordenador; Financeiro; Vendas; Logística; Motorista; Promotor de Vendas; Operador.
-- v1.15: schema_migrations é gerenciada exclusivamente pelo Migration Runner; registro legado removido.
