
-- V1.8 - Funcionalidade real de produto: tabelas reais de domínio
CREATE SCHEMA IF NOT EXISTS integrarp;
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE OR REPLACE FUNCTION integrarp.fn_set_atualizado_em() RETURNS trigger AS $$
BEGIN
  NEW.atualizado_em = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TABLE IF NOT EXISTS integrarp.tenant (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), nome text NOT NULL, status text NOT NULL DEFAULT 'ativo', criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NOT NULL DEFAULT now(), atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NULL);
CREATE TABLE IF NOT EXISTS integrarp.usuario (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, nome text NOT NULL, email text NOT NULL, status text NOT NULL DEFAULT 'ativo', senha_hash text NULL, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NOT NULL DEFAULT now(), atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NULL, UNIQUE(tenant_id,email));
CREATE TABLE IF NOT EXISTS integrarp.perfil (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, nome text NOT NULL, status text NOT NULL DEFAULT 'ativo', criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NOT NULL DEFAULT now(), atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NULL, UNIQUE(tenant_id,nome));
CREATE TABLE IF NOT EXISTS integrarp.permissao (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, codigo text NOT NULL, descricao text NULL, status text NOT NULL DEFAULT 'ativo', criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NOT NULL DEFAULT now(), atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NULL, UNIQUE(tenant_id,codigo));
CREATE TABLE IF NOT EXISTS integrarp.usuario_perfil (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, usuario_id uuid NOT NULL, perfil_id uuid NOT NULL, status text NOT NULL DEFAULT 'ativo', criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NOT NULL DEFAULT now(), atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NULL, UNIQUE(tenant_id,usuario_id,perfil_id));
CREATE TABLE IF NOT EXISTS integrarp.setor (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, nome text NOT NULL, status text NOT NULL DEFAULT 'ativo', criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NOT NULL DEFAULT now(), atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NULL);
CREATE TABLE IF NOT EXISTS integrarp.cargo (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, setor_id uuid NULL, nome text NOT NULL, status text NOT NULL DEFAULT 'ativo', criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NOT NULL DEFAULT now(), atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NULL);

CREATE TABLE IF NOT EXISTS integrarp.cliente (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, razao_social text NOT NULL, nome_fantasia text NULL, documento text NULL, email text NULL, telefone text NULL, status text NOT NULL DEFAULT 'ativo', criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NOT NULL DEFAULT now(), atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NULL);
CREATE TABLE IF NOT EXISTS integrarp.cliente_contato (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, cliente_id uuid NOT NULL, nome text NOT NULL, email text NULL, telefone text NULL, cargo text NULL, status text NOT NULL DEFAULT 'ativo', criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NOT NULL DEFAULT now(), atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NULL);
CREATE TABLE IF NOT EXISTS integrarp.cliente_endereco (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, cliente_id uuid NOT NULL, tipo text NOT NULL DEFAULT 'principal', logradouro text NOT NULL, numero text NULL, cidade text NULL, uf text NULL, cep text NULL, status text NOT NULL DEFAULT 'ativo', criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NOT NULL DEFAULT now(), atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NULL);

CREATE TABLE IF NOT EXISTS integrarp.produto_categoria (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, nome text NOT NULL, status text NOT NULL DEFAULT 'ativo', criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NOT NULL DEFAULT now(), atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NULL);
CREATE TABLE IF NOT EXISTS integrarp.produto (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, categoria_id uuid NULL, sku text NOT NULL, nome text NOT NULL, preco numeric(18,2) NOT NULL DEFAULT 0, estoque_minimo numeric(18,3) NOT NULL DEFAULT 0, status text NOT NULL DEFAULT 'ativo', criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NOT NULL DEFAULT now(), atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NULL, UNIQUE(tenant_id,sku));
CREATE TABLE IF NOT EXISTS integrarp.estoque_local (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, nome text NOT NULL, status text NOT NULL DEFAULT 'ativo', criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NOT NULL DEFAULT now(), atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NULL);
CREATE TABLE IF NOT EXISTS integrarp.estoque_movimento (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, produto_id uuid NOT NULL, estoque_local_id uuid NOT NULL, tipo text NOT NULL, quantidade numeric(18,3) NOT NULL, origem_tipo text NULL, origem_id uuid NULL, status text NOT NULL DEFAULT 'confirmado', criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NOT NULL DEFAULT now(), atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NULL);
CREATE TABLE IF NOT EXISTS integrarp.estoque_saldo (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, produto_id uuid NOT NULL, estoque_local_id uuid NOT NULL, quantidade numeric(18,3) NOT NULL DEFAULT 0, reservado numeric(18,3) NOT NULL DEFAULT 0, status text NOT NULL DEFAULT 'ativo', criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NOT NULL DEFAULT now(), atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NULL, UNIQUE(tenant_id,produto_id,estoque_local_id));
CREATE TABLE IF NOT EXISTS integrarp.estoque_reserva (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, produto_id uuid NOT NULL, estoque_local_id uuid NOT NULL, pedido_id uuid NULL, quantidade numeric(18,3) NOT NULL, status text NOT NULL DEFAULT 'reservado', criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NOT NULL DEFAULT now(), atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NULL);

CREATE TABLE IF NOT EXISTS integrarp.pedido (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, cliente_id uuid NOT NULL, numero text NOT NULL, status text NOT NULL DEFAULT 'rascunho', total numeric(18,2) NOT NULL DEFAULT 0, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NOT NULL DEFAULT now(), atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NULL, UNIQUE(tenant_id,numero));
CREATE TABLE IF NOT EXISTS integrarp.pedido_item (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, pedido_id uuid NOT NULL, produto_id uuid NOT NULL, quantidade numeric(18,3) NOT NULL, preco_unitario numeric(18,2) NOT NULL, total numeric(18,2) NOT NULL, status text NOT NULL DEFAULT 'ativo', criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NOT NULL DEFAULT now(), atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NULL);
CREATE TABLE IF NOT EXISTS integrarp.pedido_historico_status (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, pedido_id uuid NOT NULL, status_anterior text NULL, status_novo text NOT NULL, observacao text NULL, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NOT NULL DEFAULT now(), atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NULL);

CREATE TABLE IF NOT EXISTS integrarp.processo_definicao (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, codigo text NOT NULL, nome text NOT NULL, status text NOT NULL DEFAULT 'ativo', criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NOT NULL DEFAULT now(), atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NULL, UNIQUE(tenant_id,codigo));
CREATE TABLE IF NOT EXISTS integrarp.processo_instancia (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, processo_definicao_id uuid NOT NULL, origem_tipo text NULL, origem_id uuid NULL, status text NOT NULL DEFAULT 'em_andamento', criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NOT NULL DEFAULT now(), atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NULL);
CREATE TABLE IF NOT EXISTS integrarp.tarefa (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, processo_instancia_id uuid NULL, titulo text NOT NULL, descricao text NULL, responsavel_usuario_id uuid NULL, status text NOT NULL DEFAULT 'pendente', vencimento_em timestamptz NULL, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NOT NULL DEFAULT now(), atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NULL);
CREATE TABLE IF NOT EXISTS integrarp.tarefa_comentario (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, tarefa_id uuid NOT NULL, comentario text NOT NULL, status text NOT NULL DEFAULT 'ativo', criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NOT NULL DEFAULT now(), atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NULL);

CREATE TABLE IF NOT EXISTS integrarp.fatura (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, pedido_id uuid NULL, numero text NOT NULL, status text NOT NULL DEFAULT 'emitida', total numeric(18,2) NOT NULL DEFAULT 0, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NOT NULL DEFAULT now(), atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NULL, UNIQUE(tenant_id,numero));
CREATE TABLE IF NOT EXISTS integrarp.fatura_item (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, fatura_id uuid NOT NULL, descricao text NOT NULL, quantidade numeric(18,3) NOT NULL, valor_unitario numeric(18,2) NOT NULL, total numeric(18,2) NOT NULL, status text NOT NULL DEFAULT 'ativo', criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NOT NULL DEFAULT now(), atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NULL);
CREATE TABLE IF NOT EXISTS integrarp.titulo_financeiro (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, fatura_id uuid NULL, valor numeric(18,2) NOT NULL, vencimento_em date NOT NULL, status text NOT NULL DEFAULT 'aberto', criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NOT NULL DEFAULT now(), atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NULL);
CREATE TABLE IF NOT EXISTS integrarp.boleto_fake (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, titulo_financeiro_id uuid NOT NULL, linha_digitavel text NOT NULL, status text NOT NULL DEFAULT 'gerado', criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NOT NULL DEFAULT now(), atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NULL);

CREATE TABLE IF NOT EXISTS integrarp.outbox_evento (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, tipo_evento text NOT NULL, canal text NULL, origem_tipo text NULL, origem_id uuid NULL, prioridade text NOT NULL DEFAULT 'normal', payload_json jsonb NOT NULL DEFAULT '{}', status text NOT NULL DEFAULT 'pendente', tentativas int NOT NULL DEFAULT 0, max_tentativas int NOT NULL DEFAULT 5, erro text NULL, processado_em timestamptz NULL, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NOT NULL DEFAULT now(), atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NULL);
CREATE TABLE IF NOT EXISTS integrarp.outbox_processamento_log (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, outbox_evento_id uuid NOT NULL, status text NOT NULL, mensagem text NULL, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NOT NULL DEFAULT now(), atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NULL);

CREATE TABLE IF NOT EXISTS integrarp.jornada_cliente (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, codigo text NOT NULL, nome text NOT NULL, status text NOT NULL DEFAULT 'ativo', criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NOT NULL DEFAULT now(), atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NULL, UNIQUE(tenant_id,codigo));
CREATE TABLE IF NOT EXISTS integrarp.jornada_etapa (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, jornada_cliente_id uuid NOT NULL, codigo text NOT NULL, titulo text NOT NULL, ordem int NOT NULL, status text NOT NULL DEFAULT 'ativo', criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NOT NULL DEFAULT now(), atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NULL);
CREATE TABLE IF NOT EXISTS integrarp.jornada_usuario_progresso (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, usuario_id uuid NOT NULL, jornada_etapa_id uuid NOT NULL, status text NOT NULL DEFAULT 'pendente', concluido_em timestamptz NULL, criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NOT NULL DEFAULT now(), atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NULL, UNIQUE(tenant_id,usuario_id,jornada_etapa_id));
CREATE TABLE IF NOT EXISTS integrarp.jornada_acao_recomendada (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, usuario_id uuid NULL, titulo text NOT NULL, descricao text NOT NULL, prioridade text NOT NULL DEFAULT 'media', rota_web text NULL, status text NOT NULL DEFAULT 'pendente', criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NOT NULL DEFAULT now(), atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NULL);

CREATE TABLE IF NOT EXISTS integrarp.auditoria_evento (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, usuario_id uuid NULL, entidade text NOT NULL, entidade_id uuid NULL, acao text NOT NULL, dados_json jsonb NULL, status text NOT NULL DEFAULT 'registrado', criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NOT NULL DEFAULT now(), atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NULL);
CREATE TABLE IF NOT EXISTS integrarp.template_operacional (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, codigo text NOT NULL, nome text NOT NULL, descricao text NULL, status text NOT NULL DEFAULT 'ativo', criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NOT NULL DEFAULT now(), atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NULL, UNIQUE(tenant_id,codigo));
CREATE TABLE IF NOT EXISTS integrarp.template_operacional_etapa (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, template_operacional_id uuid NOT NULL, titulo text NOT NULL, ordem int NOT NULL, status text NOT NULL DEFAULT 'ativo', criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NOT NULL DEFAULT now(), atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NULL);
CREATE TABLE IF NOT EXISTS integrarp.template_instalacao (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, template_operacional_id uuid NOT NULL, processo_definicao_id uuid NULL, status text NOT NULL DEFAULT 'instalado', criado_em timestamptz NOT NULL DEFAULT now(), criado_por_usuario_id uuid NULL, atualizado_em timestamptz NOT NULL DEFAULT now(), atualizado_por_usuario_id uuid NULL, excluido_em timestamptz NULL, metadata_json jsonb NULL);

DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['tenant','usuario','perfil','permissao','usuario_perfil','setor','cargo','cliente','cliente_contato','cliente_endereco','produto_categoria','produto','estoque_local','estoque_movimento','estoque_saldo','estoque_reserva','pedido','pedido_item','pedido_historico_status','processo_definicao','processo_instancia','tarefa','tarefa_comentario','fatura','fatura_item','titulo_financeiro','boleto_fake','outbox_evento','outbox_processamento_log','jornada_cliente','jornada_etapa','jornada_usuario_progresso','jornada_acao_recomendada','auditoria_evento','template_operacional','template_operacional_etapa','template_instalacao'] LOOP
    IF t <> 'tenant' THEN EXECUTE format('CREATE INDEX IF NOT EXISTS ix_%s_tenant_id ON integrarp.%I (tenant_id)', t, t); END IF;
    EXECUTE format('CREATE INDEX IF NOT EXISTS ix_%s_status ON integrarp.%I (status)', t, t);
    EXECUTE format('CREATE INDEX IF NOT EXISTS ix_%s_criado_em ON integrarp.%I (criado_em)', t, t);
    EXECUTE format('DROP TRIGGER IF EXISTS trg_%s_atualizado_em ON integrarp.%I', t, t);
    EXECUTE format('CREATE TRIGGER trg_%s_atualizado_em BEFORE UPDATE ON integrarp.%I FOR EACH ROW EXECUTE FUNCTION integrarp.fn_set_atualizado_em()', t, t);
  END LOOP;
END $$;

CREATE INDEX IF NOT EXISTS ix_cliente_busca ON integrarp.cliente USING gin (to_tsvector('portuguese', coalesce(razao_social,'') || ' ' || coalesce(nome_fantasia,'') || ' ' || coalesce(documento,'')));
CREATE INDEX IF NOT EXISTS ix_produto_busca ON integrarp.produto USING gin (to_tsvector('portuguese', coalesce(sku,'') || ' ' || coalesce(nome,'')));
CREATE INDEX IF NOT EXISTS ix_pedido_cliente_status ON integrarp.pedido (tenant_id, cliente_id, status);
CREATE INDEX IF NOT EXISTS ix_tarefa_responsavel_status ON integrarp.tarefa (tenant_id, responsavel_usuario_id, status);
CREATE INDEX IF NOT EXISTS ix_outbox_status_tentativas ON integrarp.outbox_evento (tenant_id, status, tentativas);
