using System.Data;
using Dapper;
using IntegraRP.Application.Commercial;
using IntegraRP.Contracts.Commercial;
using IntegraRP.Infrastructure.Data;

namespace IntegraRP.Infrastructure.Repositories.Postgres.Commercial;

public sealed class PostgresCommercialOperationsRepository(IDbConnectionFactory connections) : ICommercialOperationsRepository
{
    public async Task<IReadOnlyList<CustomerContactDto>> ListContactsAsync(Guid tenantId, Guid customerId, CancellationToken ct)
    { using var db=await connections.OpenConnectionAsync(ct); return (await db.QueryAsync<CustomerContactDto>(new CommandDefinition(ContactSelect+" WHERE tenant_id=@tenantId AND cliente_id=@customerId AND excluido_em IS NULL ORDER BY principal DESC,nome",new{tenantId,customerId},cancellationToken:ct))).AsList(); }
    public async Task<CustomerContactDto> AddContactAsync(Guid tenantId, Guid userId, Guid customerId, SaveCustomerContactRequest r, CancellationToken ct)
    { Required(r.Name,"Nome"); using var db=await connections.OpenConnectionAsync(ct); using var tx=db.BeginTransaction(); await RequireCustomer(db,tx,tenantId,customerId,ct); if(r.Primary) await ClearPrimary(db,tx,"cliente_contato",tenantId,customerId,ct); var id=Guid.NewGuid(); await db.ExecuteAsync(new CommandDefinition("INSERT INTO integrarp.cliente_contato(id,tenant_id,cliente_id,nome,cargo,email,telefone,whatsapp,principal,status,criado_em,criado_por_usuario_id,atualizado_em,atualizado_por_usuario_id,row_version) VALUES(@id,@tenantId,@customerId,@Name,@Role,@Email,@Phone,@WhatsApp,@Primary,'ativo',now(),@userId,now(),@userId,1)",new{id,tenantId,userId,customerId,r.Name,r.Role,r.Email,r.Phone,r.WhatsApp,r.Primary},tx,cancellationToken:ct)); tx.Commit(); return new(id,r.Name,r.Role,r.Email,r.Phone,r.WhatsApp,r.Primary,1); }
    public async Task<CustomerContactDto> UpdateContactAsync(Guid tenantId, Guid userId, Guid customerId, Guid id, SaveCustomerContactRequest r, CancellationToken ct)
    { Required(r.Name,"Nome"); var version=r.RowVersion??throw new ArgumentException("row_version obrigatório."); using var db=await connections.OpenConnectionAsync(ct); using var tx=db.BeginTransaction(); if(r.Primary) await ClearPrimary(db,tx,"cliente_contato",tenantId,customerId,ct); var changed=await db.ExecuteAsync(new CommandDefinition("UPDATE integrarp.cliente_contato SET nome=@Name,cargo=@Role,email=@Email,telefone=@Phone,whatsapp=@WhatsApp,principal=@Primary,atualizado_em=now(),atualizado_por_usuario_id=@userId,row_version=row_version+1 WHERE tenant_id=@tenantId AND cliente_id=@customerId AND id=@id AND row_version=@version AND excluido_em IS NULL",new{id,tenantId,userId,customerId,version,r.Name,r.Role,r.Email,r.Phone,r.WhatsApp,r.Primary},tx,cancellationToken:ct)); Concurrency(changed); tx.Commit(); return new(id,r.Name,r.Role,r.Email,r.Phone,r.WhatsApp,r.Primary,version+1); }
    public Task DeleteContactAsync(Guid tenantId, Guid userId, Guid customerId, Guid id, long version, CancellationToken ct) => SoftDelete("cliente_contato",tenantId,userId,customerId,id,version,ct);
    public async Task<IReadOnlyList<CustomerAddressDto>> ListAddressesAsync(Guid tenantId, Guid customerId, CancellationToken ct)
    { using var db=await connections.OpenConnectionAsync(ct); return (await db.QueryAsync<CustomerAddressDto>(new CommandDefinition(AddressSelect+" WHERE tenant_id=@tenantId AND cliente_id=@customerId AND excluido_em IS NULL ORDER BY principal DESC,logradouro",new{tenantId,customerId},cancellationToken:ct))).AsList(); }
    public async Task<CustomerAddressDto> AddAddressAsync(Guid tenantId, Guid userId, Guid customerId, SaveCustomerAddressRequest r, CancellationToken ct)
    { ValidateAddress(r); using var db=await connections.OpenConnectionAsync(ct); using var tx=db.BeginTransaction(); await RequireCustomer(db,tx,tenantId,customerId,ct); if(r.Primary) await ClearPrimary(db,tx,"cliente_endereco",tenantId,customerId,ct); var id=Guid.NewGuid(); await db.ExecuteAsync(new CommandDefinition("INSERT INTO integrarp.cliente_endereco(id,tenant_id,cliente_id,tipo,cep,logradouro,numero,complemento,bairro,cidade,uf,cobranca,entrega,principal,status,criado_em,criado_por_usuario_id,atualizado_em,atualizado_por_usuario_id,row_version) VALUES(@id,@tenantId,@customerId,@Type,@PostalCode,@Street,@Number,@Complement,@District,@City,@State,@Billing,@Delivery,@Primary,'ativo',now(),@userId,now(),@userId,1)",new{id,tenantId,userId,customerId,r.Type,r.PostalCode,r.Street,r.Number,r.Complement,r.District,r.City,r.State,r.Billing,r.Delivery,r.Primary},tx,cancellationToken:ct)); tx.Commit(); return new(id,r.Type,r.PostalCode,r.Street,r.Number,r.Complement,r.District,r.City,r.State,r.Billing,r.Delivery,r.Primary,1); }
    public async Task<CustomerAddressDto> UpdateAddressAsync(Guid tenantId, Guid userId, Guid customerId, Guid id, SaveCustomerAddressRequest r, CancellationToken ct)
    { ValidateAddress(r); var version=r.RowVersion??throw new ArgumentException("row_version obrigatório."); using var db=await connections.OpenConnectionAsync(ct); using var tx=db.BeginTransaction(); if(r.Primary) await ClearPrimary(db,tx,"cliente_endereco",tenantId,customerId,ct); var changed=await db.ExecuteAsync(new CommandDefinition("UPDATE integrarp.cliente_endereco SET tipo=@Type,cep=@PostalCode,logradouro=@Street,numero=@Number,complemento=@Complement,bairro=@District,cidade=@City,uf=@State,cobranca=@Billing,entrega=@Delivery,principal=@Primary,atualizado_em=now(),atualizado_por_usuario_id=@userId,row_version=row_version+1 WHERE tenant_id=@tenantId AND cliente_id=@customerId AND id=@id AND row_version=@version AND excluido_em IS NULL",new{id,tenantId,userId,customerId,version,r.Type,r.PostalCode,r.Street,r.Number,r.Complement,r.District,r.City,r.State,r.Billing,r.Delivery,r.Primary},tx,cancellationToken:ct)); Concurrency(changed); tx.Commit(); return new(id,r.Type,r.PostalCode,r.Street,r.Number,r.Complement,r.District,r.City,r.State,r.Billing,r.Delivery,r.Primary,version+1); }
    public Task DeleteAddressAsync(Guid tenantId, Guid userId, Guid customerId, Guid id, long version, CancellationToken ct) => SoftDelete("cliente_endereco",tenantId,userId,customerId,id,version,ct);

    public async Task<IReadOnlyList<OpportunityDto>> ListOpportunitiesAsync(Guid tenantId,CancellationToken ct)
    { using var db=await connections.OpenConnectionAsync(ct); return (await db.QueryAsync<OpportunityDto>(new CommandDefinition(OpportunitySelect+" WHERE o.tenant_id=@tenantId AND o.removido_em IS NULL ORDER BY o.atualizado_em DESC",new{tenantId},cancellationToken:ct))).AsList(); }
    public async Task<OpportunityDto> CreateOpportunityAsync(Guid tenantId,Guid userId,CreateOpportunityRequest r,string correlationId,CancellationToken ct)
    { Required(r.Name,"Nome"); if(r.ExpectedValue<0) throw new ArgumentException("Valor inválido."); using var db=await connections.OpenConnectionAsync(ct); using var tx=db.BeginTransaction(); var customer=await RequireCustomer(db,tx,tenantId,r.CustomerId,ct); var id=Guid.NewGuid(); await db.ExecuteAsync(new CommandDefinition("INSERT INTO integrarp.oportunidade_comercial(id,tenant_id,cliente_id,nome,etapa,probabilidade,valor_esperado,fechamento_previsto,proxima_acao,proxima_acao_em,responsavel_id,criado_por,atualizado_por) VALUES(@id,@tenantId,@CustomerId,@Name,'nova',10,@ExpectedValue,@ExpectedCloseDate,@NextAction,@NextActionAt,@userId,@userId,@userId); INSERT INTO integrarp.outbox_evento(id,tenant_id,tipo,payload_json,status,tentativas,correlation_id,criado_em,atualizado_em) VALUES(gen_random_uuid(),@tenantId,'oportunidade.criada',jsonb_build_object('oportunidadeId',@id),'pendente',0,@correlationId,now(),now())",new{id,tenantId,userId,r.CustomerId,r.Name,r.ExpectedValue,r.ExpectedCloseDate,r.NextAction,r.NextActionAt,correlationId},tx,cancellationToken:ct)); tx.Commit(); return new(id,r.CustomerId,customer,r.Name,"nova",10,r.ExpectedValue,r.ExpectedCloseDate,r.NextAction,r.NextActionAt,userId,1); }
    public async Task<OpportunityDto> ChangeOpportunityStageAsync(Guid tenantId,Guid userId,Guid id,ChangeOpportunityStageRequest r,string correlationId,CancellationToken ct)
    { var allowed=new[]{"nova","qualificacao","diagnostico","proposta","negociacao","ganha","perdida","cancelada"}; if(!allowed.Contains(r.Stage)) throw new ArgumentException("Etapa inválida."); using var db=await connections.OpenConnectionAsync(ct); using var tx=db.BeginTransaction(); var changed=await db.ExecuteAsync(new CommandDefinition("UPDATE integrarp.oportunidade_comercial SET etapa=@Stage,probabilidade=CASE WHEN @Stage='ganha' THEN 100 WHEN @Stage IN ('perdida','cancelada') THEN 0 ELSE probabilidade END,atualizado_em=now(),atualizado_por=@userId,row_version=row_version+1 WHERE tenant_id=@tenantId AND id=@id AND row_version=@RowVersion AND removido_em IS NULL",new{tenantId,userId,id,r.Stage,r.RowVersion},tx,cancellationToken:ct)); Concurrency(changed); await Event(db,tx,tenantId,userId,"oportunidade",id,"oportunidade.etapa_alterada",correlationId,ct); tx.Commit(); return await GetOpportunity(tenantId,id,ct); }

    public async Task<IReadOnlyList<QuoteDto>> ListQuotesAsync(Guid tenantId,CancellationToken ct)
    { using var db=await connections.OpenConnectionAsync(ct); var headers=(await db.QueryAsync<QuoteRow>(new CommandDefinition(QuoteSelect+" WHERE q.tenant_id=@tenantId AND q.removido_em IS NULL ORDER BY q.atualizado_em DESC",new{tenantId},cancellationToken:ct))).AsList(); return headers.Select(x=>x.ToDto([])).ToList(); }
    public async Task<QuoteDto> GetQuoteAsync(Guid tenantId,Guid id,CancellationToken ct)
    { using var db=await connections.OpenConnectionAsync(ct); var row=await db.QuerySingleOrDefaultAsync<QuoteRow>(new CommandDefinition(QuoteSelect+" WHERE q.tenant_id=@tenantId AND q.id=@id AND q.removido_em IS NULL",new{tenantId,id},cancellationToken:ct)) ?? throw new KeyNotFoundException("Orçamento não encontrado."); var items=(await db.QueryAsync<QuoteItemDto>(new CommandDefinition(ItemSelect+" WHERE i.tenant_id=@tenantId AND i.orcamento_id=@id AND i.removido_em IS NULL ORDER BY i.criado_em",new{tenantId,id},cancellationToken:ct))).AsList(); return row.ToDto(items); }
    public async Task<QuoteDto> CreateQuoteAsync(Guid tenantId,Guid userId,CreateQuoteRequest r,string correlationId,CancellationToken ct)
    { if(r.Validity<DateOnly.FromDateTime(DateTime.UtcNow)) throw new ArgumentException("Validade inválida."); Required(r.IdempotencyKey,"Idempotência"); using var db=await connections.OpenConnectionAsync(ct); using var tx=db.BeginTransaction(); await RequireCustomer(db,tx,tenantId,r.CustomerId,ct); var existing=await db.QuerySingleOrDefaultAsync<Guid?>(new CommandDefinition("SELECT id FROM integrarp.orcamento_v145 WHERE tenant_id=@tenantId AND idempotency_key=@IdempotencyKey",new{tenantId,r.IdempotencyKey},tx,cancellationToken:ct)); if(existing.HasValue){tx.Commit();return await GetQuoteAsync(tenantId,existing.Value,ct);} var id=Guid.NewGuid(); var number=$"ORC-{DateTime.UtcNow:yyyy}-{id.ToString("N")[..6].ToUpperInvariant()}"; await db.ExecuteAsync(new CommandDefinition("INSERT INTO integrarp.orcamento_v145(id,tenant_id,numero,cliente_id,oportunidade_id,tabela_preco_id,validade,idempotency_key,criado_por,atualizado_por) VALUES(@id,@tenantId,@number,@CustomerId,@OpportunityId,@PriceListId,@Validity,@IdempotencyKey,@userId,@userId)",new{id,tenantId,userId,number,r.CustomerId,r.OpportunityId,r.PriceListId,r.Validity,r.IdempotencyKey},tx,cancellationToken:ct)); await Event(db,tx,tenantId,userId,"orcamento",id,"orcamento.criado",correlationId,ct); tx.Commit(); return await GetQuoteAsync(tenantId,id,ct); }
    public async Task<QuoteDto> AddQuoteItemAsync(Guid tenantId,Guid userId,Guid id,AddQuoteItemRequest r,string correlationId,CancellationToken ct)
    { if(r.Quantity<=0||r.DiscountPercent is <0 or >100) throw new ArgumentException("Quantidade ou desconto inválido."); using var db=await connections.OpenConnectionAsync(ct); using var tx=db.BeginTransaction(); await LockDraftQuote(db,tx,tenantId,id,r.RowVersion,ct); var product=await db.QuerySingleOrDefaultAsync<(string Sku,string Name,decimal Price)>(new CommandDefinition("SELECT p.sku Sku,p.nome Name,COALESCE(tpi.preco,p.preco) Price FROM integrarp.orcamento_v145 q JOIN integrarp.produto p ON p.tenant_id=q.tenant_id AND p.id=@ProductId LEFT JOIN integrarp.tabela_preco_item tpi ON tpi.tenant_id=q.tenant_id AND tpi.tabela_preco_id=q.tabela_preco_id AND tpi.produto_id=p.id AND tpi.removido_em IS NULL WHERE q.tenant_id=@tenantId AND q.id=@id AND p.status='ativo'",new{tenantId,id,r.ProductId},tx,cancellationToken:ct)); if(string.IsNullOrEmpty(product.Sku)) throw new InvalidOperationException("Produto ativo não encontrado."); var subtotal=decimal.Round(r.Quantity*product.Price,2); var discount=decimal.Round(subtotal*r.DiscountPercent/100m,2); await db.ExecuteAsync(new CommandDefinition("INSERT INTO integrarp.orcamento_item_v145(id,tenant_id,orcamento_id,produto_id,descricao,quantidade,preco_unitario,desconto_percentual,subtotal,desconto,total,criado_por,atualizado_por) VALUES(gen_random_uuid(),@tenantId,@id,@ProductId,@Name,@Quantity,@Price,@DiscountPercent,@subtotal,@discount,@total,@userId,@userId)",new{tenantId,userId,id,r.ProductId,product.Name,r.Quantity,product.Price,r.DiscountPercent,subtotal,discount,total=subtotal-discount},tx,cancellationToken:ct)); await Recalculate(db,tx,tenantId,userId,id,ct); await Event(db,tx,tenantId,userId,"orcamento",id,"orcamento.item_adicionado",correlationId,ct); tx.Commit(); return await GetQuoteAsync(tenantId,id,ct); }
    public async Task<QuoteDto> ApplyQuoteDiscountAsync(Guid tenantId,Guid userId,Guid id,ApplyQuoteDiscountRequest r,string correlationId,CancellationToken ct)
    { if(r.DiscountPercent is <0 or >100) throw new ArgumentException("Desconto inválido."); using var db=await connections.OpenConnectionAsync(ct); using var tx=db.BeginTransaction(); await LockDraftQuote(db,tx,tenantId,id,r.RowVersion,ct); await db.ExecuteAsync(new CommandDefinition("UPDATE integrarp.orcamento_v145 SET desconto_global_percentual=@DiscountPercent,atualizado_por=@userId WHERE tenant_id=@tenantId AND id=@id",new{tenantId,userId,id,r.DiscountPercent},tx,cancellationToken:ct)); await Recalculate(db,tx,tenantId,userId,id,ct); await Event(db,tx,tenantId,userId,"orcamento",id,"orcamento.desconto_aplicado",correlationId,ct); tx.Commit(); return await GetQuoteAsync(tenantId,id,ct); }
    public async Task<QuoteDto> SubmitQuoteAsync(Guid tenantId,Guid userId,Guid id,QuoteDecisionRequest r,string correlationId,CancellationToken ct)
    { using var db=await connections.OpenConnectionAsync(ct); using var tx=db.BeginTransaction(); await LockDraftQuote(db,tx,tenantId,id,r.RowVersion,ct); var values=await db.QuerySingleAsync<(decimal Discount,int Items)>(new CommandDefinition("SELECT CASE WHEN subtotal=0 THEN 0 ELSE desconto/subtotal*100 END Discount,(SELECT count(*) FROM integrarp.orcamento_item_v145 i WHERE i.tenant_id=q.tenant_id AND i.orcamento_id=q.id AND i.removido_em IS NULL) Items FROM integrarp.orcamento_v145 q WHERE tenant_id=@tenantId AND id=@id",new{tenantId,id},tx,cancellationToken:ct)); if(values.Items==0) throw new InvalidOperationException("Orçamento sem itens."); var policy=await db.QuerySingleOrDefaultAsync<Guid?>(new CommandDefinition("SELECT id FROM integrarp.politica_desconto WHERE tenant_id=@tenantId AND ativa AND removido_em IS NULL AND @Discount BETWEEN percentual_inicial AND percentual_final ORDER BY prioridade LIMIT 1",new{tenantId,values.Discount},tx,cancellationToken:ct)); if(values.Discount>0&&!policy.HasValue) throw new InvalidOperationException("Nenhuma política válida para o desconto."); await db.ExecuteAsync(new CommandDefinition("UPDATE integrarp.orcamento_v145 SET status='em_aprovacao',atualizado_em=now(),atualizado_por=@userId,row_version=row_version+1 WHERE tenant_id=@tenantId AND id=@id; INSERT INTO integrarp.aprovacao_desconto(id,tenant_id,orcamento_id,politica_id,solicitado_por,criado_por,atualizado_por) SELECT gen_random_uuid(),@tenantId,@id,@policy,@userId,@userId,@userId WHERE @policy IS NOT NULL; INSERT INTO integrarp.notificacao_usuario(id,tenant_id,usuario_id,tipo,titulo,mensagem,icone,url,prioridade,correlation_id,criado_em,row_version) VALUES(gen_random_uuid(),@tenantId,@userId,'orcamento.aprovacao','Orçamento aguardando aprovação','Revise valores e desconto.','check2-square',concat('/quotes/',@id),'alta',@correlationId,now(),1)",new{tenantId,userId,id,policy,correlationId},tx,cancellationToken:ct)); await Outbox(db,tx,tenantId,id,"orcamento.submetido",correlationId,ct); tx.Commit(); return await GetQuoteAsync(tenantId,id,ct); }
    public async Task<QuoteDto> DecideQuoteAsync(Guid tenantId,Guid userId,Guid id,bool approve,QuoteDecisionRequest r,string correlationId,CancellationToken ct)
    { if(!approve) Required(r.Reason,"Motivo"); using var db=await connections.OpenConnectionAsync(ct); using var tx=db.BeginTransaction(); var changed=await db.ExecuteAsync(new CommandDefinition("UPDATE integrarp.orcamento_v145 SET status=@status,aprovado_por=CASE WHEN @approve THEN @userId END,aprovado_em=CASE WHEN @approve THEN now() END,motivo_rejeicao=CASE WHEN NOT @approve THEN @Reason END,atualizado_em=now(),atualizado_por=@userId,row_version=row_version+1 WHERE tenant_id=@tenantId AND id=@id AND status='em_aprovacao' AND row_version=@RowVersion",new{tenantId,userId,id,approve,status=approve?"aprovado":"rejeitado",r.Reason,r.RowVersion},tx,cancellationToken:ct)); Concurrency(changed); await db.ExecuteAsync(new CommandDefinition("UPDATE integrarp.aprovacao_desconto SET status=@status,decidido_por=@userId,decidido_em=now(),motivo=@Reason,atualizado_em=now(),atualizado_por=@userId,row_version=row_version+1 WHERE tenant_id=@tenantId AND orcamento_id=@id AND status='pendente'",new{tenantId,userId,id,status=approve?"aprovada":"rejeitada",r.Reason},tx,cancellationToken:ct)); await Outbox(db,tx,tenantId,id,approve?"orcamento.aprovado":"orcamento.rejeitado",correlationId,ct); tx.Commit(); return await GetQuoteAsync(tenantId,id,ct); }

    private async Task<OpportunityDto> GetOpportunity(Guid tenantId,Guid id,CancellationToken ct){using var db=await connections.OpenConnectionAsync(ct);return await db.QuerySingleAsync<OpportunityDto>(new CommandDefinition(OpportunitySelect+" WHERE o.tenant_id=@tenantId AND o.id=@id",new{tenantId,id},cancellationToken:ct));}
    private static async Task<string> RequireCustomer(IDbConnection db,IDbTransaction tx,Guid tenantId,Guid id,CancellationToken ct)=>await db.QuerySingleOrDefaultAsync<string>(new CommandDefinition("SELECT nome FROM integrarp.cliente WHERE tenant_id=@tenantId AND id=@id AND status='ativo' AND excluido_em IS NULL",new{tenantId,id},tx,cancellationToken:ct))??throw new KeyNotFoundException("Cliente ativo não encontrado.");
    private static Task ClearPrimary(IDbConnection db,IDbTransaction tx,string table,Guid tenantId,Guid customerId,CancellationToken ct)=>db.ExecuteAsync(new CommandDefinition($"UPDATE integrarp.{table} SET principal=false,row_version=row_version+1 WHERE tenant_id=@tenantId AND cliente_id=@customerId AND principal AND excluido_em IS NULL",new{tenantId,customerId},tx,cancellationToken:ct));
    private async Task SoftDelete(string table,Guid tenantId,Guid userId,Guid customerId,Guid id,long version,CancellationToken ct){using var db=await connections.OpenConnectionAsync(ct);var changed=await db.ExecuteAsync(new CommandDefinition($"UPDATE integrarp.{table} SET excluido_em=now(),atualizado_por_usuario_id=@userId,row_version=row_version+1 WHERE tenant_id=@tenantId AND cliente_id=@customerId AND id=@id AND row_version=@version AND excluido_em IS NULL",new{tenantId,userId,customerId,id,version},cancellationToken:ct));Concurrency(changed);}
    private static async Task LockDraftQuote(IDbConnection db,IDbTransaction tx,Guid tenantId,Guid id,long version,CancellationToken ct){var q=await db.QuerySingleOrDefaultAsync<(string Status,long Version)>(new CommandDefinition("SELECT status Status,row_version Version FROM integrarp.orcamento_v145 WHERE tenant_id=@tenantId AND id=@id FOR UPDATE",new{tenantId,id},tx,cancellationToken:ct));if(q.Status is null)throw new KeyNotFoundException("Orçamento não encontrado.");if(q.Version!=version)throw new DBConcurrencyException("Orçamento alterado por outro usuário.");if(q.Status!="rascunho")throw new InvalidOperationException("Somente rascunho pode ser alterado.");}
    private static Task Recalculate(IDbConnection db,IDbTransaction tx,Guid tenantId,Guid userId,Guid id,CancellationToken ct)=>db.ExecuteAsync(new CommandDefinition("UPDATE integrarp.orcamento_v145 q SET subtotal=x.subtotal,desconto=x.item_desconto+round((x.subtotal-x.item_desconto)*q.desconto_global_percentual/100,2),total=GREATEST(0,x.subtotal-x.item_desconto-round((x.subtotal-x.item_desconto)*q.desconto_global_percentual/100,2)),atualizado_em=now(),atualizado_por=@userId,row_version=row_version+1 FROM (SELECT COALESCE(sum(subtotal),0) subtotal,COALESCE(sum(desconto),0) item_desconto FROM integrarp.orcamento_item_v145 WHERE tenant_id=@tenantId AND orcamento_id=@id AND removido_em IS NULL)x WHERE q.tenant_id=@tenantId AND q.id=@id",new{tenantId,userId,id},tx,cancellationToken:ct));
    private static Task Event(IDbConnection db,IDbTransaction tx,Guid tenantId,Guid userId,string type,Guid id,string name,string correlationId,CancellationToken ct)=>db.ExecuteAsync(new CommandDefinition("INSERT INTO integrarp.historico_operacional_v145(tenant_id,entidade_tipo,entidade_id,evento,correlation_id,criado_por) VALUES(@tenantId,@type,@id,@name,@correlationId,@userId)",new{tenantId,userId,type,id,name,correlationId},tx,cancellationToken:ct));
    private static Task Outbox(IDbConnection db,IDbTransaction tx,Guid tenantId,Guid id,string type,string correlationId,CancellationToken ct)=>db.ExecuteAsync(new CommandDefinition("INSERT INTO integrarp.outbox_evento(id,tenant_id,tipo,payload_json,status,tentativas,correlation_id,criado_em,atualizado_em) VALUES(gen_random_uuid(),@tenantId,@type,jsonb_build_object('id',@id),'pendente',0,@correlationId,now(),now())",new{tenantId,id,type,correlationId},tx,cancellationToken:ct));
    private static void Concurrency(int changed){if(changed!=1)throw new DBConcurrencyException("Registro não encontrado ou alterado por outro usuário.");}
    private static void Required(string? value,string field){if(string.IsNullOrWhiteSpace(value))throw new ArgumentException($"{field} obrigatório.");}
    private static void ValidateAddress(SaveCustomerAddressRequest r){Required(r.Type,"Tipo");Required(r.Street,"Logradouro");Required(r.City,"Cidade");}
    private const string ContactSelect="SELECT id Id,nome Name,cargo Role,email Email,telefone Phone,whatsapp WhatsApp,principal Primary,row_version RowVersion FROM integrarp.cliente_contato";
    private const string AddressSelect="SELECT id Id,tipo Type,cep PostalCode,logradouro Street,numero Number,complemento Complement,bairro District,cidade City,uf State,cobranca Billing,entrega Delivery,principal Primary,row_version RowVersion FROM integrarp.cliente_endereco";
    private const string OpportunitySelect="SELECT o.id Id,o.cliente_id CustomerId,c.nome CustomerName,o.nome Name,o.etapa Stage,o.probabilidade Probability,o.valor_esperado ExpectedValue,o.fechamento_previsto ExpectedCloseDate,o.proxima_acao NextAction,o.proxima_acao_em NextActionAt,o.responsavel_id OwnerId,o.row_version RowVersion FROM integrarp.oportunidade_comercial o JOIN integrarp.cliente c ON c.tenant_id=o.tenant_id AND c.id=o.cliente_id";
    private const string QuoteSelect="SELECT q.id Id,q.numero Number,q.cliente_id CustomerId,c.nome CustomerName,q.validade Validity,q.status Status,q.desconto_global_percentual GlobalDiscountPercent,q.subtotal Subtotal,q.desconto Discount,q.total Total,q.row_version RowVersion FROM integrarp.orcamento_v145 q JOIN integrarp.cliente c ON c.tenant_id=q.tenant_id AND c.id=q.cliente_id";
    private const string ItemSelect="SELECT i.id Id,i.produto_id ProductId,p.sku Sku,i.descricao Description,i.quantidade Quantity,i.preco_unitario UnitPrice,i.desconto_percentual DiscountPercent,i.subtotal Subtotal,i.desconto Discount,i.total Total FROM integrarp.orcamento_item_v145 i JOIN integrarp.produto p ON p.tenant_id=i.tenant_id AND p.id=i.produto_id";
    private sealed record QuoteRow(Guid Id,string Number,Guid CustomerId,string CustomerName,DateOnly Validity,string Status,decimal GlobalDiscountPercent,decimal Subtotal,decimal Discount,decimal Total,long RowVersion){public QuoteDto ToDto(IReadOnlyList<QuoteItemDto> items)=>new(Id,Number,CustomerId,CustomerName,Validity,Status,GlobalDiscountPercent,Subtotal,Discount,Total,RowVersion,items);}
}
